CREATE TABLE COMTECOPSEQ
(
	TABLE_NAME            VARCHAR(20) NOT NULL,
	NEXT_ID               NUMERIC(30) NULL,
	PRIMARY KEY (TABLE_NAME)
);
CREATE UNIQUE INDEX COMTECOPSEQ_PK ON COMTECOPSEQ (TABLE_NAME);


CREATE TABLE COMTNFILE
(
	ATCH_FILE_ID          CHAR(20) NOT NULL,
	CREAT_DT              TIMESTAMP NOT NULL,
	USE_AT                CHAR(1) NULL,
	PRIMARY KEY (ATCH_FILE_ID)
);
CREATE UNIQUE INDEX COMTNFILE_PK ON COMTNFILE (ATCH_FILE_ID);


CREATE TABLE COMTNFILEDETAIL
(
	ATCH_FILE_ID          CHAR(20) NOT NULL,
	FILE_SN               NUMERIC(10) NOT NULL,
	FILE_STRE_COURS       VARCHAR(2000) NOT NULL,
	STRE_FILE_NM          VARCHAR(255) NOT NULL,
	ORIGNL_FILE_NM        VARCHAR(255) NULL,
	FILE_EXTSN            VARCHAR(20) NOT NULL,
	FILE_CN               TEXT NULL,
	FILE_SIZE             NUMERIC(8) NULL,
	PRIMARY KEY (ATCH_FILE_ID,FILE_SN),
	FOREIGN KEY (ATCH_FILE_ID) REFERENCES COMTNFILE(ATCH_FILE_ID)
);
CREATE UNIQUE INDEX COMTNFILEDETAIL_PK ON COMTNFILEDETAIL (ATCH_FILE_ID, FILE_SN);
CREATE INDEX COMTNFILEDETAIL_i01 ON COMTNFILEDETAIL (ATCH_FILE_ID);


CREATE TABLE COMTNLOGINPOLICY
(
	EMPLYR_ID             VARCHAR(20) NOT NULL,
	IP_INFO               VARCHAR(23) NOT NULL,
	DPLCT_PERM_AT         CHAR(1) NOT NULL,
	LMTT_AT               CHAR(1) NOT NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     TIMESTAMP NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       TIMESTAMP NULL,
	PRIMARY KEY (EMPLYR_ID)
);
CREATE UNIQUE INDEX COMTNLOGINPOLICY_PK ON COMTNLOGINPOLICY (EMPLYR_ID);


CREATE TABLE COMTNORGNZTINFO
(
	ORGNZT_ID             CHAR(20) NOT NULL,
	ORGNZT_NM             VARCHAR(20) NOT NULL,
	ORGNZT_DC             VARCHAR(100) NULL,
	PRIMARY KEY (ORGNZT_ID)
);
CREATE UNIQUE INDEX COMTNORGNZTINFO_PK ON COMTNORGNZTINFO (ORGNZT_ID);


CREATE TABLE COMTNAUTHORGROUPINFO
(
	GROUP_ID              CHAR(20) NOT NULL,
	GROUP_NM              VARCHAR(60) NOT NULL,
	GROUP_CREAT_DE        TIMESTAMP NOT NULL,
	GROUP_DC              VARCHAR(100) NULL,
	PRIMARY KEY (GROUP_ID)
);
CREATE UNIQUE INDEX COMTNAUTHORGROUPINFO_PK ON COMTNAUTHORGROUPINFO (GROUP_ID);


CREATE TABLE COMTNEMPLYRINFO
(
	EMPLYR_ID             VARCHAR(20) NOT NULL,
	ORGNZT_ID             CHAR(20) NULL,
	USER_NM               VARCHAR(60) NOT NULL,
	PASSWORD              VARCHAR(200) NOT NULL,
	EMPL_NO               VARCHAR(20) NULL,
	IHIDNUM               VARCHAR(200) NULL,
	SEXDSTN_CODE          CHAR(1) NULL,
	BRTHDY                CHAR(20) NULL,
	FXNUM                 VARCHAR(20) NULL,
	HOUSE_ADRES           VARCHAR(100) NOT NULL,
	PASSWORD_HINT         VARCHAR(100) NOT NULL,
	PASSWORD_CNSR         VARCHAR(100) NOT NULL,
	HOUSE_END_TELNO       VARCHAR(4) NOT NULL,
	AREA_NO               VARCHAR(4) NOT NULL,
	DETAIL_ADRES          VARCHAR(100) NULL,
	ZIP                   VARCHAR(6) NOT NULL,
	OFFM_TELNO            VARCHAR(20) NULL,
	MBTLNUM               VARCHAR(20) NULL,
	EMAIL_ADRES           VARCHAR(50) NULL,
	OFCPS_NM              VARCHAR(60) NULL,
	HOUSE_MIDDLE_TELNO    VARCHAR(4) NOT NULL,
	GROUP_ID              CHAR(20) NULL,
	PSTINST_CODE          CHAR(8) NULL,
	EMPLYR_STTUS_CODE     CHAR(1) NOT NULL,
	ESNTL_ID              CHAR(20) NOT NULL,
	CRTFC_DN_VALUE        VARCHAR(100) NULL,
	SBSCRB_DE             TIMESTAMP NULL,
	LOCK_AT               CHAR(1) NULL,
	LOCK_CNT              NUMERIC(3,0) NULL,
	LOCK_LAST_PNTTM       TIMESTAMP NULL,
	PRIMARY KEY (EMPLYR_ID),
	FOREIGN KEY (ORGNZT_ID) REFERENCES COMTNORGNZTINFO(ORGNZT_ID)
		ON DELETE SET NULL,
	FOREIGN KEY (GROUP_ID) REFERENCES COMTNAUTHORGROUPINFO(GROUP_ID)
		ON DELETE SET NULL
);
CREATE UNIQUE INDEX COMTNEMPLYRINFO_PK ON COMTNEMPLYRINFO (EMPLYR_ID);
CREATE INDEX COMTNEMPLYRINFO_i01 ON COMTNEMPLYRINFO (ORGNZT_ID);
CREATE INDEX COMTNEMPLYRINFO_i02 ON COMTNEMPLYRINFO (GROUP_ID);


CREATE TABLE COMTHEMPLYRINFOCHANGEDTLS
(
	EMPLYR_ID             VARCHAR(20) NOT NULL,
	CHANGE_DE             CHAR(20) NOT NULL,
	ORGNZT_ID             CHAR(20) NULL,
	GROUP_ID              CHAR(20) NULL,
	EMPL_NO               VARCHAR(20) NULL,
	SEXDSTN_CODE          CHAR(1) NULL,
	BRTHDY                CHAR(20) NULL,
	FXNUM                 VARCHAR(20) NULL,
	HOUSE_ADRES           VARCHAR(100) NULL,
	HOUSE_END_TELNO       VARCHAR(4) NULL,
	AREA_NO               VARCHAR(4) NULL,
	DETAIL_ADRES          VARCHAR(100) NULL,
	ZIP                   VARCHAR(6) NULL,
	OFFM_TELNO            VARCHAR(20) NULL,
	MBTLNUM               VARCHAR(20) NULL,
	EMAIL_ADRES           VARCHAR(50) NULL,
	HOUSE_MIDDLE_TELNO    VARCHAR(4) NULL,
	PSTINST_CODE          CHAR(8) NULL,
	EMPLYR_STTUS_CODE     CHAR(1) NULL,
	ESNTL_ID              CHAR(20) NULL,
	PRIMARY KEY (EMPLYR_ID,CHANGE_DE),
	FOREIGN KEY (EMPLYR_ID) REFERENCES COMTNEMPLYRINFO(EMPLYR_ID)
);
CREATE UNIQUE INDEX COMTHEMPLYRINFOCHANGEDTLS_PK ON COMTHEMPLYRINFOCHANGEDTLS (EMPLYR_ID, CHANGE_DE);
CREATE INDEX COMTHEMPLYRINFOCHANGEDTLS_i01 ON COMTHEMPLYRINFOCHANGEDTLS (EMPLYR_ID);



CREATE TABLE COMTNENTRPRSMBER
(
	ENTRPRS_MBER_ID       VARCHAR(20) NOT NULL,
	ENTRPRS_SE_CODE       CHAR(8) NULL,
	BIZRNO                VARCHAR(10) NULL,
	JURIRNO               VARCHAR(13) NULL,
	CMPNY_NM              VARCHAR(60) NOT NULL,
	CXFC                  VARCHAR(50) NULL,
	ZIP                   VARCHAR(6) NOT NULL,
	ADRES                 VARCHAR(100) NOT NULL,
	ENTRPRS_MIDDLE_TELNO  VARCHAR(4) NOT NULL,
	FXNUM                 VARCHAR(20) NULL,
	INDUTY_CODE           CHAR(1) NULL,
	APPLCNT_NM            VARCHAR(50) NOT NULL,
	APPLCNT_IHIDNUM       VARCHAR(200) NULL,
	SBSCRB_DE             TIMESTAMP NULL,
	ENTRPRS_MBER_STTUS    VARCHAR(15) NULL,
	ENTRPRS_MBER_PASSWORD  VARCHAR(200) NULL,
	ENTRPRS_MBER_PASSWORD_HINT  VARCHAR(100) NOT NULL,
	ENTRPRS_MBER_PASSWORD_CNSR  VARCHAR(100) NOT NULL,
	GROUP_ID              CHAR(20) NULL,
	DETAIL_ADRES          VARCHAR(100) NULL,
	ENTRPRS_END_TELNO     VARCHAR(4) NOT NULL,
	AREA_NO               VARCHAR(4) NOT NULL,
	APPLCNT_EMAIL_ADRES   VARCHAR(50) NOT NULL,
	ESNTL_ID              CHAR(20) NOT NULL,
	LOCK_AT               CHAR(1) NULL,
	LOCK_CNT              NUMERIC(3) NULL,
	LOCK_LAST_PNTTM       TIMESTAMP NULL,
	PRIMARY KEY (ENTRPRS_MBER_ID),
	FOREIGN KEY (GROUP_ID) REFERENCES COMTNAUTHORGROUPINFO(GROUP_ID)
		ON DELETE SET NULL
);
CREATE UNIQUE INDEX COMTNENTRPRSMBER_PK ON COMTNENTRPRSMBER (ENTRPRS_MBER_ID);
CREATE INDEX COMTNENTRPRSMBER_i01 ON COMTNENTRPRSMBER (GROUP_ID);


CREATE TABLE COMTNGNRLMBER
(
	MBER_ID               VARCHAR(20) NOT NULL,
	PASSWORD              VARCHAR(200) NOT NULL,
	PASSWORD_HINT         VARCHAR(100) NULL,
	PASSWORD_CNSR         VARCHAR(100) NULL,
	IHIDNUM               VARCHAR(200) NULL,
	MBER_NM               VARCHAR(50) NOT NULL,
	ZIP                   VARCHAR(6) NOT NULL,
	ADRES                 VARCHAR(100) NOT NULL,
	AREA_NO               VARCHAR(4) NOT NULL,
	MBER_STTUS            VARCHAR(15) NULL,
	DETAIL_ADRES          VARCHAR(100) NULL,
	END_TELNO             VARCHAR(4) NOT NULL,
	MBTLNUM               VARCHAR(20) NOT NULL,
	GROUP_ID              CHAR(20) NULL,
	MBER_FXNUM            VARCHAR(20) NULL,
	MBER_EMAIL_ADRES      VARCHAR(50) NULL,
	MIDDLE_TELNO          VARCHAR(4) NOT NULL,
	SBSCRB_DE             TIMESTAMP NULL,
	SEXDSTN_CODE          CHAR(1) NULL,
	ESNTL_ID              CHAR(20) NOT NULL,
	LOCK_AT               CHAR(1) NULL,
	LOCK_CNT              NUMERIC(3) NULL,
	LOCK_LAST_PNTTM       TIMESTAMP NULL,
	PRIMARY KEY (MBER_ID),
	FOREIGN KEY (GROUP_ID) REFERENCES COMTNAUTHORGROUPINFO(GROUP_ID)
		ON DELETE SET NULL
);
CREATE UNIQUE INDEX COMTNGNRLMBER_PK ON COMTNGNRLMBER (MBER_ID);
CREATE INDEX COMTNGNRLMBER_i01 ON COMTNGNRLMBER (GROUP_ID);


CREATE  VIEW COMVNUSERMASTER ( ESNTL_ID,USER_ID,PASSWORD,USER_NM,USER_ZIP,USER_ADRES,USER_EMAIL,GROUP_ID, USER_SE, ORGNZT_ID ) 
AS  
		SELECT ESNTL_ID, MBER_ID,PASSWORD,MBER_NM,ZIP,ADRES,MBER_EMAIL_ADRES,' ','GNR' AS USER_SE, ' ' ORGNZT_ID
		FROM COMTNGNRLMBER
		
	UNION ALL
		SELECT ESNTL_ID,EMPLYR_ID,PASSWORD,USER_NM,ZIP,HOUSE_ADRES,EMAIL_ADRES,GROUP_ID ,'USR' AS USER_SE, ORGNZT_ID
		FROM COMTNEMPLYRINFO
	UNION ALL
		SELECT ESNTL_ID,ENTRPRS_MBER_ID,ENTRPRS_MBER_PASSWORD,CMPNY_NM,ZIP,ADRES,APPLCNT_EMAIL_ADRES,' ' ,'ENT' AS USER_SE, ' ' ORGNZT_ID
		FROM COMTNENTRPRSMBER 
ORDER BY ESNTL_ID;


CREATE TABLE COMTNAUTHORINFO
(
	AUTHOR_CODE           VARCHAR(30) NOT NULL,
	AUTHOR_NM             VARCHAR(60) NOT NULL,
	AUTHOR_DC             VARCHAR(200) NULL,
	AUTHOR_CREAT_DE       TIMESTAMP NOT NULL,
	PRIMARY KEY (AUTHOR_CODE)
);
CREATE UNIQUE INDEX COMTNAUTHORINFO_PK ON COMTNAUTHORINFO (AUTHOR_CODE);


CREATE TABLE COMTNEMPLYRSCRTYESTBS
(
	SCRTY_DTRMN_TRGET_ID  VARCHAR(20) NOT NULL,
	MBER_TY_CODE          CHAR(5) NULL,
	AUTHOR_CODE           VARCHAR(30) NOT NULL,
	PRIMARY KEY (SCRTY_DTRMN_TRGET_ID)
);
CREATE UNIQUE INDEX COMTNEMPLYRSCRTYESTBS_PK ON COMTNEMPLYRSCRTYESTBS (SCRTY_DTRMN_TRGET_ID);
CREATE INDEX COMTNEMPLYRSCRTYESTBS_i04 ON COMTNEMPLYRSCRTYESTBS (AUTHOR_CODE);


CREATE TABLE COMTNROLES_HIERARCHY
(
	PARNTS_ROLE           VARCHAR(30) NOT NULL,
	CHLDRN_ROLE           VARCHAR(30) NOT NULL,
	PRIMARY KEY (PARNTS_ROLE,CHLDRN_ROLE),
	FOREIGN KEY (PARNTS_ROLE) REFERENCES COMTNAUTHORINFO(AUTHOR_CODE)
		ON DELETE CASCADE,
	FOREIGN KEY (CHLDRN_ROLE) REFERENCES COMTNAUTHORINFO(AUTHOR_CODE)
		ON DELETE CASCADE
);
CREATE UNIQUE INDEX COMTNROLES_HIERARCHY_PK ON COMTNROLES_HIERARCHY (PARNTS_ROLE, CHLDRN_ROLE);
CREATE UNIQUE INDEX COMTNROLES_HIERARCHY_i01 ON COMTNROLES_HIERARCHY (PARNTS_ROLE);
CREATE INDEX COMTNROLES_HIERARCHY_i02 ON COMTNROLES_HIERARCHY(CHLDRN_ROLE);


CREATE TABLE COMTNROLEINFO
(
	ROLE_CODE             VARCHAR(50) NOT NULL,
	ROLE_NM               VARCHAR(60) NOT NULL,
	ROLE_PTTRN            VARCHAR(300) NULL,
	ROLE_DC               VARCHAR(200) NULL,
	ROLE_TY               VARCHAR(80) NULL,
	ROLE_SORT             VARCHAR(10) NULL,
	ROLE_CREAT_DE         TIMESTAMP NOT NULL,
	PRIMARY KEY (ROLE_CODE)
);
CREATE UNIQUE INDEX COMTNROLEINFO_PK ON COMTNROLEINFO (ROLE_CODE);


CREATE TABLE COMTNAUTHORROLERELATE
(
	AUTHOR_CODE           VARCHAR(30) NOT NULL,
	ROLE_CODE             VARCHAR(50) NOT NULL,
	CREAT_DT              TIMESTAMP NULL,
	PRIMARY KEY (AUTHOR_CODE,ROLE_CODE),
	FOREIGN KEY (AUTHOR_CODE) REFERENCES COMTNAUTHORINFO(AUTHOR_CODE)
		ON DELETE CASCADE,
	FOREIGN KEY (ROLE_CODE) REFERENCES COMTNROLEINFO(ROLE_CODE)
		ON DELETE CASCADE
);
CREATE UNIQUE INDEX COMTNAUTHORROLERELATE_PK ON COMTNAUTHORROLERELATE (AUTHOR_CODE,	ROLE_CODE);
CREATE INDEX COMTNAUTHORROLERELATE_i01 ON COMTNAUTHORROLERELATE (AUTHOR_CODE);
CREATE INDEX COMTNAUTHORROLERELATE_i02 ON COMTNAUTHORROLERELATE (ROLE_CODE);


CREATE TABLE COMTNBBSMASTER
(
	BBS_ID                CHAR(20) NOT NULL,
	BBS_NM                VARCHAR(255) NOT NULL,
	BBS_INTRCN            VARCHAR(2400) NULL,
	BBS_TY_CODE           CHAR(6) NOT NULL,
	REPLY_POSBL_AT        CHAR(1) NULL,
	FILE_ATCH_POSBL_AT    CHAR(1) NOT NULL,
	ATCH_POSBL_FILE_NUMBER  NUMERIC(2) NOT NULL,
	ATCH_POSBL_FILE_SIZE  NUMERIC(8) NULL,
	USE_AT                CHAR(1) NOT NULL,
	TMPLAT_ID             CHAR(20) NULL,
	CMMNTY_ID             CHAR(20) NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	FRST_REGIST_PNTTM     TIMESTAMP NOT NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       TIMESTAMP NULL,
	BLOG_ID 					CHAR(20) NULL,
	BLOG_AT 					CHAR(2) NULL,
	PRIMARY KEY (BBS_ID)
);
CREATE UNIQUE INDEX COMTNBBSMASTER_PK ON COMTNBBSMASTER (BBS_ID);


CREATE TABLE COMTNBBSMASTEROPTN
(
	BBS_ID                CHAR(20) NOT NULL,
	ANSWER_AT             CHAR(1) NOT NULL,
	STSFDG_AT             CHAR(1) NOT NULL,
	FRST_REGIST_PNTTM     TIMESTAMP NOT NULL,
	LAST_UPDT_PNTTM       TIMESTAMP NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	PRIMARY KEY (BBS_ID)
);
CREATE UNIQUE INDEX COMTNBBSMASTEROPTN_PK ON COMTNBBSMASTEROPTN (BBS_ID);


CREATE TABLE COMTNBBSUSE
(
	BBS_ID                CHAR(20) NOT NULL,
	TRGET_ID              CHAR(20) NOT NULL,
	USE_AT                CHAR(1) NOT NULL,
	REGIST_SE_CODE        CHAR(6) NULL,
	FRST_REGIST_PNTTM     TIMESTAMP NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM       TIMESTAMP NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	PRIMARY KEY (BBS_ID,TRGET_ID),
	FOREIGN KEY (BBS_ID) REFERENCES COMTNBBSMASTER(BBS_ID)
);
CREATE UNIQUE INDEX COMTNBBSUSE_PK ON COMTNBBSUSE (BBS_ID, TRGET_ID);
CREATE INDEX COMTNBBSUSE_i01 ON COMTNBBSUSE (BBS_ID);


CREATE TABLE COMTNBBS
(
	NTT_ID                NUMERIC(20) NOT NULL,
	BBS_ID                CHAR(20) NOT NULL,
	NTT_NO                NUMERIC(20) NULL,
	NTT_SJ                VARCHAR(2000) NULL,
	NTT_CN                TEXT NULL,
	ANSWER_AT             CHAR(1) NULL,
	PARNTSCTT_NO          NUMERIC(10) NULL,
	ANSWER_LC             NUMERIC(8) NULL,
	SORT_ORDR             NUMERIC(8) NULL,
	RDCNT                 NUMERIC(10) NULL,
	USE_AT                CHAR(1) NOT NULL,
	NTCE_BGNDE            CHAR(20) NULL,
	NTCE_ENDDE            CHAR(20) NULL,
	NTCR_ID               VARCHAR(20) NULL,
	NTCR_NM               VARCHAR(20) NULL,
	PASSWORD              VARCHAR(200) NULL,
	ATCH_FILE_ID          CHAR(20) NULL,
	NOTICE_AT             CHAR(1) NULL,
	SJ_BOLD_AT            CHAR(1) NULL,
	SECRET_AT             CHAR(1) NULL,
	FRST_REGIST_PNTTM     TIMESTAMP NOT NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM       TIMESTAMP NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	BLOG_ID 					CHAR(20) NULL,
	PRIMARY KEY (NTT_ID,BBS_ID),
	FOREIGN KEY (BBS_ID) REFERENCES COMTNBBSMASTER(BBS_ID)
);
CREATE UNIQUE INDEX COMTNBBS_PK ON COMTNBBS (NTT_ID, BBS_ID);
CREATE INDEX COMTNBBS_i01 ON COMTNBBS (BBS_ID);


CREATE TABLE COMTNCOMMENT
(
	NTT_ID                NUMERIC(20) NOT NULL,
	BBS_ID                CHAR(20) NOT NULL,
	ANSWER_NO             NUMERIC(20) NOT NULL,
	WRTER_ID              VARCHAR(20) NULL,
	WRTER_NM              VARCHAR(20) NULL,
	ANSWER                VARCHAR(200) NULL,
	USE_AT                CHAR(1) NOT NULL,
	FRST_REGIST_PNTTM     TIMESTAMP NOT NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM       TIMESTAMP NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	PASSWORD              VARCHAR(200) NULL,
	PRIMARY KEY (NTT_ID,BBS_ID,ANSWER_NO),
	FOREIGN KEY (NTT_ID,BBS_ID) REFERENCES COMTNBBS(NTT_ID,BBS_ID)
);
CREATE UNIQUE INDEX COMTNCOMMENT_PK ON COMTNCOMMENT (NTT_ID, BBS_ID, ANSWER_NO);
CREATE INDEX COMTNCOMMENT_i01 ON COMTNCOMMENT (NTT_ID, BBS_ID);


CREATE TABLE COMTNSTSFDG
(
	STSFDG_NO             NUMERIC(20) NOT NULL,
	NTT_ID                NUMERIC(20) NOT NULL,
	BBS_ID                CHAR(20) NOT NULL,
	WRTER_ID              VARCHAR(20) NULL,
	WRTER_NM              VARCHAR(20) NULL,
	PASSWORD              VARCHAR(200) NULL,
	STSFDG                NUMERIC(1) NOT NULL,
	STSFDG_CN             VARCHAR(200) NULL,
	USE_AT                CHAR(1) NOT NULL,
	FRST_REGIST_PNTTM     TIMESTAMP NOT NULL,
	LAST_UPDT_PNTTM       TIMESTAMP NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	PRIMARY KEY (STSFDG_NO)
);
CREATE UNIQUE INDEX COMTNSTSFDG_PK ON COMTNSTSFDG (STSFDG_NO);


CREATE TABLE COMTNSCRAP
(
	SCRAP_ID              CHAR(20) NOT NULL,
	NTT_ID                NUMERIC(20) NOT NULL,
	BBS_ID                CHAR(20) NOT NULL,
	SCRAP_NM              VARCHAR(100) NOT NULL,
	USE_AT                CHAR(1) NOT NULL,
	FRST_REGIST_PNTTM     TIMESTAMP NOT NULL,
	LAST_UPDT_PNTTM       TIMESTAMP NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	PRIMARY KEY (SCRAP_ID)
);
CREATE UNIQUE INDEX COMTNSCRAP_PK ON COMTNSCRAP (SCRAP_ID);


CREATE TABLE COMTNCMMNTY
(
	CMMNTY_ID             CHAR(20) NOT NULL,
	CMMNTY_NM             VARCHAR(255) NOT NULL,
	CMMNTY_INTRCN         VARCHAR(2400) NULL,
	USE_AT                CHAR(1) NOT NULL,
	REGIST_SE_CODE        CHAR(6) NULL,
	TMPLAT_ID             CHAR(20) NULL,
	FRST_REGIST_PNTTM     TIMESTAMP NOT NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM       TIMESTAMP NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	PRIMARY KEY (CMMNTY_ID)
);
CREATE UNIQUE INDEX COMTNCMMNTY_PK ON COMTNCMMNTY (CMMNTY_ID);


CREATE TABLE COMTNCMMNTYUSER
(
	CMMNTY_ID             CHAR(20) NOT NULL,
	EMPLYR_ID             VARCHAR(20) NOT NULL,
	MNGR_AT               CHAR(1) NOT NULL,
	MBER_STTUS            VARCHAR(15) NULL,
	SBSCRB_DE             TIMESTAMP NULL,
	SECSN_DE              CHAR(20) NULL,
	USE_AT                CHAR(1) NULL,
	FRST_REGIST_PNTTM     TIMESTAMP NOT NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM       TIMESTAMP NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	PRIMARY KEY (CMMNTY_ID,EMPLYR_ID),
	FOREIGN KEY (CMMNTY_ID) REFERENCES COMTNCMMNTY(CMMNTY_ID)
);
CREATE UNIQUE INDEX COMTNCMMNTYUSER_PK ON COMTNCMMNTYUSER (CMMNTY_ID, EMPLYR_ID);
CREATE INDEX COMTNCMMNTYUSER_i01 ON COMTNCMMNTYUSER (CMMNTY_ID);


CREATE TABLE COMTNCLUB
(
	CLB_ID                CHAR(20) NOT NULL,
	CMMNTY_ID             CHAR(20) NOT NULL,
	CLB_NM                VARCHAR(255) NOT NULL,
	CLB_INTRCN            VARCHAR(2400) NULL,
	USE_AT                CHAR(1) NOT NULL,
	REGIST_SE_CODE        CHAR(6) NULL,
	TMPLAT_ID             CHAR(20) NULL,
	FRST_REGIST_PNTTM     TIMESTAMP NOT NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM       TIMESTAMP NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	PRIMARY KEY (CLB_ID,CMMNTY_ID)
);
CREATE UNIQUE INDEX COMTNCLUB_PK ON COMTNCLUB (CLB_ID, CMMNTY_ID);


CREATE TABLE COMTNCLUBUSER
(
	CLB_ID                CHAR(20) NOT NULL,
	CMMNTY_ID             CHAR(20) NOT NULL,
	OPRTR_AT              CHAR(1) NOT NULL,
	SBSCRB_DE             TIMESTAMP NULL,
	SECSN_DE              CHAR(20) NULL,
	USE_AT                CHAR(1) NOT NULL,
	FRST_REGIST_PNTTM     TIMESTAMP NOT NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM       TIMESTAMP NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	EMPLYR_ID             VARCHAR(20) NOT NULL,
	PRIMARY KEY (CLB_ID,CMMNTY_ID,EMPLYR_ID),
	FOREIGN KEY (CLB_ID,CMMNTY_ID) REFERENCES COMTNCLUB(CLB_ID,CMMNTY_ID)
);
CREATE UNIQUE INDEX COMTNCLUBUSER_PK ON COMTNCLUBUSER (CLB_ID, CMMNTY_ID, EMPLYR_ID);
CREATE INDEX COMTNCLUBUSER_i01 ON COMTNCLUBUSER (CLB_ID, CMMNTY_ID);


CREATE TABLE COMTHCONFMHISTORY
(
	CONFM_NO              NUMERIC(8) NOT NULL,
	CONFM_RQESTER_ID      VARCHAR(20) NOT NULL,
	CONFMER_ID            VARCHAR(20) NULL,
	CONFM_DE              CHAR(20) NULL,
	CONFM_TY_CODE         CHAR(4) NOT NULL,
	CONFM_STTUS_CODE      CHAR(4) NOT NULL,
	OPERT_TY_CODE         CHAR(4) NULL,
	OPERT_ID              VARCHAR(20) NULL,
	TRGET_JOB_TY_CODE     CHAR(3) NULL,
	TRGET_JOB_ID          CHAR(20) NULL,
	PRIMARY KEY (CONFM_NO)
);
CREATE UNIQUE INDEX COMTHCONFMHISTORY_PK ON COMTHCONFMHISTORY (CONFM_NO);


CREATE TABLE COMTNPROGRMLIST
(
	PROGRM_FILE_NM        VARCHAR(60) NOT NULL,
	PROGRM_STRE_PATH      VARCHAR(100) NOT NULL,
	PROGRM_KOREAN_NM      VARCHAR(60) NULL,
	PROGRM_DC             VARCHAR(200) NULL,
	URL                   VARCHAR(100) NOT NULL,
	 PRIMARY KEY (PROGRM_FILE_NM)
);
CREATE UNIQUE INDEX COMTNPROGRMLIST_PK ON COMTNPROGRMLIST (PROGRM_FILE_NM);


CREATE TABLE COMTHPROGRMCHANGEDTLS
(
	PROGRM_FILE_NM        VARCHAR(60) NOT NULL,
	REQUST_NO             NUMERIC(10) NOT NULL,
	RQESTER_ID            VARCHAR(20) NOT NULL,
	CHANGE_REQUST_CN      VARCHAR(1000) NULL,
	REQUST_PROCESS_CN     TEXT NULL,
	OPETR_ID              VARCHAR(20) NULL,
	PROCESS_STTUS_CODE    VARCHAR(15) NOT NULL,
	PROCESS_DE            CHAR(20) NULL,
	RQESTDE               CHAR(20) NULL,
	REQUST_SJ             VARCHAR(60) NOT NULL,
	PRIMARY KEY (PROGRM_FILE_NM,REQUST_NO),
	FOREIGN KEY (PROGRM_FILE_NM) REFERENCES COMTNPROGRMLIST(PROGRM_FILE_NM)
		ON DELETE CASCADE
);
CREATE UNIQUE INDEX COMTHPROGRMCHANGEDTLS_PK ON COMTHPROGRMCHANGEDTLS (PROGRM_FILE_NM, REQUST_NO);
CREATE INDEX COMTHPROGRMCHANGEDTLS_i01 ON COMTHPROGRMCHANGEDTLS (PROGRM_FILE_NM);


