ALTER TABLE COMTECOPSEQ COMMENT = 'COMTECOPSEQ';
ALTER TABLE `COMTECOPSEQ` CHANGE `NEXT_ID` `NEXT_ID` decimal(30,0) DEFAULT NULL  COMMENT '다음아이디' ;
ALTER TABLE `COMTECOPSEQ` CHANGE `TABLE_NAME` `TABLE_NAME` varchar(20) NOT NULL DEFAULT ''  COMMENT '테이블명' ;


ALTER TABLE COMTNFILE COMMENT = '파일속성';
ALTER TABLE `COMTNFILE` CHANGE `ATCH_FILE_ID` `ATCH_FILE_ID` char(20) NOT NULL  COMMENT '첨부파일ID' ;
ALTER TABLE `COMTNFILE` CHANGE `CREAT_DT` `CREAT_DT` datetime NOT NULL  COMMENT '생성일시' ;
ALTER TABLE `COMTNFILE` CHANGE `USE_AT` `USE_AT` char(1) DEFAULT NULL  COMMENT '사용여부' ;


ALTER TABLE COMTNFILEDETAIL COMMENT = '파일상세정보';
ALTER TABLE `COMTNFILEDETAIL` CHANGE `ATCH_FILE_ID` `ATCH_FILE_ID` char(20) NOT NULL  COMMENT '첨부파일ID' ;
ALTER TABLE `COMTNFILEDETAIL` CHANGE `FILE_CN` `FILE_CN` mediumtext DEFAULT NULL  COMMENT '파일내용' ;
ALTER TABLE `COMTNFILEDETAIL` CHANGE `FILE_EXTSN` `FILE_EXTSN` varchar(20) NOT NULL  COMMENT '파일확장자' ;
ALTER TABLE `COMTNFILEDETAIL` CHANGE `FILE_SIZE` `FILE_SIZE` decimal(8,0) DEFAULT NULL  COMMENT '파일크기' ;
ALTER TABLE `COMTNFILEDETAIL` CHANGE `FILE_SN` `FILE_SN` decimal(10,0) NOT NULL  COMMENT '파일순번' ;
ALTER TABLE `COMTNFILEDETAIL` CHANGE `FILE_STRE_COURS` `FILE_STRE_COURS` varchar(2000) NOT NULL  COMMENT '파일저장경로' ;
ALTER TABLE `COMTNFILEDETAIL` CHANGE `ORIGNL_FILE_NM` `ORIGNL_FILE_NM` varchar(255) DEFAULT NULL  COMMENT '원파일명' ;
ALTER TABLE `COMTNFILEDETAIL` CHANGE `STRE_FILE_NM` `STRE_FILE_NM` varchar(255) NOT NULL  COMMENT '저장파일명' ;


ALTER TABLE COMTNLOGINPOLICY COMMENT = '로그인정책';
ALTER TABLE `COMTNLOGINPOLICY` CHANGE `DPLCT_PERM_AT` `DPLCT_PERM_AT` char(1) NOT NULL  COMMENT '중복허용여부' ;
ALTER TABLE `COMTNLOGINPOLICY` CHANGE `EMPLYR_ID` `EMPLYR_ID` varchar(20) NOT NULL DEFAULT ''  COMMENT '업무사용자ID' ;
ALTER TABLE `COMTNLOGINPOLICY` CHANGE `FRST_REGIST_PNTTM` `FRST_REGIST_PNTTM` datetime DEFAULT NULL  COMMENT '최초등록시점' ;
ALTER TABLE `COMTNLOGINPOLICY` CHANGE `FRST_REGISTER_ID` `FRST_REGISTER_ID` varchar(20) DEFAULT NULL  COMMENT '최초등록자ID' ;
ALTER TABLE `COMTNLOGINPOLICY` CHANGE `IP_INFO` `IP_INFO` varchar(23) NOT NULL  COMMENT 'IP정보' ;
ALTER TABLE `COMTNLOGINPOLICY` CHANGE `LAST_UPDT_PNTTM` `LAST_UPDT_PNTTM` datetime DEFAULT NULL  COMMENT '최종수정시점' ;
ALTER TABLE `COMTNLOGINPOLICY` CHANGE `LAST_UPDUSR_ID` `LAST_UPDUSR_ID` varchar(20) DEFAULT NULL  COMMENT '최종수정자ID' ;
ALTER TABLE `COMTNLOGINPOLICY` CHANGE `LMTT_AT` `LMTT_AT` char(1) NOT NULL  COMMENT '제한여부' ;


ALTER TABLE COMTNORGNZTINFO COMMENT = '조직정보';
ALTER TABLE `COMTNORGNZTINFO` CHANGE `ORGNZT_DC` `ORGNZT_DC` varchar(100) DEFAULT NULL  COMMENT '조직설명' ;
ALTER TABLE `COMTNORGNZTINFO` CHANGE `ORGNZT_ID` `ORGNZT_ID` char(20) NOT NULL DEFAULT ''  COMMENT '조직ID' ;
ALTER TABLE `COMTNORGNZTINFO` CHANGE `ORGNZT_NM` `ORGNZT_NM` varchar(20) NOT NULL  COMMENT '조직명' ;


ALTER TABLE COMTNAUTHORGROUPINFO COMMENT = '권한그룹정보';
ALTER TABLE `COMTNAUTHORGROUPINFO` CHANGE `GROUP_CREAT_DE` `GROUP_CREAT_DE` char(20) NOT NULL  COMMENT '그룹생성일' ;
ALTER TABLE `COMTNAUTHORGROUPINFO` CHANGE `GROUP_DC` `GROUP_DC` varchar(100) DEFAULT NULL  COMMENT '그룹설명' ;
ALTER TABLE `COMTNAUTHORGROUPINFO` CHANGE `GROUP_ID` `GROUP_ID` char(20) NOT NULL DEFAULT ''  COMMENT '그룹ID' ;
ALTER TABLE `COMTNAUTHORGROUPINFO` CHANGE `GROUP_NM` `GROUP_NM` varchar(60) NOT NULL  COMMENT '그룹명' ;


ALTER TABLE COMTNEMPLYRINFO COMMENT = '업무사용자정보';
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `AREA_NO` `AREA_NO` varchar(4) NOT NULL  COMMENT '지역번호' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `BRTHDY` `BRTHDY` char(20) DEFAULT NULL  COMMENT '생일' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `CRTFC_DN_VALUE` `CRTFC_DN_VALUE` varchar(100) DEFAULT NULL  COMMENT '인증DN값' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `DETAIL_ADRES` `DETAIL_ADRES` varchar(100) DEFAULT NULL  COMMENT '상세주소' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `EMAIL_ADRES` `EMAIL_ADRES` varchar(50) DEFAULT NULL  COMMENT '이메일주소' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `EMPL_NO` `EMPL_NO` varchar(20) DEFAULT NULL  COMMENT '사원번호' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `EMPLYR_ID` `EMPLYR_ID` varchar(20) NOT NULL  COMMENT '업무사용자ID' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `EMPLYR_STTUS_CODE` `EMPLYR_STTUS_CODE` char(1) NOT NULL  COMMENT '사용자상태코드' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `ESNTL_ID` `ESNTL_ID` char(20) NOT NULL  COMMENT '고유ID' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `FXNUM` `FXNUM` varchar(20) DEFAULT NULL  COMMENT '팩스번호' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `GROUP_ID` `GROUP_ID` char(20)  COMMENT '그룹ID' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `HOUSE_ADRES` `HOUSE_ADRES` varchar(100) NOT NULL  COMMENT '주택주소' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `HOUSE_END_TELNO` `HOUSE_END_TELNO` varchar(4) NOT NULL  COMMENT '주택끝전화번호' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `HOUSE_MIDDLE_TELNO` `HOUSE_MIDDLE_TELNO` varchar(4) NOT NULL  COMMENT '주택중간전화번호' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `IHIDNUM` `IHIDNUM` varchar(200) DEFAULT NULL  COMMENT '주민등록번호' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `MBTLNUM` `MBTLNUM` varchar(20) DEFAULT NULL  COMMENT '이동전화번호' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `OFCPS_NM` `OFCPS_NM` varchar(60) DEFAULT NULL  COMMENT '직위명' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `OFFM_TELNO` `OFFM_TELNO` varchar(20) DEFAULT NULL  COMMENT '사무실전화번호' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `ORGNZT_ID` `ORGNZT_ID` char(20)  COMMENT '조직ID' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `PASSWORD_CNSR` `PASSWORD_CNSR` varchar(100) NOT NULL  COMMENT '비밀번호정답' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `PASSWORD_HINT` `PASSWORD_HINT` varchar(100) NOT NULL  COMMENT '비밀번호힌트' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `PASSWORD` `PASSWORD` varchar(200) NOT NULL  COMMENT '비밀번호' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `PSTINST_CODE` `PSTINST_CODE` char(8) DEFAULT NULL  COMMENT '소속기관코드' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `SBSCRB_DE` `SBSCRB_DE` datetime DEFAULT NULL  COMMENT '가입일자' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `SEXDSTN_CODE` `SEXDSTN_CODE` char(1) DEFAULT NULL  COMMENT '성별코드' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `USER_NM` `USER_NM` varchar(60) NOT NULL  COMMENT '사용자명' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `ZIP` `ZIP` varchar(6) NOT NULL  COMMENT '우편번호' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `LOCK_AT` `LOCK_AT` char(1) NULL COMMENT '잠금여부' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `LOCK_CNT` `LOCK_CNT` numeric(3) NULL COMMENT '잠금회수' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `LOCK_LAST_PNTTM` `LOCK_LAST_PNTTM` datetime NULL COMMENT '잠금최종시점' ;


ALTER TABLE COMTHEMPLYRINFOCHANGEDTLS COMMENT = '업무사용자정보변경내역';
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `AREA_NO` `AREA_NO` varchar(4) DEFAULT NULL  COMMENT '지역번호' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `BRTHDY` `BRTHDY` char(20) DEFAULT NULL  COMMENT '생일' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `CHANGE_DE` `CHANGE_DE` char(20) NOT NULL DEFAULT ''  COMMENT '변경일' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `DETAIL_ADRES` `DETAIL_ADRES` varchar(100) DEFAULT NULL  COMMENT '상세주소' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `EMAIL_ADRES` `EMAIL_ADRES` varchar(50) DEFAULT NULL  COMMENT '이메일주소' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `EMPL_NO` `EMPL_NO` varchar(20) DEFAULT NULL  COMMENT '사원번호' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `EMPLYR_ID` `EMPLYR_ID` varchar(20) NOT NULL  COMMENT '업무사용자ID' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `EMPLYR_STTUS_CODE` `EMPLYR_STTUS_CODE` char(1) DEFAULT NULL  COMMENT '사용자상태코드' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `ESNTL_ID` `ESNTL_ID` char(20) DEFAULT NULL  COMMENT '고유ID' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `FXNUM` `FXNUM` varchar(20) DEFAULT NULL  COMMENT '팩스번호' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `GROUP_ID` `GROUP_ID` char(20) DEFAULT NULL  COMMENT '그룹ID' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `HOUSE_ADRES` `HOUSE_ADRES` varchar(100) DEFAULT NULL  COMMENT '주택주소' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `HOUSE_END_TELNO` `HOUSE_END_TELNO` varchar(4) DEFAULT NULL  COMMENT '주택끝전화번호' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `HOUSE_MIDDLE_TELNO` `HOUSE_MIDDLE_TELNO` varchar(4) DEFAULT NULL  COMMENT '주택중간전화번호' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `MBTLNUM` `MBTLNUM` varchar(20) DEFAULT NULL  COMMENT '이동전화번호' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `OFFM_TELNO` `OFFM_TELNO` varchar(20) DEFAULT NULL  COMMENT '사무실전화번호' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `ORGNZT_ID` `ORGNZT_ID` char(20) DEFAULT NULL  COMMENT '조직ID' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `PSTINST_CODE` `PSTINST_CODE` char(8) DEFAULT NULL  COMMENT '소속기관코드' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `SEXDSTN_CODE` `SEXDSTN_CODE` char(1) DEFAULT NULL  COMMENT '성별코드' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `ZIP` `ZIP` varchar(6) DEFAULT NULL  COMMENT '우편번호' ;


ALTER TABLE COMTNENTRPRSMBER COMMENT = '기업회원';
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `ADRES` `ADRES` varchar(100) NOT NULL  COMMENT '주소' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `APPLCNT_EMAIL_ADRES` `APPLCNT_EMAIL_ADRES` varchar(50) NOT NULL  COMMENT '신청자이메일주소' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `APPLCNT_IHIDNUM` `APPLCNT_IHIDNUM` varchar(200) DEFAULT NULL  COMMENT '신청인주민등록번호' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `APPLCNT_NM` `APPLCNT_NM` varchar(50) NOT NULL  COMMENT '신청인명' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `AREA_NO` `AREA_NO` varchar(4) NOT NULL  COMMENT '지역번호' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `BIZRNO` `BIZRNO` varchar(10) DEFAULT NULL  COMMENT '사업자등록번호' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `CMPNY_NM` `CMPNY_NM` varchar(60) NOT NULL  COMMENT '회사명' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `CXFC` `CXFC` varchar(50) DEFAULT NULL  COMMENT '대표이사' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `DETAIL_ADRES` `DETAIL_ADRES` varchar(100) DEFAULT NULL  COMMENT '상세주소' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `ENTRPRS_END_TELNO` `ENTRPRS_END_TELNO` varchar(4) NOT NULL  COMMENT '기업끝전화번호' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `ENTRPRS_MBER_ID` `ENTRPRS_MBER_ID` varchar(20) NOT NULL DEFAULT ''  COMMENT '기업회원ID' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `ENTRPRS_MBER_PASSWORD_CNSR` `ENTRPRS_MBER_PASSWORD_CNSR` varchar(100) NOT NULL  COMMENT '기업회원비밀번호정답' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `ENTRPRS_MBER_PASSWORD_HINT` `ENTRPRS_MBER_PASSWORD_HINT` varchar(100) NOT NULL  COMMENT '기업회원비밀번호힌트' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `ENTRPRS_MBER_PASSWORD` `ENTRPRS_MBER_PASSWORD` varchar(200) DEFAULT NULL  COMMENT '기업회원비밀번호' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `ENTRPRS_MBER_STTUS` `ENTRPRS_MBER_STTUS` varchar(15) DEFAULT NULL  COMMENT '기업회원상태' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `ENTRPRS_MIDDLE_TELNO` `ENTRPRS_MIDDLE_TELNO` varchar(4) NOT NULL  COMMENT '기업중간전화번호' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `ENTRPRS_SE_CODE` `ENTRPRS_SE_CODE` char(8) DEFAULT NULL  COMMENT '기업구분코드' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `ESNTL_ID` `ESNTL_ID` char(20) NOT NULL  COMMENT '고유ID' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `FXNUM` `FXNUM` varchar(20) DEFAULT NULL  COMMENT '팩스번호' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `GROUP_ID` `GROUP_ID` char(20)  COMMENT '그룹ID' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `INDUTY_CODE` `INDUTY_CODE` char(1) DEFAULT NULL  COMMENT '업종코드' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `JURIRNO` `JURIRNO` varchar(13) DEFAULT NULL  COMMENT '법인등록번호' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `SBSCRB_DE` `SBSCRB_DE` datetime DEFAULT NULL  COMMENT '가입일자' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `ZIP` `ZIP` varchar(6) NOT NULL  COMMENT '우편번호' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `LOCK_AT` `LOCK_AT` char(1) NULL COMMENT '잠금여부' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `LOCK_CNT` `LOCK_CNT` numeric(3) NULL COMMENT '잠금회수' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `LOCK_LAST_PNTTM` `LOCK_LAST_PNTTM` datetime NULL COMMENT '잠금최종시점' ;


ALTER TABLE COMTNGNRLMBER COMMENT = '일반회원';
ALTER TABLE `COMTNGNRLMBER` CHANGE `ADRES` `ADRES` varchar(100) NOT NULL  COMMENT '주소' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `AREA_NO` `AREA_NO` varchar(4) NOT NULL  COMMENT '지역번호' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `DETAIL_ADRES` `DETAIL_ADRES` varchar(100) DEFAULT NULL  COMMENT '상세주소' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `END_TELNO` `END_TELNO` varchar(4) NOT NULL  COMMENT '끝전화번호' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `ESNTL_ID` `ESNTL_ID` char(20) NOT NULL  COMMENT '고유ID' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `GROUP_ID` `GROUP_ID` char(20)  COMMENT '그룹ID' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `IHIDNUM` `IHIDNUM` varchar(200) DEFAULT NULL  COMMENT '주민등록번호' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `MBER_EMAIL_ADRES` `MBER_EMAIL_ADRES` varchar(50) DEFAULT NULL  COMMENT '회원이메일주소' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `MBER_FXNUM` `MBER_FXNUM` varchar(20) DEFAULT NULL  COMMENT '회원팩스번호' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `MBER_ID` `MBER_ID` varchar(20) NOT NULL DEFAULT ''  COMMENT '회원ID' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `MBER_NM` `MBER_NM` varchar(50) NOT NULL  COMMENT '회원명' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `MBER_STTUS` `MBER_STTUS` varchar(15) DEFAULT NULL  COMMENT '회원상태' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `MBTLNUM` `MBTLNUM` varchar(20) NOT NULL  COMMENT '이동전화번호' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `MIDDLE_TELNO` `MIDDLE_TELNO` varchar(4) NOT NULL  COMMENT '중간전화번호' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `PASSWORD_CNSR` `PASSWORD_CNSR` varchar(100) DEFAULT NULL  COMMENT '비밀번호정답' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `PASSWORD_HINT` `PASSWORD_HINT` varchar(100) DEFAULT NULL  COMMENT '비밀번호힌트' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `PASSWORD` `PASSWORD` varchar(200) NOT NULL  COMMENT '비밀번호' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `SBSCRB_DE` `SBSCRB_DE` datetime DEFAULT NULL  COMMENT '가입일자' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `SEXDSTN_CODE` `SEXDSTN_CODE` char(1) DEFAULT NULL  COMMENT '성별코드' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `ZIP` `ZIP` varchar(6) NOT NULL  COMMENT '우편번호' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `LOCK_AT` `LOCK_AT` char(1) NULL COMMENT '잠금여부' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `LOCK_CNT` `LOCK_CNT` numeric(3) NULL COMMENT '잠금회수' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `LOCK_LAST_PNTTM` `LOCK_LAST_PNTTM` datetime NULL COMMENT '잠금최종시점' ;
ALTER TABLE `COMTNHPCMINFO` CHANGE `FRST_REGIST_PNTTM` `FRST_REGIST_PNTTM` datetime DEFAULT NULL  COMMENT '최초등록시점' ;
ALTER TABLE `COMTNHPCMINFO` CHANGE `FRST_REGISTER_ID` `FRST_REGISTER_ID` varchar(20) DEFAULT NULL  COMMENT '최초등록자ID' ;
ALTER TABLE `COMTNHPCMINFO` CHANGE `HPCM_DC` `HPCM_DC` varchar(2500) DEFAULT NULL  COMMENT '도움말설명' ;
ALTER TABLE `COMTNHPCMINFO` CHANGE `HPCM_DFN` `HPCM_DFN` varchar(1000) DEFAULT NULL  COMMENT '도움말정의' ;
ALTER TABLE `COMTNHPCMINFO` CHANGE `HPCM_ID` `HPCM_ID` char(20) NOT NULL  COMMENT '도움말ID' ;
ALTER TABLE `COMTNHPCMINFO` CHANGE `HPCM_SE_CODE` `HPCM_SE_CODE` char(1) DEFAULT NULL  COMMENT '도움말구분코드' ;
ALTER TABLE `COMTNHPCMINFO` CHANGE `LAST_UPDT_PNTTM` `LAST_UPDT_PNTTM` datetime DEFAULT NULL  COMMENT '최종수정시점' ;
ALTER TABLE `COMTNHPCMINFO` CHANGE `LAST_UPDUSR_ID` `LAST_UPDUSR_ID` varchar(20) DEFAULT NULL  COMMENT '최종수정자ID' ;


