ALTER TABLE COMTECOPSEQ COMMENT = 'COMTECOPSEQ';
ALTER TABLE `COMTECOPSEQ` CHANGE `NEXT_ID` `NEXT_ID` decimal(30,0) DEFAULT NULL  COMMENT '다음아이디' ;
ALTER TABLE `COMTECOPSEQ` CHANGE `TABLE_NAME` `TABLE_NAME` varchar(20) NOT NULL DEFAULT ''  COMMENT '테이블명' ;


ALTER TABLE COMTNFILE COMMENT = '파일속성';
ALTER TABLE `COMTNFILE` CHANGE `ATCH_FILE_ID` `ATCH_FILE_ID` char(20) NOT NULL  COMMENT '첨부파일ID' ;
ALTER TABLE `COMTNFILE` CHANGE `CREAT_DT` `CREAT_DT` datetime NOT NULL  COMMENT '생성일시' ;
ALTER TABLE `COMTNFILE` CHANGE `USE_AT` `USE_AT` char(1) DEFAULT NULL  COMMENT '사용여부' ;


ALTER TABLE COMTNFILEDETAIL COMMENT = '파일상세정보';
ALTER TABLE `COMTNFILEDETAIL` CHANGE `ATCH_FILE_ID` `ATCH_FILE_ID` char(20) NOT NULL  COMMENT '첨부파일ID' ;
ALTER TABLE `COMTNFILEDETAIL` CHANGE `FILE_CN` `FILE_CN` mediumtext DEFAULT NULL  COMMENT '파일내용' ;
ALTER TABLE `COMTNFILEDETAIL` CHANGE `FILE_EXTSN` `FILE_EXTSN` varchar(20) NOT NULL  COMMENT '파일확장자' ;
ALTER TABLE `COMTNFILEDETAIL` CHANGE `FILE_SIZE` `FILE_SIZE` decimal(8,0) DEFAULT NULL  COMMENT '파일크기' ;
ALTER TABLE `COMTNFILEDETAIL` CHANGE `FILE_SN` `FILE_SN` decimal(10,0) NOT NULL  COMMENT '파일순번' ;
ALTER TABLE `COMTNFILEDETAIL` CHANGE `FILE_STRE_COURS` `FILE_STRE_COURS` varchar(2000) NOT NULL  COMMENT '파일저장경로' ;
ALTER TABLE `COMTNFILEDETAIL` CHANGE `ORIGNL_FILE_NM` `ORIGNL_FILE_NM` varchar(255) DEFAULT NULL  COMMENT '원파일명' ;
ALTER TABLE `COMTNFILEDETAIL` CHANGE `STRE_FILE_NM` `STRE_FILE_NM` varchar(255) NOT NULL  COMMENT '저장파일명' ;


ALTER TABLE COMTNLOGINPOLICY COMMENT = '로그인정책';
ALTER TABLE `COMTNLOGINPOLICY` CHANGE `DPLCT_PERM_AT` `DPLCT_PERM_AT` char(1) NOT NULL  COMMENT '중복허용여부' ;
ALTER TABLE `COMTNLOGINPOLICY` CHANGE `EMPLYR_ID` `EMPLYR_ID` varchar(20) NOT NULL DEFAULT ''  COMMENT '업무사용자ID' ;
ALTER TABLE `COMTNLOGINPOLICY` CHANGE `FRST_REGIST_PNTTM` `FRST_REGIST_PNTTM` datetime DEFAULT NULL  COMMENT '최초등록시점' ;
ALTER TABLE `COMTNLOGINPOLICY` CHANGE `FRST_REGISTER_ID` `FRST_REGISTER_ID` varchar(20) DEFAULT NULL  COMMENT '최초등록자ID' ;
ALTER TABLE `COMTNLOGINPOLICY` CHANGE `IP_INFO` `IP_INFO` varchar(23) NOT NULL  COMMENT 'IP정보' ;
ALTER TABLE `COMTNLOGINPOLICY` CHANGE `LAST_UPDT_PNTTM` `LAST_UPDT_PNTTM` datetime DEFAULT NULL  COMMENT '최종수정시점' ;
ALTER TABLE `COMTNLOGINPOLICY` CHANGE `LAST_UPDUSR_ID` `LAST_UPDUSR_ID` varchar(20) DEFAULT NULL  COMMENT '최종수정자ID' ;
ALTER TABLE `COMTNLOGINPOLICY` CHANGE `LMTT_AT` `LMTT_AT` char(1) NOT NULL  COMMENT '제한여부' ;


ALTER TABLE COMTNORGNZTINFO COMMENT = '조직정보';
ALTER TABLE `COMTNORGNZTINFO` CHANGE `ORGNZT_DC` `ORGNZT_DC` varchar(100) DEFAULT NULL  COMMENT '조직설명' ;
ALTER TABLE `COMTNORGNZTINFO` CHANGE `ORGNZT_ID` `ORGNZT_ID` char(20) NOT NULL DEFAULT ''  COMMENT '조직ID' ;
ALTER TABLE `COMTNORGNZTINFO` CHANGE `ORGNZT_NM` `ORGNZT_NM` varchar(20) NOT NULL  COMMENT '조직명' ;


ALTER TABLE COMTNAUTHORGROUPINFO COMMENT = '권한그룹정보';
ALTER TABLE `COMTNAUTHORGROUPINFO` CHANGE `GROUP_CREAT_DE` `GROUP_CREAT_DE` char(20) NOT NULL  COMMENT '그룹생성일' ;
ALTER TABLE `COMTNAUTHORGROUPINFO` CHANGE `GROUP_DC` `GROUP_DC` varchar(100) DEFAULT NULL  COMMENT '그룹설명' ;
ALTER TABLE `COMTNAUTHORGROUPINFO` CHANGE `GROUP_ID` `GROUP_ID` char(20) NOT NULL DEFAULT ''  COMMENT '그룹ID' ;
ALTER TABLE `COMTNAUTHORGROUPINFO` CHANGE `GROUP_NM` `GROUP_NM` varchar(60) NOT NULL  COMMENT '그룹명' ;


ALTER TABLE COMTNEMPLYRINFO COMMENT = '업무사용자정보';
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `AREA_NO` `AREA_NO` varchar(4) NOT NULL  COMMENT '지역번호' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `BRTHDY` `BRTHDY` char(20) DEFAULT NULL  COMMENT '생일' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `CRTFC_DN_VALUE` `CRTFC_DN_VALUE` varchar(100) DEFAULT NULL  COMMENT '인증DN값' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `DETAIL_ADRES` `DETAIL_ADRES` varchar(100) DEFAULT NULL  COMMENT '상세주소' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `EMAIL_ADRES` `EMAIL_ADRES` varchar(50) DEFAULT NULL  COMMENT '이메일주소' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `EMPL_NO` `EMPL_NO` varchar(20) DEFAULT NULL  COMMENT '사원번호' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `EMPLYR_ID` `EMPLYR_ID` varchar(20) NOT NULL  COMMENT '업무사용자ID' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `EMPLYR_STTUS_CODE` `EMPLYR_STTUS_CODE` char(1) NOT NULL  COMMENT '사용자상태코드' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `ESNTL_ID` `ESNTL_ID` char(20) NOT NULL  COMMENT '고유ID' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `FXNUM` `FXNUM` varchar(20) DEFAULT NULL  COMMENT '팩스번호' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `GROUP_ID` `GROUP_ID` char(20)  COMMENT '그룹ID' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `HOUSE_ADRES` `HOUSE_ADRES` varchar(100) NOT NULL  COMMENT '주택주소' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `HOUSE_END_TELNO` `HOUSE_END_TELNO` varchar(4) NOT NULL  COMMENT '주택끝전화번호' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `HOUSE_MIDDLE_TELNO` `HOUSE_MIDDLE_TELNO` varchar(4) NOT NULL  COMMENT '주택중간전화번호' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `IHIDNUM` `IHIDNUM` varchar(200) DEFAULT NULL  COMMENT '주민등록번호' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `MBTLNUM` `MBTLNUM` varchar(20) DEFAULT NULL  COMMENT '이동전화번호' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `OFCPS_NM` `OFCPS_NM` varchar(60) DEFAULT NULL  COMMENT '직위명' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `OFFM_TELNO` `OFFM_TELNO` varchar(20) DEFAULT NULL  COMMENT '사무실전화번호' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `ORGNZT_ID` `ORGNZT_ID` char(20)  COMMENT '조직ID' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `PASSWORD_CNSR` `PASSWORD_CNSR` varchar(100) NOT NULL  COMMENT '비밀번호정답' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `PASSWORD_HINT` `PASSWORD_HINT` varchar(100) NOT NULL  COMMENT '비밀번호힌트' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `PASSWORD` `PASSWORD` varchar(200) NOT NULL  COMMENT '비밀번호' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `PSTINST_CODE` `PSTINST_CODE` char(8) DEFAULT NULL  COMMENT '소속기관코드' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `SBSCRB_DE` `SBSCRB_DE` datetime DEFAULT NULL  COMMENT '가입일자' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `SEXDSTN_CODE` `SEXDSTN_CODE` char(1) DEFAULT NULL  COMMENT '성별코드' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `USER_NM` `USER_NM` varchar(60) NOT NULL  COMMENT '사용자명' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `ZIP` `ZIP` varchar(6) NOT NULL  COMMENT '우편번호' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `LOCK_AT` `LOCK_AT` char(1) NULL COMMENT '잠금여부' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `LOCK_CNT` `LOCK_CNT` numeric(3) NULL COMMENT '잠금회수' ;
ALTER TABLE `COMTNEMPLYRINFO` CHANGE `LOCK_LAST_PNTTM` `LOCK_LAST_PNTTM` datetime NULL COMMENT '잠금최종시점' ;


ALTER TABLE COMTHEMPLYRINFOCHANGEDTLS COMMENT = '업무사용자정보변경내역';
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `AREA_NO` `AREA_NO` varchar(4) DEFAULT NULL  COMMENT '지역번호' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `BRTHDY` `BRTHDY` char(20) DEFAULT NULL  COMMENT '생일' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `CHANGE_DE` `CHANGE_DE` char(20) NOT NULL DEFAULT ''  COMMENT '변경일' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `DETAIL_ADRES` `DETAIL_ADRES` varchar(100) DEFAULT NULL  COMMENT '상세주소' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `EMAIL_ADRES` `EMAIL_ADRES` varchar(50) DEFAULT NULL  COMMENT '이메일주소' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `EMPL_NO` `EMPL_NO` varchar(20) DEFAULT NULL  COMMENT '사원번호' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `EMPLYR_ID` `EMPLYR_ID` varchar(20) NOT NULL  COMMENT '업무사용자ID' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `EMPLYR_STTUS_CODE` `EMPLYR_STTUS_CODE` char(1) DEFAULT NULL  COMMENT '사용자상태코드' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `ESNTL_ID` `ESNTL_ID` char(20) DEFAULT NULL  COMMENT '고유ID' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `FXNUM` `FXNUM` varchar(20) DEFAULT NULL  COMMENT '팩스번호' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `GROUP_ID` `GROUP_ID` char(20) DEFAULT NULL  COMMENT '그룹ID' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `HOUSE_ADRES` `HOUSE_ADRES` varchar(100) DEFAULT NULL  COMMENT '주택주소' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `HOUSE_END_TELNO` `HOUSE_END_TELNO` varchar(4) DEFAULT NULL  COMMENT '주택끝전화번호' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `HOUSE_MIDDLE_TELNO` `HOUSE_MIDDLE_TELNO` varchar(4) DEFAULT NULL  COMMENT '주택중간전화번호' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `MBTLNUM` `MBTLNUM` varchar(20) DEFAULT NULL  COMMENT '이동전화번호' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `OFFM_TELNO` `OFFM_TELNO` varchar(20) DEFAULT NULL  COMMENT '사무실전화번호' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `ORGNZT_ID` `ORGNZT_ID` char(20) DEFAULT NULL  COMMENT '조직ID' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `PSTINST_CODE` `PSTINST_CODE` char(8) DEFAULT NULL  COMMENT '소속기관코드' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `SEXDSTN_CODE` `SEXDSTN_CODE` char(1) DEFAULT NULL  COMMENT '성별코드' ;
ALTER TABLE `COMTHEMPLYRINFOCHANGEDTLS` CHANGE `ZIP` `ZIP` varchar(6) DEFAULT NULL  COMMENT '우편번호' ;


ALTER TABLE COMTNENTRPRSMBER COMMENT = '기업회원';
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `ADRES` `ADRES` varchar(100) NOT NULL  COMMENT '주소' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `APPLCNT_EMAIL_ADRES` `APPLCNT_EMAIL_ADRES` varchar(50) NOT NULL  COMMENT '신청자이메일주소' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `APPLCNT_IHIDNUM` `APPLCNT_IHIDNUM` varchar(200) DEFAULT NULL  COMMENT '신청인주민등록번호' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `APPLCNT_NM` `APPLCNT_NM` varchar(50) NOT NULL  COMMENT '신청인명' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `AREA_NO` `AREA_NO` varchar(4) NOT NULL  COMMENT '지역번호' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `BIZRNO` `BIZRNO` varchar(10) DEFAULT NULL  COMMENT '사업자등록번호' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `CMPNY_NM` `CMPNY_NM` varchar(60) NOT NULL  COMMENT '회사명' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `CXFC` `CXFC` varchar(50) DEFAULT NULL  COMMENT '대표이사' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `DETAIL_ADRES` `DETAIL_ADRES` varchar(100) DEFAULT NULL  COMMENT '상세주소' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `ENTRPRS_END_TELNO` `ENTRPRS_END_TELNO` varchar(4) NOT NULL  COMMENT '기업끝전화번호' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `ENTRPRS_MBER_ID` `ENTRPRS_MBER_ID` varchar(20) NOT NULL DEFAULT ''  COMMENT '기업회원ID' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `ENTRPRS_MBER_PASSWORD_CNSR` `ENTRPRS_MBER_PASSWORD_CNSR` varchar(100) NOT NULL  COMMENT '기업회원비밀번호정답' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `ENTRPRS_MBER_PASSWORD_HINT` `ENTRPRS_MBER_PASSWORD_HINT` varchar(100) NOT NULL  COMMENT '기업회원비밀번호힌트' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `ENTRPRS_MBER_PASSWORD` `ENTRPRS_MBER_PASSWORD` varchar(200) DEFAULT NULL  COMMENT '기업회원비밀번호' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `ENTRPRS_MBER_STTUS` `ENTRPRS_MBER_STTUS` varchar(15) DEFAULT NULL  COMMENT '기업회원상태' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `ENTRPRS_MIDDLE_TELNO` `ENTRPRS_MIDDLE_TELNO` varchar(4) NOT NULL  COMMENT '기업중간전화번호' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `ENTRPRS_SE_CODE` `ENTRPRS_SE_CODE` char(8) DEFAULT NULL  COMMENT '기업구분코드' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `ESNTL_ID` `ESNTL_ID` char(20) NOT NULL  COMMENT '고유ID' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `FXNUM` `FXNUM` varchar(20) DEFAULT NULL  COMMENT '팩스번호' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `GROUP_ID` `GROUP_ID` char(20)  COMMENT '그룹ID' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `INDUTY_CODE` `INDUTY_CODE` char(1) DEFAULT NULL  COMMENT '업종코드' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `JURIRNO` `JURIRNO` varchar(13) DEFAULT NULL  COMMENT '법인등록번호' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `SBSCRB_DE` `SBSCRB_DE` datetime DEFAULT NULL  COMMENT '가입일자' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `ZIP` `ZIP` varchar(6) NOT NULL  COMMENT '우편번호' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `LOCK_AT` `LOCK_AT` char(1) NULL COMMENT '잠금여부' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `LOCK_CNT` `LOCK_CNT` numeric(3) NULL COMMENT '잠금회수' ;
ALTER TABLE `COMTNENTRPRSMBER` CHANGE `LOCK_LAST_PNTTM` `LOCK_LAST_PNTTM` datetime NULL COMMENT '잠금최종시점' ;


ALTER TABLE COMTNGNRLMBER COMMENT = '일반회원';
ALTER TABLE `COMTNGNRLMBER` CHANGE `ADRES` `ADRES` varchar(100) NOT NULL  COMMENT '주소' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `AREA_NO` `AREA_NO` varchar(4) NOT NULL  COMMENT '지역번호' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `DETAIL_ADRES` `DETAIL_ADRES` varchar(100) DEFAULT NULL  COMMENT '상세주소' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `END_TELNO` `END_TELNO` varchar(4) NOT NULL  COMMENT '끝전화번호' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `ESNTL_ID` `ESNTL_ID` char(20) NOT NULL  COMMENT '고유ID' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `GROUP_ID` `GROUP_ID` char(20)  COMMENT '그룹ID' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `IHIDNUM` `IHIDNUM` varchar(200) DEFAULT NULL  COMMENT '주민등록번호' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `MBER_EMAIL_ADRES` `MBER_EMAIL_ADRES` varchar(50) DEFAULT NULL  COMMENT '회원이메일주소' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `MBER_FXNUM` `MBER_FXNUM` varchar(20) DEFAULT NULL  COMMENT '회원팩스번호' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `MBER_ID` `MBER_ID` varchar(20) NOT NULL DEFAULT ''  COMMENT '회원ID' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `MBER_NM` `MBER_NM` varchar(50) NOT NULL  COMMENT '회원명' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `MBER_STTUS` `MBER_STTUS` varchar(15) DEFAULT NULL  COMMENT '회원상태' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `MBTLNUM` `MBTLNUM` varchar(20) NOT NULL  COMMENT '이동전화번호' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `MIDDLE_TELNO` `MIDDLE_TELNO` varchar(4) NOT NULL  COMMENT '중간전화번호' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `PASSWORD_CNSR` `PASSWORD_CNSR` varchar(100) DEFAULT NULL  COMMENT '비밀번호정답' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `PASSWORD_HINT` `PASSWORD_HINT` varchar(100) DEFAULT NULL  COMMENT '비밀번호힌트' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `PASSWORD` `PASSWORD` varchar(200) NOT NULL  COMMENT '비밀번호' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `SBSCRB_DE` `SBSCRB_DE` datetime DEFAULT NULL  COMMENT '가입일자' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `SEXDSTN_CODE` `SEXDSTN_CODE` char(1) DEFAULT NULL  COMMENT '성별코드' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `ZIP` `ZIP` varchar(6) NOT NULL  COMMENT '우편번호' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `LOCK_AT` `LOCK_AT` char(1) NULL COMMENT '잠금여부' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `LOCK_CNT` `LOCK_CNT` numeric(3) NULL COMMENT '잠금회수' ;
ALTER TABLE `COMTNGNRLMBER` CHANGE `LOCK_LAST_PNTTM` `LOCK_LAST_PNTTM` datetime NULL COMMENT '잠금최종시점' ;
ALTER TABLE `COMTNHPCMINFO` CHANGE `FRST_REGIST_PNTTM` `FRST_REGIST_PNTTM` datetime DEFAULT NULL  COMMENT '최초등록시점' ;
ALTER TABLE `COMTNHPCMINFO` CHANGE `FRST_REGISTER_ID` `FRST_REGISTER_ID` varchar(20) DEFAULT NULL  COMMENT '최초등록자ID' ;
ALTER TABLE `COMTNHPCMINFO` CHANGE `HPCM_DC` `HPCM_DC` varchar(2500) DEFAULT NULL  COMMENT '도움말설명' ;
ALTER TABLE `COMTNHPCMINFO` CHANGE `HPCM_DFN` `HPCM_DFN` varchar(1000) DEFAULT NULL  COMMENT '도움말정의' ;
ALTER TABLE `COMTNHPCMINFO` CHANGE `HPCM_ID` `HPCM_ID` char(20) NOT NULL  COMMENT '도움말ID' ;
ALTER TABLE `COMTNHPCMINFO` CHANGE `HPCM_SE_CODE` `HPCM_SE_CODE` char(1) DEFAULT NULL  COMMENT '도움말구분코드' ;
ALTER TABLE `COMTNHPCMINFO` CHANGE `LAST_UPDT_PNTTM` `LAST_UPDT_PNTTM` datetime DEFAULT NULL  COMMENT '최종수정시점' ;
ALTER TABLE `COMTNHPCMINFO` CHANGE `LAST_UPDUSR_ID` `LAST_UPDUSR_ID` varchar(20) DEFAULT NULL  COMMENT '최종수정자ID' ;


ALTER TABLE COMTNAUTHORINFO COMMENT = '권한정보';
ALTER TABLE `COMTNAUTHORINFO` CHANGE `AUTHOR_CODE` `AUTHOR_CODE` varchar(30) NOT NULL DEFAULT ''  COMMENT '권한코드' ;
ALTER TABLE `COMTNAUTHORINFO` CHANGE `AUTHOR_CREAT_DE` `AUTHOR_CREAT_DE` char(20) NOT NULL  COMMENT '권한생성일' ;
ALTER TABLE `COMTNAUTHORINFO` CHANGE `AUTHOR_DC` `AUTHOR_DC` varchar(200) DEFAULT NULL  COMMENT '권한설명' ;
ALTER TABLE `COMTNAUTHORINFO` CHANGE `AUTHOR_NM` `AUTHOR_NM` varchar(60) NOT NULL  COMMENT '권한명' ;


ALTER TABLE COMTNEMPLYRSCRTYESTBS COMMENT = '사용자보안설정';
ALTER TABLE `COMTNEMPLYRSCRTYESTBS` CHANGE `AUTHOR_CODE` `AUTHOR_CODE` varchar(30) NOT NULL  COMMENT '권한코드' ;
ALTER TABLE `COMTNEMPLYRSCRTYESTBS` CHANGE `MBER_TY_CODE` `MBER_TY_CODE` char(5) DEFAULT NULL  COMMENT '회원유형코드' ;
ALTER TABLE `COMTNEMPLYRSCRTYESTBS` CHANGE `SCRTY_DTRMN_TRGET_ID` `SCRTY_DTRMN_TRGET_ID` varchar(20) NOT NULL  COMMENT '보안설정대상ID' ;


ALTER TABLE COMTNROLES_HIERARCHY COMMENT = '롤 계층구조';
ALTER TABLE `COMTNROLES_HIERARCHY` CHANGE `CHLDRN_ROLE` `CHLDRN_ROLE` varchar(30) NOT NULL  COMMENT '자식롤' ;
ALTER TABLE `COMTNROLES_HIERARCHY` CHANGE `PARNTS_ROLE` `PARNTS_ROLE` varchar(30) NOT NULL  COMMENT '부모롤' ;


ALTER TABLE COMTNROLEINFO COMMENT = '롤정보';
ALTER TABLE `COMTNROLEINFO` CHANGE `ROLE_CODE` `ROLE_CODE` varchar(50) NOT NULL DEFAULT ''  COMMENT '롤코드' ;
ALTER TABLE `COMTNROLEINFO` CHANGE `ROLE_CREAT_DE` `ROLE_CREAT_DE` char(20) NOT NULL  COMMENT '롤생성일' ;
ALTER TABLE `COMTNROLEINFO` CHANGE `ROLE_DC` `ROLE_DC` varchar(200) DEFAULT NULL  COMMENT '롤설명' ;
ALTER TABLE `COMTNROLEINFO` CHANGE `ROLE_NM` `ROLE_NM` varchar(60) NOT NULL  COMMENT '롤명' ;
ALTER TABLE `COMTNROLEINFO` CHANGE `ROLE_PTTRN` `ROLE_PTTRN` varchar(300) DEFAULT NULL  COMMENT '롤패턴' ;
ALTER TABLE `COMTNROLEINFO` CHANGE `ROLE_SORT` `ROLE_SORT` varchar(10) DEFAULT NULL  COMMENT '롤정렬' ;
ALTER TABLE `COMTNROLEINFO` CHANGE `ROLE_TY` `ROLE_TY` varchar(80) DEFAULT NULL  COMMENT '롤유형' ;


ALTER TABLE COMTNAUTHORROLERELATE COMMENT = '권한롤관계';
ALTER TABLE `COMTNAUTHORROLERELATE` CHANGE `AUTHOR_CODE` `AUTHOR_CODE` varchar(30) NOT NULL  COMMENT '권한코드' ;
ALTER TABLE `COMTNAUTHORROLERELATE` CHANGE `CREAT_DT` `CREAT_DT` datetime DEFAULT NULL  COMMENT '생성일시' ;
ALTER TABLE `COMTNAUTHORROLERELATE` CHANGE `ROLE_CODE` `ROLE_CODE` varchar(50) NOT NULL  COMMENT '롤코드' ;


ALTER TABLE COMTNBBSMASTER COMMENT = '게시판마스터';
ALTER TABLE `COMTNBBSMASTER` CHANGE `ATCH_POSBL_FILE_NUMBER` `ATCH_POSBL_FILE_NUMBER` decimal(2,0) NOT NULL  COMMENT '첨부가능파일숫자' ;
ALTER TABLE `COMTNBBSMASTER` CHANGE `ATCH_POSBL_FILE_SIZE` `ATCH_POSBL_FILE_SIZE` decimal(8,0) DEFAULT NULL  COMMENT '첨부가능파일사이즈' ;
ALTER TABLE `COMTNBBSMASTER` CHANGE `BBS_ID` `BBS_ID` char(20) NOT NULL  COMMENT '게시판ID' ;
ALTER TABLE `COMTNBBSMASTER` CHANGE `BBS_INTRCN` `BBS_INTRCN` varchar(2400) DEFAULT NULL  COMMENT '게시판소개' ;
ALTER TABLE `COMTNBBSMASTER` CHANGE `BBS_NM` `BBS_NM` varchar(255) NOT NULL  COMMENT '게시판명' ;
ALTER TABLE `COMTNBBSMASTER` CHANGE `BBS_TY_CODE` `BBS_TY_CODE` char(6) NOT NULL  COMMENT '게시판유형코드' ;
ALTER TABLE `COMTNBBSMASTER` CHANGE `FILE_ATCH_POSBL_AT` `FILE_ATCH_POSBL_AT` char(1) NOT NULL  COMMENT '파일첨부가능여부' ;
ALTER TABLE `COMTNBBSMASTER` CHANGE `FRST_REGIST_PNTTM` `FRST_REGIST_PNTTM` datetime NOT NULL  COMMENT '최초등록시점' ;
ALTER TABLE `COMTNBBSMASTER` CHANGE `FRST_REGISTER_ID` `FRST_REGISTER_ID` varchar(20) NOT NULL  COMMENT '최초등록자ID' ;
ALTER TABLE `COMTNBBSMASTER` CHANGE `LAST_UPDT_PNTTM` `LAST_UPDT_PNTTM` datetime DEFAULT NULL  COMMENT '최종수정시점' ;
ALTER TABLE `COMTNBBSMASTER` CHANGE `LAST_UPDUSR_ID` `LAST_UPDUSR_ID` varchar(20) DEFAULT NULL  COMMENT '최종수정자ID' ;
ALTER TABLE `COMTNBBSMASTER` CHANGE `REPLY_POSBL_AT` `REPLY_POSBL_AT` char(1) DEFAULT NULL  COMMENT '답장가능여부' ;
ALTER TABLE `COMTNBBSMASTER` CHANGE `TMPLAT_ID` `TMPLAT_ID` char(20) DEFAULT NULL  COMMENT '템플릿ID' ;
ALTER TABLE `COMTNBBSMASTER` CHANGE `USE_AT` `USE_AT` char(1) NOT NULL  COMMENT '사용여부' ;
ALTER TABLE `COMTNBBSMASTER` CHANGE `BLOG_AT` `BLOG_AT` char(2) NULL COMMENT '블로그 여부' ;
ALTER TABLE `COMTNBBSMASTER` CHANGE `BLOG_ID` `BLOG_ID` char(20) NULL COMMENT '블로그 ID' ;
ALTER TABLE `COMTNBBSMASTER` CHANGE `CMMNTY_ID` `CMMNTY_ID` char(20) NULL COMMENT '커뮤니티ID' ;


ALTER TABLE COMTNBBSMASTEROPTN COMMENT = '게시판마스터옵션';
ALTER TABLE `COMTNBBSMASTEROPTN` CHANGE `ANSWER_AT` `ANSWER_AT` char(1) NOT NULL  COMMENT '댓글여부' ;
ALTER TABLE `COMTNBBSMASTEROPTN` CHANGE `BBS_ID` `BBS_ID` char(20) NOT NULL  COMMENT '게시판ID' ;
ALTER TABLE `COMTNBBSMASTEROPTN` CHANGE `FRST_REGIST_PNTTM` `FRST_REGIST_PNTTM` datetime NOT NULL  COMMENT '최초등록시점' ;
ALTER TABLE `COMTNBBSMASTEROPTN` CHANGE `FRST_REGISTER_ID` `FRST_REGISTER_ID` varchar(20) NOT NULL  COMMENT '최초등록자ID' ;
ALTER TABLE `COMTNBBSMASTEROPTN` CHANGE `LAST_UPDT_PNTTM` `LAST_UPDT_PNTTM` datetime DEFAULT NULL  COMMENT '최종수정시점' ;
ALTER TABLE `COMTNBBSMASTEROPTN` CHANGE `LAST_UPDUSR_ID` `LAST_UPDUSR_ID` varchar(20) DEFAULT NULL  COMMENT '최종수정자ID' ;
ALTER TABLE `COMTNBBSMASTEROPTN` CHANGE `STSFDG_AT` `STSFDG_AT` char(1) NOT NULL  COMMENT '만족도여부' ;


ALTER TABLE COMTNBBSUSE COMMENT = '게시판활용';
ALTER TABLE `COMTNBBSUSE` CHANGE `BBS_ID` `BBS_ID` char(20) NOT NULL  COMMENT '게시판ID' ;
ALTER TABLE `COMTNBBSUSE` CHANGE `FRST_REGIST_PNTTM` `FRST_REGIST_PNTTM` datetime DEFAULT NULL  COMMENT '최초등록시점' ;
ALTER TABLE `COMTNBBSUSE` CHANGE `FRST_REGISTER_ID` `FRST_REGISTER_ID` varchar(20) NOT NULL  COMMENT '최초등록자ID' ;
ALTER TABLE `COMTNBBSUSE` CHANGE `LAST_UPDT_PNTTM` `LAST_UPDT_PNTTM` datetime DEFAULT NULL  COMMENT '최종수정시점' ;
ALTER TABLE `COMTNBBSUSE` CHANGE `LAST_UPDUSR_ID` `LAST_UPDUSR_ID` varchar(20) DEFAULT NULL  COMMENT '최종수정자ID' ;
ALTER TABLE `COMTNBBSUSE` CHANGE `REGIST_SE_CODE` `REGIST_SE_CODE` char(6) DEFAULT NULL  COMMENT '등록구분코드' ;
ALTER TABLE `COMTNBBSUSE` CHANGE `TRGET_ID` `TRGET_ID` char(20) NOT NULL DEFAULT ''  COMMENT '대상ID' ;
ALTER TABLE `COMTNBBSUSE` CHANGE `USE_AT` `USE_AT` char(1) NOT NULL  COMMENT '사용여부' ;


ALTER TABLE COMTNBBS COMMENT = '게시판';
ALTER TABLE `COMTNBBS` CHANGE `ANSWER_AT` `ANSWER_AT` char(1) DEFAULT NULL  COMMENT '댓글여부' ;
ALTER TABLE `COMTNBBS` CHANGE `ANSWER_LC` `ANSWER_LC` decimal(8,0) DEFAULT NULL  COMMENT '댓글위치' ;
ALTER TABLE `COMTNBBS` CHANGE `ATCH_FILE_ID` `ATCH_FILE_ID` char(20) DEFAULT NULL  COMMENT '첨부파일ID' ;
ALTER TABLE `COMTNBBS` CHANGE `BBS_ID` `BBS_ID` char(20) NOT NULL  COMMENT '게시판ID' ;
ALTER TABLE `COMTNBBS` CHANGE `FRST_REGIST_PNTTM` `FRST_REGIST_PNTTM` datetime NOT NULL  COMMENT '최초등록시점' ;
ALTER TABLE `COMTNBBS` CHANGE `FRST_REGISTER_ID` `FRST_REGISTER_ID` varchar(20) NOT NULL  COMMENT '최초등록자ID' ;
ALTER TABLE `COMTNBBS` CHANGE `LAST_UPDT_PNTTM` `LAST_UPDT_PNTTM` datetime DEFAULT NULL  COMMENT '최종수정시점' ;
ALTER TABLE `COMTNBBS` CHANGE `LAST_UPDUSR_ID` `LAST_UPDUSR_ID` varchar(20) DEFAULT NULL  COMMENT '최종수정자ID' ;
ALTER TABLE `COMTNBBS` CHANGE `NTCE_BGNDE` `NTCE_BGNDE` char(20) DEFAULT NULL  COMMENT '게시시작일' ;
ALTER TABLE `COMTNBBS` CHANGE `NTCE_ENDDE` `NTCE_ENDDE` char(20) DEFAULT NULL  COMMENT '게시종료일' ;
ALTER TABLE `COMTNBBS` CHANGE `NTCR_ID` `NTCR_ID` varchar(20) DEFAULT NULL  COMMENT '게시자ID' ;
ALTER TABLE `COMTNBBS` CHANGE `NTCR_NM` `NTCR_NM` varchar(20) DEFAULT NULL  COMMENT '게시자명' ;
ALTER TABLE `COMTNBBS` CHANGE `NTT_CN` `NTT_CN` mediumtext DEFAULT NULL  COMMENT '게시물내용' ;
ALTER TABLE `COMTNBBS` CHANGE `NTT_ID` `NTT_ID` decimal(20,0) NOT NULL  COMMENT '게시물ID' ;
ALTER TABLE `COMTNBBS` CHANGE `NTT_NO` `NTT_NO` decimal(20,0) DEFAULT NULL  COMMENT '게시물번호' ;
ALTER TABLE `COMTNBBS` CHANGE `NTT_SJ` `NTT_SJ` varchar(2000) DEFAULT NULL  COMMENT '게시물제목' ;
ALTER TABLE `COMTNBBS` CHANGE `PARNTSCTT_NO` `PARNTSCTT_NO` decimal(10,0) DEFAULT NULL  COMMENT '부모글번호' ;
ALTER TABLE `COMTNBBS` CHANGE `PASSWORD` `PASSWORD` varchar(200) DEFAULT NULL  COMMENT '비밀번호' ;
ALTER TABLE `COMTNBBS` CHANGE `RDCNT` `RDCNT` decimal(10,0) DEFAULT NULL  COMMENT '조회수' ;
ALTER TABLE `COMTNBBS` CHANGE `SORT_ORDR` `SORT_ORDR` decimal(8,0) DEFAULT NULL  COMMENT '정렬순서' ;
ALTER TABLE `COMTNBBS` CHANGE `USE_AT` `USE_AT` char(1) NOT NULL  COMMENT '사용여부' ;
ALTER TABLE `COMTNBBS` CHANGE `BLOG_ID` `BLOG_ID` char(20) NULL COMMENT '블로그 ID' ;
ALTER TABLE `COMTNBBS` CHANGE `NOTICE_AT` `NOTICE_AT` char(1) NULL COMMENT '공지사항여부' ;
ALTER TABLE `COMTNBBS` CHANGE `SECRET_AT` `SECRET_AT` char(1) NULL COMMENT '비밀글여부' ;
ALTER TABLE `COMTNBBS` CHANGE `SJ_BOLD_AT` `SJ_BOLD_AT` char(1) NULL COMMENT '제목볼드여부' ;


ALTER TABLE COMTNCOMMENT COMMENT = '댓글';
ALTER TABLE `COMTNCOMMENT` CHANGE `ANSWER_NO` `ANSWER_NO` decimal(20,0) NOT NULL  COMMENT '댓글번호' ;
ALTER TABLE `COMTNCOMMENT` CHANGE `ANSWER` `ANSWER` varchar(200) DEFAULT NULL  COMMENT '댓글' ;
ALTER TABLE `COMTNCOMMENT` CHANGE `BBS_ID` `BBS_ID` char(20) NOT NULL  COMMENT '게시판ID' ;
ALTER TABLE `COMTNCOMMENT` CHANGE `FRST_REGIST_PNTTM` `FRST_REGIST_PNTTM` datetime NOT NULL  COMMENT '최초등록시점' ;
ALTER TABLE `COMTNCOMMENT` CHANGE `FRST_REGISTER_ID` `FRST_REGISTER_ID` varchar(20) NOT NULL  COMMENT '최초등록자ID' ;
ALTER TABLE `COMTNCOMMENT` CHANGE `LAST_UPDT_PNTTM` `LAST_UPDT_PNTTM` datetime DEFAULT NULL  COMMENT '최종수정시점' ;
ALTER TABLE `COMTNCOMMENT` CHANGE `LAST_UPDUSR_ID` `LAST_UPDUSR_ID` varchar(20) DEFAULT NULL  COMMENT '최종수정자ID' ;
ALTER TABLE `COMTNCOMMENT` CHANGE `NTT_ID` `NTT_ID` decimal(20,0) NOT NULL  COMMENT '게시물ID' ;
ALTER TABLE `COMTNCOMMENT` CHANGE `PASSWORD` `PASSWORD` varchar(200) DEFAULT NULL  COMMENT '비밀번호' ;
ALTER TABLE `COMTNCOMMENT` CHANGE `USE_AT` `USE_AT` char(1) NOT NULL  COMMENT '사용여부' ;
ALTER TABLE `COMTNCOMMENT` CHANGE `WRTER_ID` `WRTER_ID` varchar(20) DEFAULT NULL  COMMENT '작성자ID' ;
ALTER TABLE `COMTNCOMMENT` CHANGE `WRTER_NM` `WRTER_NM` varchar(20) DEFAULT NULL  COMMENT '작성자명' ;


ALTER TABLE COMTNSTSFDG COMMENT = '만족도';
ALTER TABLE `COMTNSTSFDG` CHANGE `BBS_ID` `BBS_ID` char(20) NOT NULL  COMMENT '게시판ID' ;
ALTER TABLE `COMTNSTSFDG` CHANGE `FRST_REGIST_PNTTM` `FRST_REGIST_PNTTM` datetime NOT NULL  COMMENT '최초등록시점' ;
ALTER TABLE `COMTNSTSFDG` CHANGE `FRST_REGISTER_ID` `FRST_REGISTER_ID` varchar(20) NOT NULL  COMMENT '최초등록자ID' ;
ALTER TABLE `COMTNSTSFDG` CHANGE `LAST_UPDT_PNTTM` `LAST_UPDT_PNTTM` datetime DEFAULT NULL  COMMENT '최종수정시점' ;
ALTER TABLE `COMTNSTSFDG` CHANGE `LAST_UPDUSR_ID` `LAST_UPDUSR_ID` varchar(20) DEFAULT NULL  COMMENT '최종수정자ID' ;
ALTER TABLE `COMTNSTSFDG` CHANGE `NTT_ID` `NTT_ID` decimal(20,0) NOT NULL  COMMENT '게시물ID' ;
ALTER TABLE `COMTNSTSFDG` CHANGE `PASSWORD` `PASSWORD` varchar(200) DEFAULT NULL  COMMENT '비밀번호' ;
ALTER TABLE `COMTNSTSFDG` CHANGE `STSFDG_CN` `STSFDG_CN` varchar(200) DEFAULT NULL  COMMENT '만족도내용' ;
ALTER TABLE `COMTNSTSFDG` CHANGE `STSFDG_NO` `STSFDG_NO` decimal(20,0) NOT NULL  COMMENT '만족도번호' ;
ALTER TABLE `COMTNSTSFDG` CHANGE `STSFDG` `STSFDG` decimal(1,0) NOT NULL  COMMENT '만족도' ;
ALTER TABLE `COMTNSTSFDG` CHANGE `USE_AT` `USE_AT` char(1) NOT NULL  COMMENT '사용여부' ;
ALTER TABLE `COMTNSTSFDG` CHANGE `WRTER_ID` `WRTER_ID` varchar(20) DEFAULT NULL  COMMENT '작성자ID' ;
ALTER TABLE `COMTNSTSFDG` CHANGE `WRTER_NM` `WRTER_NM` varchar(20) DEFAULT NULL  COMMENT '작성자명' ;


ALTER TABLE COMTNSCRAP COMMENT = '스크랩';
ALTER TABLE `COMTNSCRAP` CHANGE `BBS_ID` `BBS_ID` char(20) NOT NULL  COMMENT '게시판ID' ;
ALTER TABLE `COMTNSCRAP` CHANGE `FRST_REGIST_PNTTM` `FRST_REGIST_PNTTM` datetime NOT NULL  COMMENT '최초등록시점' ;
ALTER TABLE `COMTNSCRAP` CHANGE `FRST_REGISTER_ID` `FRST_REGISTER_ID` varchar(20) NOT NULL  COMMENT '최초등록자ID' ;
ALTER TABLE `COMTNSCRAP` CHANGE `LAST_UPDT_PNTTM` `LAST_UPDT_PNTTM` datetime DEFAULT NULL  COMMENT '최종수정시점' ;
ALTER TABLE `COMTNSCRAP` CHANGE `LAST_UPDUSR_ID` `LAST_UPDUSR_ID` varchar(20) DEFAULT NULL  COMMENT '최종수정자ID' ;
ALTER TABLE `COMTNSCRAP` CHANGE `NTT_ID` `NTT_ID` decimal(20,0) NOT NULL  COMMENT '게시물ID' ;
ALTER TABLE `COMTNSCRAP` CHANGE `SCRAP_ID` `SCRAP_ID` char(20) NOT NULL  COMMENT '스크랩ID' ;
ALTER TABLE `COMTNSCRAP` CHANGE `SCRAP_NM` `SCRAP_NM` varchar(100) NOT NULL  COMMENT '스크랩명' ;
ALTER TABLE `COMTNSCRAP` CHANGE `USE_AT` `USE_AT` char(1) NOT NULL  COMMENT '사용여부' ;


ALTER TABLE COMTNCMMNTY COMMENT = '커뮤니티 속성';
ALTER TABLE `COMTNCMMNTY` CHANGE `CMMNTY_ID` `CMMNTY_ID` char(20) NOT NULL  COMMENT '커뮤니티ID' ;
ALTER TABLE `COMTNCMMNTY` CHANGE `CMMNTY_INTRCN` `CMMNTY_INTRCN` varchar(2400) DEFAULT NULL  COMMENT '커뮤니티소개' ;
ALTER TABLE `COMTNCMMNTY` CHANGE `CMMNTY_NM` `CMMNTY_NM` varchar(255) NOT NULL  COMMENT '커뮤니티명' ;
ALTER TABLE `COMTNCMMNTY` CHANGE `FRST_REGIST_PNTTM` `FRST_REGIST_PNTTM` datetime NOT NULL  COMMENT '최초등록시점' ;
ALTER TABLE `COMTNCMMNTY` CHANGE `FRST_REGISTER_ID` `FRST_REGISTER_ID` varchar(20) NOT NULL  COMMENT '최초등록자ID' ;
ALTER TABLE `COMTNCMMNTY` CHANGE `LAST_UPDT_PNTTM` `LAST_UPDT_PNTTM` datetime DEFAULT NULL  COMMENT '최종수정시점' ;
ALTER TABLE `COMTNCMMNTY` CHANGE `LAST_UPDUSR_ID` `LAST_UPDUSR_ID` varchar(20) DEFAULT NULL  COMMENT '최종수정자ID' ;
ALTER TABLE `COMTNCMMNTY` CHANGE `REGIST_SE_CODE` `REGIST_SE_CODE` char(6) DEFAULT NULL  COMMENT '등록구분코드' ;
ALTER TABLE `COMTNCMMNTY` CHANGE `TMPLAT_ID` `TMPLAT_ID` char(20) DEFAULT NULL  COMMENT '템플릿ID' ;
ALTER TABLE `COMTNCMMNTY` CHANGE `USE_AT` `USE_AT` char(1) NOT NULL  COMMENT '사용여부' ;


ALTER TABLE COMTNCMMNTYUSER COMMENT = '커뮤니티사용자';
ALTER TABLE `COMTNCMMNTYUSER` CHANGE `CMMNTY_ID` `CMMNTY_ID` char(20) NOT NULL  COMMENT '커뮤니티ID' ;
ALTER TABLE `COMTNCMMNTYUSER` CHANGE `EMPLYR_ID` `EMPLYR_ID` varchar(20) NOT NULL  COMMENT '업무사용자ID' ;
ALTER TABLE `COMTNCMMNTYUSER` CHANGE `FRST_REGIST_PNTTM` `FRST_REGIST_PNTTM` datetime NOT NULL  COMMENT '최초등록시점' ;
ALTER TABLE `COMTNCMMNTYUSER` CHANGE `FRST_REGISTER_ID` `FRST_REGISTER_ID` varchar(20) NOT NULL  COMMENT '최초등록자ID' ;
ALTER TABLE `COMTNCMMNTYUSER` CHANGE `LAST_UPDT_PNTTM` `LAST_UPDT_PNTTM` datetime DEFAULT NULL  COMMENT '최종수정시점' ;
ALTER TABLE `COMTNCMMNTYUSER` CHANGE `LAST_UPDUSR_ID` `LAST_UPDUSR_ID` varchar(20) DEFAULT NULL  COMMENT '최종수정자ID' ;
ALTER TABLE `COMTNCMMNTYUSER` CHANGE `MNGR_AT` `MNGR_AT` char(1) NOT NULL  COMMENT '관리자여부' ;
ALTER TABLE `COMTNCMMNTYUSER` CHANGE `SBSCRB_DE` `SBSCRB_DE` datetime DEFAULT NULL  COMMENT '가입일자' ;
ALTER TABLE `COMTNCMMNTYUSER` CHANGE `SECSN_DE` `SECSN_DE` char(20) DEFAULT NULL  COMMENT '탈퇴일' ;
ALTER TABLE `COMTNCMMNTYUSER` CHANGE `USE_AT` `USE_AT` char(1) DEFAULT NULL  COMMENT '사용여부' ;
ALTER TABLE `COMTNCMMNTYUSER` CHANGE `MBER_STTUS` `MBER_STTUS` varchar(15) NULL COMMENT '회원 상태' ;


ALTER TABLE COMTNCLUB COMMENT = '동호회속성';
ALTER TABLE `COMTNCLUB` CHANGE `CLB_ID` `CLB_ID` char(20) NOT NULL  COMMENT '동호회ID' ;
ALTER TABLE `COMTNCLUB` CHANGE `CLB_INTRCN` `CLB_INTRCN` varchar(2400) DEFAULT NULL  COMMENT '동호회소개' ;
ALTER TABLE `COMTNCLUB` CHANGE `CLB_NM` `CLB_NM` varchar(255) NOT NULL  COMMENT '동호회명' ;
ALTER TABLE `COMTNCLUB` CHANGE `CMMNTY_ID` `CMMNTY_ID` char(20) NOT NULL  COMMENT '커뮤니티ID' ;
ALTER TABLE `COMTNCLUB` CHANGE `FRST_REGIST_PNTTM` `FRST_REGIST_PNTTM` datetime NOT NULL  COMMENT '최초등록시점' ;
ALTER TABLE `COMTNCLUB` CHANGE `FRST_REGISTER_ID` `FRST_REGISTER_ID` varchar(20) NOT NULL  COMMENT '최초등록자ID' ;
ALTER TABLE `COMTNCLUB` CHANGE `LAST_UPDT_PNTTM` `LAST_UPDT_PNTTM` datetime DEFAULT NULL  COMMENT '최종수정시점' ;
ALTER TABLE `COMTNCLUB` CHANGE `LAST_UPDUSR_ID` `LAST_UPDUSR_ID` varchar(20) DEFAULT NULL  COMMENT '최종수정자ID' ;
ALTER TABLE `COMTNCLUB` CHANGE `REGIST_SE_CODE` `REGIST_SE_CODE` char(6) DEFAULT NULL  COMMENT '등록구분코드' ;
ALTER TABLE `COMTNCLUB` CHANGE `TMPLAT_ID` `TMPLAT_ID` char(20) DEFAULT NULL  COMMENT '템플릿ID' ;
ALTER TABLE `COMTNCLUB` CHANGE `USE_AT` `USE_AT` char(1) NOT NULL  COMMENT '사용여부' ;


ALTER TABLE COMTNCLUBUSER COMMENT = '동호회사용자';
ALTER TABLE `COMTNCLUBUSER` CHANGE `CLB_ID` `CLB_ID` char(20) NOT NULL  COMMENT '동호회ID' ;
ALTER TABLE `COMTNCLUBUSER` CHANGE `CMMNTY_ID` `CMMNTY_ID` char(20) NOT NULL  COMMENT '커뮤니티ID' ;
ALTER TABLE `COMTNCLUBUSER` CHANGE `EMPLYR_ID` `EMPLYR_ID` varchar(20) NOT NULL  COMMENT '업무사용자ID' ;
ALTER TABLE `COMTNCLUBUSER` CHANGE `FRST_REGIST_PNTTM` `FRST_REGIST_PNTTM` datetime NOT NULL  COMMENT '최초등록시점' ;
ALTER TABLE `COMTNCLUBUSER` CHANGE `FRST_REGISTER_ID` `FRST_REGISTER_ID` varchar(20) NOT NULL  COMMENT '최초등록자ID' ;
ALTER TABLE `COMTNCLUBUSER` CHANGE `LAST_UPDT_PNTTM` `LAST_UPDT_PNTTM` datetime DEFAULT NULL  COMMENT '최종수정시점' ;
ALTER TABLE `COMTNCLUBUSER` CHANGE `LAST_UPDUSR_ID` `LAST_UPDUSR_ID` varchar(20) DEFAULT NULL  COMMENT '최종수정자ID' ;
ALTER TABLE `COMTNCLUBUSER` CHANGE `OPRTR_AT` `OPRTR_AT` char(1) NOT NULL  COMMENT '운영인여부' ;
ALTER TABLE `COMTNCLUBUSER` CHANGE `SBSCRB_DE` `SBSCRB_DE` datetime DEFAULT NULL  COMMENT '가입일자' ;
ALTER TABLE `COMTNCLUBUSER` CHANGE `SECSN_DE` `SECSN_DE` char(20) DEFAULT NULL  COMMENT '탈퇴일' ;
ALTER TABLE `COMTNCLUBUSER` CHANGE `USE_AT` `USE_AT` char(1) NOT NULL  COMMENT '사용여부' ;


ALTER TABLE COMTHCONFMHISTORY COMMENT = '승인이력';
ALTER TABLE `COMTHCONFMHISTORY` CHANGE `CONFM_DE` `CONFM_DE` char(20) DEFAULT NULL  COMMENT '승인일' ;
ALTER TABLE `COMTHCONFMHISTORY` CHANGE `CONFM_NO` `CONFM_NO` decimal(8,0) NOT NULL  COMMENT '승인번호' ;
ALTER TABLE `COMTHCONFMHISTORY` CHANGE `CONFM_RQESTER_ID` `CONFM_RQESTER_ID` varchar(20) NOT NULL  COMMENT '승인요청자ID' ;
ALTER TABLE `COMTHCONFMHISTORY` CHANGE `CONFM_STTUS_CODE` `CONFM_STTUS_CODE` char(4) NOT NULL  COMMENT '승인상태코드' ;
ALTER TABLE `COMTHCONFMHISTORY` CHANGE `CONFM_TY_CODE` `CONFM_TY_CODE` char(4) NOT NULL  COMMENT '승인유형코드' ;
ALTER TABLE `COMTHCONFMHISTORY` CHANGE `CONFMER_ID` `CONFMER_ID` varchar(20) DEFAULT NULL  COMMENT '승인자ID' ;
ALTER TABLE `COMTHCONFMHISTORY` CHANGE `OPERT_ID` `OPERT_ID` varchar(20) DEFAULT NULL  COMMENT '작업ID' ;
ALTER TABLE `COMTHCONFMHISTORY` CHANGE `OPERT_TY_CODE` `OPERT_TY_CODE` char(4) DEFAULT NULL  COMMENT '작업유형코드' ;
ALTER TABLE `COMTHCONFMHISTORY` CHANGE `TRGET_JOB_ID` `TRGET_JOB_ID` char(20) DEFAULT NULL  COMMENT '대상업무ID' ;
ALTER TABLE `COMTHCONFMHISTORY` CHANGE `TRGET_JOB_TY_CODE` `TRGET_JOB_TY_CODE` char(3) DEFAULT NULL  COMMENT '대상업무유형코드' ;


ALTER TABLE COMTNPROGRMLIST COMMENT = '프로그램목록';
ALTER TABLE `COMTNPROGRMLIST` CHANGE `PROGRM_DC` `PROGRM_DC` varchar(200) DEFAULT NULL  COMMENT '프로그램설명' ;
ALTER TABLE `COMTNPROGRMLIST` CHANGE `PROGRM_FILE_NM` `PROGRM_FILE_NM` varchar(60) NOT NULL DEFAULT ''  COMMENT '프로그램파일명' ;
ALTER TABLE `COMTNPROGRMLIST` CHANGE `PROGRM_KOREAN_NM` `PROGRM_KOREAN_NM` varchar(60) DEFAULT NULL  COMMENT '프로그램한글명' ;
ALTER TABLE `COMTNPROGRMLIST` CHANGE `PROGRM_STRE_PATH` `PROGRM_STRE_PATH` varchar(100) NOT NULL  COMMENT '프로그램저장경로' ;
ALTER TABLE `COMTNPROGRMLIST` CHANGE `URL` `URL` varchar(100) NOT NULL  COMMENT 'URL' ;


ALTER TABLE COMTHPROGRMCHANGEDTLS COMMENT = '프로그램변경내역';
ALTER TABLE `COMTHPROGRMCHANGEDTLS` CHANGE `CHANGE_REQUST_CN` `CHANGE_REQUST_CN` varchar(1000) DEFAULT NULL  COMMENT '변경요청내용' ;
ALTER TABLE `COMTHPROGRMCHANGEDTLS` CHANGE `OPETR_ID` `OPETR_ID` varchar(20) DEFAULT NULL  COMMENT '처리자ID' ;
ALTER TABLE `COMTHPROGRMCHANGEDTLS` CHANGE `PROCESS_DE` `PROCESS_DE` char(20) DEFAULT NULL  COMMENT '처리일' ;
ALTER TABLE `COMTHPROGRMCHANGEDTLS` CHANGE `PROCESS_STTUS_CODE` `PROCESS_STTUS_CODE` varchar(15) NOT NULL  COMMENT '처리상태코드' ;
ALTER TABLE `COMTHPROGRMCHANGEDTLS` CHANGE `PROGRM_FILE_NM` `PROGRM_FILE_NM` varchar(60) NOT NULL  COMMENT '프로그램파일명' ;
ALTER TABLE `COMTHPROGRMCHANGEDTLS` CHANGE `REQUST_NO` `REQUST_NO` decimal(10,0) NOT NULL DEFAULT '0'  COMMENT '요청번호' ;
ALTER TABLE `COMTHPROGRMCHANGEDTLS` CHANGE `REQUST_PROCESS_CN` `REQUST_PROCESS_CN` mediumtext DEFAULT NULL  COMMENT '요청처리내용' ;
ALTER TABLE `COMTHPROGRMCHANGEDTLS` CHANGE `REQUST_SJ` `REQUST_SJ` varchar(60) NOT NULL  COMMENT '요청제목' ;
ALTER TABLE `COMTHPROGRMCHANGEDTLS` CHANGE `RQESTDE` `RQESTDE` char(20) DEFAULT NULL  COMMENT '요청일' ;
ALTER TABLE `COMTHPROGRMCHANGEDTLS` CHANGE `RQESTER_ID` `RQESTER_ID` varchar(20) NOT NULL  COMMENT '요청자ID' ;


