<%@ page language="java" contentType="text/html; charset=utf-8" pageEncoding="utf-8"%>
<DIV id="main"> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''>+<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2><b>▶ 보안관리</b></font><br> 
<div id='div1000000'> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/cmm/sec/arm/EgovAuthorListView.do');">― 권한관리</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/cmm/sec/arm/EgovGroupListView.do');">― 그룹관리</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/cmm/sec/arm/EgovGroupAuthorListView.do');">― 권한그룹관리</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/cmm/sec/arm/EgovRoleListView.do');">― 롤관리</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/cmm/sec/arm/EgovDeptAuthorListView.do');">― 부서권한관리</a></font><br> 
</div> 
<br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''>+<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2><b>▶ 사용자지원</b></font><br> 
<div id='div2000000'> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''>+<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2><b>▶ 메뉴관리</b></font><br> 
<div id='div2010000'> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/sym/mnu/mpm/listMenu.do');">― 메뉴목록관리</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/sym/mnu/mpm/listMenuTree.do');">― 메뉴리스트</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/sym/mnu/mcm/listMenuCreat.do');">― 메뉴생성관리</a></font><br> 
</div> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''>+<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2><b>▶ 프로그램관리</b></font><br> 
<div id='div2020000'> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/sym/prm/listProgram.do');">― 프로그램목록관리</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/sym/prm/listProgramChangeRequst.do');">― 프로그램변경관리</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/sym/prm/listProgramChangeProcess.do');">― 프로그램변경요청</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/sym/prm/listProgramChgHst.do');">― 프로그램변경이력</a></font><br> 
</div> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''>+<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2><b>▶ 사용자관리</b></font><br> 
<div id='div2030000'> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/uss/umt/listUser.do');">― 업무사용자관리</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/uss/umt/listMber.do');">― 일반회원관리</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/uss/umt/listEntrprsMber.do');">― 기업회원관리</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/uss/umt/stplatMberView.do');">― 일반회원가입처리</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/uss/umt/stplatEntrprsMberView.do');">― 기업회원가입처리</a></font><br> 
</div> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/uss/olp/mgt/listMeeting.do');">― 회의관리</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''>+<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2><b>▶ 설문관리</b></font><br> 
<div id='div2050000'> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/uss/olp/qtm/listQustnrTmplat.do');">― 설문템플릿관리</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/uss/olp/qmc/listQustnr.do');">― 설문지관리</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/uss/olp/qqm/listQustnrQestn.do');">― 설문문항관리</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/uss/olp/qim/listQustnrItem.do');">― 설문항목관리</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/uss/olp/qri/listQustnrRespondInfo.do');">― 설문조사(응답결과)관리</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/uss/olp/qri/listQustnrRespondInfoUser.do');">― 설문참여</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/uss/olp/qrm/listQustnrRespond.do');">― 설문응답자정보관리</a></font><br> 
</div> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/uss/sam/stp/StplatListInqire.do');">― 약관관리</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/uss/sam/cpy/CpyrhtPrtcPolicyListInqire.do');">― 저작권보호정책관리</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''>+<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2><b>▶ 상담관리</b></font><br> 
<div id='div2080000'> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/uss/olp/cns/EgovCnsltListInqire.do');">― 상담목록조회</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/uss/olp/cns/EgovCnsltAnswerListInqire.do');">― 상담답변목록조회</a></font><br> 
</div> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/uss/olh/hpc/HpcmListInqire.do');">― 도움말관리</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/uss/olh/wor/WordDicaryListInqire.do');">― 용어사전관리</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/uss/olh/faq/FaqListInqire.do');">― FAQ관리</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''>+<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2><b>▶ Q&amp;A관리</b></font><br> 
<div id='div2120000'> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/uss/olh/qna/listQna.do');">― Q&amp;A목록조회</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/uss/olh/qna/QnaAnswerListInqire.do');">― Q&amp;A답변목록조회</a></font><br> 
</div> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/uss/ion/nws/listNewsInfo.do');">― 뉴스관리</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''>+<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2><b>▶ 사이트관리</b></font><br> 
<div id='div2210000'> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/uss/ion/sit/listSiteInfo.do');">― 사이트목록조회</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/PageLink.do?link=/cmm/sym/mpm/EgovSiteMap');">― 사이트맵</a></font><br> 
</div> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/uss/ion/rec/listRecomendSite.do');">― 추천사이트관리</a></font><br> 
</div> 
<br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''>+<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2><b>▶ 시스템관리</b></font><br> 
<div id='div4000000'> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''>+<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2><b>▶ 시스템이력관리</b></font><br> 
<div id='div4020000'> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/sym/log/SelectSysHistoryList.do');">― 시스템이력조회</a></font><br> 
</div> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/sym/ccm/ccc/EgovCcmCmmnClCodeList.do');">― 공통분류코드목록</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''>+<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2><b>▶ 로그조회</b></font><br> 
<div id='div4010000'> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/sym/log/SelectSysLogList.do');">― 시스템로그조회</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/sym/log/SelectTrsmrcvLogList.do');">― 송수신로그조회</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('');">― 로그인로그조회</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('');">― 웹로그조회</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('');">― 사용자로그조회</a></font><br> 
</div> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/sym/ccm/cde/EgovCcmCmmnDetailCodeList.do');">― 공통상세코드목록</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/sym/ccm/cca/EgovCcmCmmnCodeList.do');">― 공통코드목록</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/sym/ccm/zip/listZip.do');">― 우편번호목록</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/sym/ccm/adc/listAdministCode.do');">― 행정코드목록</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''>+<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2><b>▶ 달력</b></font><br> 
<div id='div4080000'> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/sym/cal/listRestde.do');">― 휴일목록</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('');">― 일반달력 일간</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('');">― 일반달력 주간</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('');">― 일반달력 월간</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('');">― 일반달력 연간</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('');">― 행정달력 일간</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('');">― 행정달력 주간</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('');">― 행정달력 월간</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('');">― 행정달력 연간</a></font><br> 
</div> 
</div> 
<br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''>+<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2><b>▶ 협업</b></font><br> 
<div id='div5000000'> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''>+<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2><b>▶ 게시판</b></font><br> 
<div id='div5010000'> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/cop/bbs/selectBBSMasterInfs.do');">― 게시판목록조회</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/cop/com/selectBBSUseInfs.do');">― 게시판 사용정보 조회</a></font><br> 
</div> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''>+<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2><b>▶ 커뮤니티/동호회</b></font><br> 
<div id='div5020000'> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/cop/cmy/selectCmmntyInfs.do');">― 커뮤니티목록조회</a></font><br> 
</div> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''>+<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2><b>▶ 공통관리</b></font><br> 
<div id='div5030000'> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/cop/com/selectTemplateInfs.do');">― 템플릿 목록조회</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/cop/cmy/selectConfirmRequest.do');">― 승인정보조회</a></font><br> 
</div> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''>+<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2><b>▶ 명함관리</b></font><br> 
<div id='div5040000'> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/cop/ncm/selectNcrdInfs.do');">― 명함목록조회</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/cop/ncm/addNcrdInf.do');">― 명함등록</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('');">― 내 명함목록</a></font><br> 
</div> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''>+<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2><b>▶ 행사/이벤트/캠페인</b></font><br> 
<div id='div5050000'> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/uss/ion/ecc/listEventCmpgn.do');">― 행사/이벤트/캠페인 조회</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/uss/ion/ecc/listTnextrlHrInfo.do');">― 외부인사정보 조회</a></font><br> 
</div> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''>+<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2><b>▶ 게시판 예시</b></font><br> 
<div id='div5060000'> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('');">― 사진첩</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('');">― 방명록</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('');">― 유효게시판</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('');">― 익명게시판</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('');">― 자료실</a></font><br> 
</div> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/cop/cus/CmmntyViewPage.do');">― 커뮤니티/동호회 뷰페이지</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''>+<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2><b>▶ 일정관리</b></font><br> 
<div id='div5080000'> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('');">― 부서일정관리</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('');">― 일정관리</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('');">― 전체일정</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('');">― 일지관리</a></font><br> 
</div> 
</div> 
<br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''>+<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2><b>▶ 통계/리포팅</b></font><br> 
<div id='div6000000'> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/sts/selectBbsStats.do');">― 게시물통계</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/sts/selectUserStats.do');">― 사용자통계</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/sts/selectScrinStats.do');">― 화면통계</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/sts/selectConectStats.do');">― 접속통계</a></font><br> 
</div> 
<br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''>+<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2><b>▶ 전자우편연계</b></font><br> 
<div id='div7000000'> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/ems/selectSndngMailList.do');">― 발송메일내역</a></font><br> 
<img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><img src='/images/cmm/utl/menu_empty.gif' border='0' alt=''><font size=2 class='.location'><a href="javascript:fCallUrl('/ems/insertSndngMailView.do');">― 발송메일등록</a></font><br> 
</div> 
</DIV>