




CREATE TABLE COMTNPROXYINFO
(
	PROXY_ID              CHAR(20) NOT NULL,
	PROXY_NM              VARCHAR(60) NULL,
	PROXY_IP              VARCHAR(23) NULL,
	PROXY_PORT            VARCHAR(10) NULL,
	TRGET_SVC_NM          VARCHAR(255) NULL,
	SVC_DC                VARCHAR(2000) NULL,
	SVC_IP                VARCHAR(23) NULL,
	SVC_PORT              VARCHAR(10) NULL,
	SVC_STTUS             CHAR(2) NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	 PRIMARY KEY (PROXY_ID)
);
CREATE UNIQUE INDEX COMTNPROXYINFO_PK ON COMTNPROXYINFO (PROXY_ID);


CREATE TABLE COMTNPROXYLOGINFO
(
	PROXY_ID              CHAR(20) NOT NULL,
	CLNT_IP               VARCHAR(23) NULL,
	CLNT_PORT             VARCHAR(10) NULL,
	CONECT_TIME           DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LOG_ID                CHAR(20) NOT NULL,
	 PRIMARY KEY (PROXY_ID,LOG_ID),
	FOREIGN KEY COMTNPROXYLOGINFO_FK1 (PROXY_ID) REFERENCES COMTNPROXYINFO(PROXY_ID)
);
CREATE UNIQUE INDEX COMTNPROXYLOGINFO_PK ON COMTNPROXYLOGINFO (PROXY_ID, LOG_ID);


CREATE TABLE COMTNQUSTNRTMPLAT (
	QUSTNR_TMPLAT_ID      CHAR(20) NOT NULL,
	QUSTNR_TMPLAT_TY      VARCHAR(100) NULL,
	QUSTNR_TMPLAT_DC      VARCHAR(2000) NULL,
	QUSTNR_TMPLAT_PATH_NM  VARCHAR(100) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	QUSTNR_TMPLAT_IMAGE_INFO  BLOB NULL,
	 PRIMARY KEY (QUSTNR_TMPLAT_ID)
);
CREATE UNIQUE INDEX COMTNQUSTNRTMPLAT_PK ON COMTNQUSTNRTMPLAT (QUSTNR_TMPLAT_ID);


CREATE TABLE COMTNQESTNRINFO
(
	QUSTNR_TMPLAT_ID      CHAR(20) NOT NULL,
	QESTNR_ID             CHAR(20) NOT NULL,
	QUSTNR_SJ             VARCHAR(255) NULL,
	QUSTNR_PURPS          VARCHAR(1000) NULL,
	QUSTNR_WRITNG_GUIDANCE_CN  VARCHAR(2000) NULL,
	QUSTNR_TRGET          VARCHAR(1000) NULL,
	QUSTNR_BGNDE          CHAR(20) NULL,
	QUSTNR_ENDDE          CHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID),
	FOREIGN KEY COMTNQESTNRINFO_FK1 (QUSTNR_TMPLAT_ID) REFERENCES COMTNQUSTNRTMPLAT(QUSTNR_TMPLAT_ID)
);
CREATE UNIQUE INDEX COMTNQESTNRINFO_PK ON COMTNQESTNRINFO (QUSTNR_TMPLAT_ID, QESTNR_ID);
CREATE INDEX COMTNQESTNRINFO_i01 ON COMTNQESTNRINFO (QUSTNR_TMPLAT_ID);


CREATE TABLE COMTNQUSTNRRESPONDINFO
(
	QUSTNR_TMPLAT_ID      CHAR(20) NOT NULL,
	QESTNR_ID             CHAR(20) NOT NULL,
	QUSTNR_RESPOND_ID     CHAR(20) NOT NULL,
	SEXDSTN_CODE          CHAR(1) NULL,
	OCCP_TY_CODE          CHAR(1) NULL,
	RESPOND_NM            VARCHAR(50) NULL,
	BRTHDY                CHAR(20) NULL,
	AREA_NO               VARCHAR(4) NULL,
	MIDDLE_TELNO          VARCHAR(4) NULL,
	END_TELNO             VARCHAR(4) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID,QUSTNR_RESPOND_ID),
	FOREIGN KEY COMTNQUSTNRRESPONDINFO_FK1 (QUSTNR_TMPLAT_ID,QESTNR_ID) REFERENCES COMTNQESTNRINFO(QUSTNR_TMPLAT_ID,QESTNR_ID)
);
CREATE UNIQUE INDEX COMTNQUSTNRRESPONDINFO_PK ON COMTNQUSTNRRESPONDINFO (QUSTNR_TMPLAT_ID, QESTNR_ID, QUSTNR_RESPOND_ID);
CREATE INDEX COMTNQUSTNRRESPONDINFO_i01 ON COMTNQUSTNRRESPONDINFO (QESTNR_ID, QUSTNR_TMPLAT_ID);


CREATE TABLE COMTRDNMADRZIP
(
	RDMN_CODE             VARCHAR(12) NOT NULL,
	SN                    NUMERIC(10) NOT NULL,
	CTPRVN_NM             VARCHAR(20) NULL,
	SIGNGU_NM             VARCHAR(20) NULL,
	RDMN                  VARCHAR(60) NULL,
	BDNBR_MNNM            VARCHAR(5) NULL,
	BDNBR_SLNO            VARCHAR(5) NULL,
	BULD_NM               VARCHAR(60) NULL,
	DETAIL_BULD_NM        VARCHAR(60) NULL,
	ZIP                   VARCHAR(6) NOT NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (SN)
);


CREATE UNIQUE INDEX COMTRDNMADRZIP_PK ON COMTRDNMADRZIP (RDMN_CODE,	SN);



CREATE TABLE COMTNQAINFO
(
	QA_ID                 CHAR(20) NOT NULL,
	QESTN_SJ              VARCHAR(255) NULL,
	QESTN_CN              VARCHAR(2500) NULL,
	WRITNG_DE             CHAR(20) NULL,
	RDCNT                 NUMERIC(10) NULL,
	EMAIL_ADRES           VARCHAR(50) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	QNA_PROCESS_STTUS_CODE  CHAR(1) NULL,
	WRTER_NM              VARCHAR(20) NULL,
	ANSWER_CN             VARCHAR(2500) NULL,
	WRITNG_PASSWORD       VARCHAR(20) NULL,
	ANSWER_DE             CHAR(20) NULL,
	EMAIL_ANSWER_AT       CHAR(1) NULL,
	AREA_NO               VARCHAR(4) NULL,
	MIDDLE_TELNO          VARCHAR(4) NULL,
	END_TELNO             VARCHAR(4) NULL,
	 PRIMARY KEY (QA_ID)
);
CREATE UNIQUE INDEX COMTNQAINFO_PK ON COMTNQAINFO (QA_ID);




CREATE TABLE COMTNSTPLATINFO
(
	USE_STPLAT_ID         CHAR(20) NOT NULL,
	USE_STPLAT_NM         VARCHAR(100) NULL,
	USE_STPLAT_CN         MEDIUMTEXT NULL,
	INFO_PROVD_AGRE_CN    MEDIUMTEXT NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (USE_STPLAT_ID)
);
CREATE UNIQUE INDEX COMTNSTPLATINFO_PK ON COMTNSTPLATINFO (USE_STPLAT_ID);


CREATE TABLE COMTNQUSTNRQESITM
(
	QESTNR_ID             CHAR(20) NOT NULL,
	QUSTNR_QESITM_ID      CHAR(20) NOT NULL,
	QUSTNR_TMPLAT_ID      CHAR(20) NOT NULL,
	QESTN_SN              NUMERIC(10) NULL,
	QESTN_TY_CODE         CHAR(1) NULL,
	QESTN_CN              VARCHAR(2500) NULL,
	MXMM_CHOISE_CO        NUMERIC(5) NULL,
	FRST_REGIST_PNTTM     DATETIME NOT NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM       DATETIME NOT NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NOT NULL,
	 PRIMARY KEY (QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID),
	FOREIGN KEY COMTNQUSTNRQESITM_FK1 (QUSTNR_TMPLAT_ID,QESTNR_ID) REFERENCES COMTNQESTNRINFO(QUSTNR_TMPLAT_ID,QESTNR_ID)
);
CREATE UNIQUE INDEX COMTNQUSTNRQESITM_PK ON COMTNQUSTNRQESITM (QESTNR_ID, QUSTNR_QESITM_ID,	QUSTNR_TMPLAT_ID);
CREATE INDEX COMTNQUSTNRQESITM_i02 ON COMTNQUSTNRQESITM (QESTNR_ID, QUSTNR_TMPLAT_ID);


CREATE TABLE COMTNQUSTNRRSPNSRESULT
(
	QUSTNR_RSPNS_RESULT_ID  CHAR(20) NOT NULL,
	QESTNR_ID             CHAR(20) NOT NULL,
	QUSTNR_QESITM_ID      CHAR(20) NOT NULL,
	QUSTNR_TMPLAT_ID      CHAR(20) NOT NULL,
	RESPOND_ANSWER_CN     VARCHAR(1000) NULL,
	ETC_ANSWER_CN         VARCHAR(1000) NULL,
	RESPOND_NM            VARCHAR(50) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	QUSTNR_IEM_ID         VARCHAR(20) NULL,
	 PRIMARY KEY (QUSTNR_RSPNS_RESULT_ID,QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID),
	FOREIGN KEY COMTNQUSTNRRSPNSRESULT_FK1 (QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID) REFERENCES COMTNQUSTNRQESITM(QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID)
);
CREATE UNIQUE INDEX COMTNQUSTNRRSPNSRESULT_PK ON COMTNQUSTNRRSPNSRESULT
(
	QUSTNR_RSPNS_RESULT_ID,
	QESTNR_ID,
	QUSTNR_QESITM_ID,
	QUSTNR_TMPLAT_ID
);
CREATE INDEX COMTNQUSTNRRSPNSRESULT_i01 ON COMTNQUSTNRRSPNSRESULT
(
	QESTNR_ID,
	QUSTNR_QESITM_ID,
	QUSTNR_TMPLAT_ID
);


CREATE TABLE COMTNQUSTNRIEM
(
	QUSTNR_TMPLAT_ID      CHAR(20) NOT NULL,
	QESTNR_ID             CHAR(20) NOT NULL,
	QUSTNR_QESITM_ID      CHAR(20) NOT NULL,
	QUSTNR_IEM_ID         VARCHAR(20) NOT NULL,
	IEM_SN                NUMERIC(5) NULL,
	IEM_CN                VARCHAR(1000) NULL,
	ETC_ANSWER_AT         CHAR(1) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_IEM_ID),
	FOREIGN KEY COMTNQUSTNRIEM_FK1 (QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID) REFERENCES COMTNQUSTNRQESITM(QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID)
);
CREATE UNIQUE INDEX COMTNQUSTNRIEM_PK ON COMTNQUSTNRIEM
(
	QUSTNR_TMPLAT_ID,
	QESTNR_ID,
	QUSTNR_QESITM_ID,
	QUSTNR_IEM_ID
);
CREATE INDEX COMTNQUSTNRIEM_i01 ON COMTNQUSTNRIEM
(
	QUSTNR_QESITM_ID,
	QESTNR_ID,
	QUSTNR_TMPLAT_ID
);


CREATE TABLE COMTNADMINISTRATIONWORD
(
	ADMINIST_WORD_ID      CHAR(20) NOT NULL,
	ADMINIST_WORD_NM      VARCHAR(255) NULL,
	ADMINIST_WORD_ENG_NM  VARCHAR(255) NULL,
	ADMINIST_WORD_ABRV_NM  VARCHAR(255) NULL,
	THEMA_RELM            VARCHAR(255) NULL,
	WORD_SE               VARCHAR(255) NULL,
	RELATE_STD_WORD       VARCHAR(255) NULL,
	ADMINIST_WORD_DFN     VARCHAR(2500) NULL,
	ADMINIST_WORD_DC      VARCHAR(4000) NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	 PRIMARY KEY (ADMINIST_WORD_ID)
);
CREATE UNIQUE INDEX COMTNADMINISTRATIONWORD_PK ON COMTNADMINISTRATIONWORD (ADMINIST_WORD_ID);


CREATE TABLE COMTNONLINEMANUAL
(
	ONLINE_MNL_ID         CHAR(20) NOT NULL,
	ONLINE_MNL_SE_CODE    CHAR(3) NULL,
	ONLINE_MNL_DFN        MEDIUMTEXT NULL,
	ONLINE_MNL_DC         MEDIUMTEXT NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	ONLINE_MNL_NM         VARCHAR(255) NULL,
	 PRIMARY KEY (ONLINE_MNL_ID)
);
CREATE UNIQUE INDEX COMTNONLINEMANUAL_PK ON COMTNONLINEMANUAL (ONLINE_MNL_ID);



CREATE TABLE COMTNFAQINFO
(
	FAQ_ID                CHAR(20) NOT NULL,
	QESTN_SJ              VARCHAR(255) NULL,
	QESTN_CN              VARCHAR(2500) NULL,
	ANSWER_CN             VARCHAR(2500) NULL,
	RDCNT                 NUMERIC(10) NULL,
	FRST_REGIST_PNTTM     DATETIME NOT NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM       DATETIME NOT NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NOT NULL,
	ATCH_FILE_ID          CHAR(20) NULL,
	QNA_PROCESS_STTUS_CODE  CHAR(1) NULL,
	 PRIMARY KEY (FAQ_ID),
	FOREIGN KEY COMTNFAQINFO_FK1 (ATCH_FILE_ID) REFERENCES COMTNFILE(ATCH_FILE_ID)
);
CREATE UNIQUE INDEX COMTNFAQINFO_PK ON COMTNFAQINFO (FAQ_ID);
CREATE INDEX COMTNFAQINFO_i01 ON COMTNFAQINFO (ATCH_FILE_ID);


CREATE TABLE COMTNMTGINFO
(
	MTG_ID                CHAR(20) NOT NULL,
	MTG_NM                VARCHAR(255) NULL,
	MTG_MTR_CN            VARCHAR(1000) NULL,
	MTG_SN                NUMERIC(10) NULL,
	MTG_CO                NUMERIC(5) NULL,
	MTG_DE                CHAR(20) NULL,
	MTG_PLACE             VARCHAR(255) NULL,
	MTG_BEGIN_TM          VARCHAR(14) NULL,
	MTG_END_TM            VARCHAR(14) NULL,
	CLSDR_MTG_AT          CHAR(1) NULL,
	READNG_BGNDE          CHAR(20) NULL,
	READNG_AT             CHAR(1) NULL,
	MTG_RESULT_CN         VARCHAR(1000) NULL,
	MTG_RESULT_ENNC       CHAR(1) NULL,
	ETC_MATTER            VARCHAR(1000) NULL,
	MNGT_DEPT_ID          VARCHAR(20) NULL,
	MNAER_ID              VARCHAR(20) NULL,
	MNAER_DEPT_ID         VARCHAR(20) NULL,
	MTG_AT                CHAR(1) NULL,
	NONATDRN_CO           NUMERIC(10) NULL,
	ATDRN_CO              NUMERIC(10) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (MTG_ID)
);
CREATE UNIQUE INDEX COMTNMTGINFO_PK ON COMTNMTGINFO (MTG_ID);




CREATE TABLE COMTNCPYRHTINFO
(
	CPYRHT_ID             CHAR(20) NOT NULL,
	CPYRHT_PRTC_POLICY_CN  VARCHAR(2500) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (CPYRHT_ID)
);
CREATE UNIQUE INDEX COMTNCPYRHTINFO_PK ON COMTNCPYRHTINFO (CPYRHT_ID);


CREATE TABLE COMTNONLINEPOLLMANAGE
(
	POLL_ID               CHAR(20) NOT NULL,
	POLL_NM               VARCHAR(255) NULL,
	POLL_BGNDE            CHAR(10) NULL,
	POLL_ENDDE            CHAR(10) NULL,
	POLL_KND              CHAR(3) NULL,
	POLL_DSUSE_ENNC       CHAR(1) NULL,
	POLL_ATMC_DSUSE_ENNC  CHAR(1) NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	 PRIMARY KEY (POLL_ID)
);
CREATE UNIQUE INDEX COMTNONLINEPOLLMANAGE_PK ON COMTNONLINEPOLLMANAGE (POLL_ID);


CREATE TABLE COMTNONLINEPOLLIEM
(
	POLL_IEM_NM           VARCHAR(255) NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	POLL_IEM_ID           CHAR(20) NOT NULL,
	POLL_ID               CHAR(20) NOT NULL,
	 PRIMARY KEY (POLL_ID,POLL_IEM_ID),
	FOREIGN KEY COMTNONLINEPOLLIEM_FK1 (POLL_ID) REFERENCES COMTNONLINEPOLLMANAGE(POLL_ID)
);
CREATE UNIQUE INDEX COMTNONLINEPOLLIEM_PK ON COMTNONLINEPOLLIEM (POLL_ID, POLL_IEM_ID);
CREATE INDEX COMTNONLINEPOLLIEM_i01 ON COMTNONLINEPOLLIEM (POLL_ID);


CREATE TABLE COMTNONLINEPOLLRESULT
(
	POLL_RESULT_ID        CHAR(20) NOT NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	POLL_IEM_ID           CHAR(20) NOT NULL,
	POLL_ID               CHAR(20) NOT NULL,
	 PRIMARY KEY (POLL_RESULT_ID,POLL_IEM_ID,POLL_ID),
	FOREIGN KEY COMTNONLINEPOLLRESULT_FK1 (POLL_ID,POLL_IEM_ID) REFERENCES COMTNONLINEPOLLIEM(POLL_ID,POLL_IEM_ID)
);
CREATE UNIQUE INDEX COMTNONLINEPOLLRESULT_PK ON COMTNONLINEPOLLRESULT
(
	POLL_RESULT_ID,
	POLL_IEM_ID,
	POLL_ID
);
CREATE INDEX COMTNONLINEPOLLRESULT_i01 ON COMTNONLINEPOLLRESULT
(
	POLL_IEM_ID,
	POLL_ID
);


CREATE TABLE COMTNWORDDICARYINFO
(
	WORD_ID               CHAR(20) NOT NULL,
	WORD_NM               VARCHAR(255) NULL,
	ENG_NM                VARCHAR(60) NULL,
	WORD_DC               VARCHAR(4000) NULL,
	SYNONM                VARCHAR(100) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (WORD_ID)
);
CREATE UNIQUE INDEX COMTNWORDDICARYINFO_PK ON COMTNWORDDICARYINFO (WORD_ID);



CREATE TABLE COMTNHPCMINFO
(
	HPCM_ID               CHAR(20) NOT NULL,
	HPCM_SE_CODE          CHAR(1) NULL,
	HPCM_DFN              VARCHAR(1000) NULL,
	HPCM_DC               VARCHAR(2500) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (HPCM_ID)
);
CREATE UNIQUE INDEX COMTNHPCMINFO_PK ON COMTNHPCMINFO (HPCM_ID);


CREATE TABLE COMTNCNSLTLIST
(
	CNSLT_ID              CHAR(20) NOT NULL,
	CNSLT_SJ              VARCHAR(255) NULL,
	OTHBC_AT              CHAR(1) NULL,
	EMAIL_ADRES           VARCHAR(50) NULL,
	CNSLT_CN              VARCHAR(2500) NULL,
	MANAGT_CN             VARCHAR(2500) NULL,
	MANAGT_DE             CHAR(20) NULL,
	RDCNT                 NUMERIC(10) NULL,
	ATCH_FILE_ID          CHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	AREA_NO               VARCHAR(4) NULL,
	MIDDLE_TELNO          VARCHAR(4) NULL,
	END_TELNO             VARCHAR(4) NULL,
	FRST_MBTLNUM          VARCHAR(4) NULL,
	MIDDLE_MBTLNUM        VARCHAR(4) NULL,
	END_MBTLNUM           VARCHAR(4) NULL,
	WRITNG_DE             CHAR(20) NULL,
	WRTER_NM              VARCHAR(20) NULL,
	EMAIL_ANSWER_AT       CHAR(1) NULL,
	QNA_PROCESS_STTUS_CODE  CHAR(1) NULL,
	WRITNG_PASSWORD       VARCHAR(20) NULL,
	 PRIMARY KEY (CNSLT_ID)
);
CREATE UNIQUE INDEX COMTNCNSLTLIST_PK ON COMTNCNSLTLIST (CNSLT_ID);



CREATE TABLE COMTNANSWER
(
	NTT_ID                NUMERIC(20) NOT NULL,
	BBS_ID                CHAR(20) NOT NULL,
	WRTER_ID              VARCHAR(20) NULL,
	ANSWER                VARCHAR(200) NULL,
	USE_AT                CHAR(1) NOT NULL,
	WRTER_NM              VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NOT NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	ANSWER_NO             NUMERIC(20) NOT NULL,
	 PRIMARY KEY (NTT_ID,BBS_ID,ANSWER_NO),
	FOREIGN KEY COMTNANSWER_FK1 (BBS_ID) REFERENCES COMTNBBSMASTEROPTN(BBS_ID)
);
CREATE UNIQUE INDEX COMTNANSWER_PK ON COMTNANSWER (NTT_ID, BBS_ID, ANSWER_NO);


CREATE TABLE COMTNDAMCALRES
(
	ORGNZT_ID             CHAR(20) NULL,
	EXPERT_ID             CHAR(20) NULL,
	KNWLDG_TY_CODE        VARCHAR(3) NULL,
	EMPLYR_ID             VARCHAR(20) NULL,
	KNWLDG_NM             VARCHAR(60) NULL,
	KNWLDG_CN             VARCHAR(2500) NULL,
	ATCH_FILE_ID          CHAR(20) NULL,
	PARNTS_KNWLDG_ID      CHAR(20) NULL,
	ANSWER_DP             NUMERIC(20) NULL,
	ANSWER_ORDR           NUMERIC(20) NULL,
	ANSWER_GROUP_NO       NUMERIC(20) NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	KNWLDG_ID             CHAR(20) NOT NULL,
	 PRIMARY KEY (KNWLDG_ID)
);
CREATE UNIQUE INDEX COMTNDAMCALRES_PK ON COMTNDAMCALRES (KNWLDG_ID);


CREATE TABLE COMTHTRSMRCVMNTRNGLOGINFO
(
	LOG_ID                CHAR(20) NOT NULL,
	CNTC_ID               CHAR(8) NOT NULL,
	TEST_CLASS_NM         VARCHAR(255) NULL,
	MNGR_NM               VARCHAR(60) NULL,
	MNGR_EMAIL_ADRES      VARCHAR(50) NULL,
	MNTRNG_STTUS          CHAR(2) NULL,
	LOG_INFO              VARCHAR(2000) NULL,
	CREAT_DT              DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NOT NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NOT NULL,
	 PRIMARY KEY (LOG_ID)
);
CREATE UNIQUE INDEX COMTHTRSMRCVMNTRNGLOGINFO_PK ON COMTHTRSMRCVMNTRNGLOGINFO (LOG_ID);




CREATE TABLE COMTNHTTPMON
(
	SYS_ID                VARCHAR(20) NOT NULL,
	SITE_URL              VARCHAR(100) NULL,
	WEBSVC_KND            VARCHAR(10) NULL,
	HTTP_STTUS_CODE       VARCHAR(3) NULL,
	CREAT_DT              DATETIME NULL,
	MNGR_NM               VARCHAR(60) NULL,
	MNGR_EMAIL_ADRES      VARCHAR(50) NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	 PRIMARY KEY (SYS_ID)
);
CREATE UNIQUE INDEX COMTNHTTPMON_PK ON COMTNHTTPMON (SYS_ID);


CREATE TABLE COMTHHTTPMONLOGINFO
(
	SYS_ID                VARCHAR(20) NOT NULL,
	SITE_URL              VARCHAR(100) NULL,
	WEBSVC_KND            VARCHAR(10) NULL,
	HTTP_STTUS_CODE       VARCHAR(3) NULL,
	CREAT_DT              DATETIME NULL,
	LOG_INFO              VARCHAR(2000) NULL,
	MNGR_NM               VARCHAR(60) NULL,
	MNGR_EMAIL_ADRES      VARCHAR(50) NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LOG_ID                CHAR(20) NOT NULL,
	 PRIMARY KEY (SYS_ID,LOG_ID),
	FOREIGN KEY COMTHHTTPMONLOGINFO_FK2 (SYS_ID) REFERENCES COMTNHTTPMON(SYS_ID)
);
CREATE UNIQUE INDEX COMTHHTTPMONLOGINFO_PK ON COMTHHTTPMONLOGINFO (SYS_ID, LOG_ID);


CREATE TABLE COMTHDBMNTRNGLOGINFO
(
	DATA_SOURC_NM         VARCHAR(60) NOT NULL,
	SERVER_NM             VARCHAR(60) NULL,
	DBMS_KND              VARCHAR(2) NULL,
	CECK_SQL              VARCHAR(250) NULL,
	MNGR_NM               VARCHAR(60) NULL,
	MNGR_EMAIL_ADRES      VARCHAR(50) NULL,
	MNTRNG_STTUS          CHAR(2) NULL,
	LOG_INFO              VARCHAR(2000) NULL,
	CREAT_DT              DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NOT NULL,
	LAST_UPDT_PNTTM       DATETIME NOT NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LOG_ID                CHAR(20) NOT NULL,
	 PRIMARY KEY (LOG_ID)
);
CREATE UNIQUE INDEX COMTHDBMNTRNGLOGINFO_PK ON COMTHDBMNTRNGLOGINFO (LOG_ID);


CREATE TABLE COMTNDAMMAPTEAM
(
	ORGNZT_ID             CHAR(20) NOT NULL,
	ORGNZT_NM             VARCHAR(20) NULL,
	CL_DE                 CHAR(20) NULL,
	KNWLDG_URL            VARCHAR(255) NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	 PRIMARY KEY (ORGNZT_ID)
);
CREATE UNIQUE INDEX COMTNDAMMAPTEAM_PK ON COMTNDAMMAPTEAM (ORGNZT_ID);



CREATE TABLE COMTNINDVDLPGECNTNTS
(
	CNTNTS_ID             VARCHAR(20) NOT NULL,
	CNTNTS_NM             VARCHAR(100) NOT NULL,
	CNTC_URL              VARCHAR(255) NOT NULL,
	CNTNTS_USE_AT         CHAR(1) NOT NULL,
	CNTNTS_LINK_URL       VARCHAR(1000) NULL,
	CNTNTS_DC             VARCHAR(250) NULL,
	 PRIMARY KEY (CNTNTS_ID)
);
CREATE UNIQUE INDEX COMTNINDVDLPGECNTNTS_PK ON COMTNINDVDLPGECNTNTS (CNTNTS_ID);


CREATE TABLE COMTNINDVDLPGEESTBS
(
	EMPLYR_ID             VARCHAR(20) NOT NULL,
	UPEND_IMAGE           VARCHAR(1024) NULL,
	TITLEBAR_COLOR        CHAR(7) NULL,
	ALGN_MTHD             CHAR(1) NULL,
	ALGN_CO               NUMERIC(10) NULL,
	 PRIMARY KEY (EMPLYR_ID)
);
CREATE UNIQUE INDEX COMTNINDVDLPGEESTBS_PK ON COMTNINDVDLPGEESTBS (EMPLYR_ID);


CREATE TABLE COMTNCNTNTSLIST
(
	CNTNTS_ID             VARCHAR(20) NOT NULL,
	EMPLYR_ID             VARCHAR(20) NOT NULL,
	 PRIMARY KEY (CNTNTS_ID,EMPLYR_ID),
	FOREIGN KEY COMTNCNTNTSLIST_FK1 (CNTNTS_ID) REFERENCES COMTNINDVDLPGECNTNTS(CNTNTS_ID),
	FOREIGN KEY COMTNCNTNTSLIST_FK2 (EMPLYR_ID) REFERENCES COMTNINDVDLPGEESTBS(EMPLYR_ID)
);
CREATE UNIQUE INDEX COMTNCNTNTSLIST_PK ON COMTNCNTNTSLIST (CNTNTS_ID, EMPLYR_ID);
CREATE INDEX COMTNCNTNTSLIST_i01 ON COMTNCNTNTSLIST (CNTNTS_ID);
CREATE INDEX COMTNCNTNTSLIST_i02 ON COMTNCNTNTSLIST (EMPLYR_ID);



CREATE TABLE COMTNINDVDLINFOPOLICY
(
	INDVDL_INFO_POLICY_ID  CHAR(20) NOT NULL,
	INDVDL_INFO_POLICY_CN  VARCHAR(2500) NULL,
	INDVDL_INFO_POLICY_AGRE_AT  CHAR(1) NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	INDVDL_INFO_POLICY_NM  VARCHAR(255) NULL,
	 PRIMARY KEY (INDVDL_INFO_POLICY_ID)
);
CREATE UNIQUE INDEX COMTNINDVDLINFOPOLICY_PK ON COMTNINDVDLINFOPOLICY (INDVDL_INFO_POLICY_ID);




CREATE TABLE COMTNFILESYSMNTRNG
(
	FILE_SYS_ID           CHAR(20) NOT NULL,
	FILE_SYS_NM           VARCHAR(60) NOT NULL,
	FILE_SYS_MANAGE_NM    VARCHAR(255) NOT NULL,
	FILE_SYS_SIZE         NUMERIC(8) NOT NULL,
	FILE_SYS_THRHLD       NUMERIC(8) NOT NULL,
	FILE_SYS_USGQTY       NUMERIC(8) NULL,
	MNGR_NM               VARCHAR(60) NULL,
	MNGR_EMAIL_ADRES      VARCHAR(50) NULL,
	MNTRNG_STTUS          CHAR(2) NULL,
	CREAT_DT              DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	 PRIMARY KEY (FILE_SYS_ID)
);
CREATE UNIQUE INDEX COMTNFILESYSMNTRNG_PK ON COMTNFILESYSMNTRNG (FILE_SYS_ID);


CREATE TABLE COMTNFILESYSMNTRNGLOGINFO
(
	FILE_SYS_ID           CHAR(20) NOT NULL,
	FILE_SYS_NM           VARCHAR(60) NOT NULL,
	FILE_SYS_MANAGE_NM    VARCHAR(255) NOT NULL,
	FILE_SYS_SIZE         NUMERIC(8) NOT NULL,
	FILE_SYS_THRHLD       NUMERIC(8) NOT NULL,
	FILE_SYS_USGQTY       NUMERIC(8) NULL,
	MNTRNG_STTUS          CHAR(2) NULL,
	LOG_INFO              VARCHAR(2000) NULL,
	CREAT_DT              DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LOG_ID                CHAR(20) NOT NULL,
	 PRIMARY KEY (FILE_SYS_ID,LOG_ID),
	FOREIGN KEY COMTNFILESYSMNTRNGLOGINFO_FK2 (FILE_SYS_ID) REFERENCES COMTNFILESYSMNTRNG(FILE_SYS_ID)
);
CREATE UNIQUE INDEX COMTNFILESYSMNTRNGLOGINFO_PK ON COMTNFILESYSMNTRNGLOGINFO (FILE_SYS_ID, LOG_ID);


CREATE TABLE COMTNDAMKNOIFM
(
	KNWLDG_ID             CHAR(20) NOT NULL,
	KNWLDG_TY_CODE        VARCHAR(3) NULL,
	ORGNZT_ID             CHAR(20) NULL,
	EXPERT_ID             CHAR(20) NULL,
	EMPLYR_ID             VARCHAR(20) NULL,
	KNWLDG_NM             VARCHAR(60) NULL,
	KNWLDG_CN             VARCHAR(2500) NULL,
	KWRD                  VARCHAR(100) NULL,
	OTHBC_AT              CHAR(1) NULL,
	KNWLDG_EVL            CHAR(1) NULL,
	COLCT_DE              CHAR(20) NULL,
	EVL_DE                CHAR(20) NULL,
	ATCH_FILE_ID          CHAR(20) NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	DSUSE_DE              CHAR(20) NULL,
	 PRIMARY KEY (KNWLDG_ID)
);
CREATE UNIQUE INDEX COMTNDAMKNOIFM_PK ON COMTNDAMKNOIFM (KNWLDG_ID);


CREATE TABLE COMTNDAMMAPKNO
(
	KNWLDG_TY_CODE        VARCHAR(3) NOT NULL,
	ORGNZT_ID             CHAR(20) NULL,
	EXPERT_ID             CHAR(20) NULL,
	KNWLDG_TY_NM          VARCHAR(60) NULL,
	CL_DE                 CHAR(20) NULL,
	KNWLDG_URL            VARCHAR(255) NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	 PRIMARY KEY (KNWLDG_TY_CODE)
);
CREATE UNIQUE INDEX COMTNDAMMAPKNO_PK ON COMTNDAMMAPKNO (KNWLDG_TY_CODE);


CREATE TABLE COMTNDAMPRO
(
	EXPERT_ID             CHAR(20) NOT NULL,
	KNWLDG_TY_CODE        VARCHAR(3) NOT NULL,
	EXPERT_GRAD           CHAR(1) NOT NULL,
	EXPERT_CONFM_DE       CHAR(20) NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	EXPERT_DC             VARCHAR(2000) NULL,
	 PRIMARY KEY (EXPERT_ID,KNWLDG_TY_CODE,EXPERT_GRAD),
	FOREIGN KEY COMTNDAMPRO_FK1 (KNWLDG_TY_CODE) REFERENCES COMTNDAMMAPKNO(KNWLDG_TY_CODE)
);
CREATE UNIQUE INDEX COMTNDAMPRO_PK ON COMTNDAMPRO
(
	EXPERT_ID,
	KNWLDG_TY_CODE,
	EXPERT_GRAD
);


CREATE TABLE COMTNDBMNTRNG
(
	DATA_SOURC_NM         VARCHAR(60) NOT NULL,
	SERVER_NM             VARCHAR(60) NULL,
	DBMS_KND              VARCHAR(2) NULL,
	CECK_SQL              VARCHAR(250) NULL,
	MNGR_NM               VARCHAR(60) NULL,
	MNGR_EMAIL_ADRES      VARCHAR(50) NULL,
	MNTRNG_STTUS          CHAR(2) NULL,
	CREAT_DT              DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NOT NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NOT NULL,
	 PRIMARY KEY (DATA_SOURC_NM)
);
CREATE UNIQUE INDEX COMTNDBMNTRNG_PK ON COMTNDBMNTRNG (DATA_SOURC_NM);


CREATE TABLE COMTNTRSMRCVMNTRNG
(
	CNTC_ID               CHAR(8) NOT NULL,
	TEST_CLASS_NM         VARCHAR(255) NULL,
	MNGR_NM               VARCHAR(60) NULL,
	MNGR_EMAIL_ADRES      VARCHAR(50) NULL,
	MNTRNG_STTUS          CHAR(2) NULL,
	CREAT_DT              DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NOT NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NOT NULL,
	 PRIMARY KEY (CNTC_ID)
);
CREATE UNIQUE INDEX COMTNTRSMRCVMNTRNG_PK ON COMTNTRSMRCVMNTRNG (CNTC_ID);




CREATE TABLE COMTNNTWRKSVCMNTRNG
(
	SYS_IP                VARCHAR(23) NOT NULL,
	SYS_PORT              NUMERIC(5) NOT NULL,
	SYS_NM                VARCHAR(255) NOT NULL,
	MNGR_NM               VARCHAR(60) NULL,
	MNGR_EMAIL_ADRES      VARCHAR(50) NULL,
	MNTRNG_STTUS          CHAR(2) NULL,
	CREAT_DT              DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM       DATETIME NOT NULL,
	 PRIMARY KEY (SYS_IP,SYS_PORT)
);
CREATE UNIQUE INDEX COMTNNTWRKSVCMNTRNG_PK ON COMTNNTWRKSVCMNTRNG (SYS_IP, SYS_PORT);


CREATE TABLE COMTNNTWRKSVCMNTRNGLOGINFO
(
	SYS_IP                VARCHAR(23) NOT NULL,
	SYS_PORT              NUMERIC(5) NOT NULL,
	SYS_NM                VARCHAR(255) NOT NULL,
	MNTRNG_STTUS          CHAR(2) NULL,
	LOG_INFO              VARCHAR(2000) NULL,
	CREAT_DT              DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM       DATETIME NOT NULL,
	LOG_ID                CHAR(20) NOT NULL,
	 PRIMARY KEY (SYS_IP,SYS_PORT,LOG_ID),
	FOREIGN KEY COMTNNTWRKSVCMNTRNGLOGINFO_FK2 (SYS_IP,SYS_PORT) REFERENCES COMTNNTWRKSVCMNTRNG(SYS_IP,SYS_PORT)
);
CREATE UNIQUE INDEX COMTNNTWRKSVCMNTRNGLOGINFO_PK ON COMTNNTWRKSVCMNTRNGLOGINFO (SYS_IP, SYS_PORT, LOG_ID);


CREATE TABLE COMTNSERVEREQPMNINFO
(
	SERVER_EQPMN_ID       VARCHAR(20) NOT NULL,
	SERVER_EQPMN_NM       VARCHAR(60) NULL,
	SERVER_EQPMN_IP       VARCHAR(23) NULL,
	SERVER_EQPMN_MNGR     VARCHAR(60) NULL,
	MNGR_EMAIL_ADRES      VARCHAR(50) NULL,
	OPERSYSM_INFO         VARCHAR(2000) NULL,
	CPU_INFO              VARCHAR(2000) NULL,
	MORY_INFO             VARCHAR(2000) NULL,
	HDDISK                CHAR(18) NULL,
	ETC_INFO              VARCHAR(250) NULL,
	RGSDE                 DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	 PRIMARY KEY (SERVER_EQPMN_ID)
);
CREATE UNIQUE INDEX COMTNSERVEREQPMNINFO_PK ON COMTNSERVEREQPMNINFO (SERVER_EQPMN_ID);


CREATE TABLE COMTNSYNCHRNSERVERINFO
(
	SERVER_ID             CHAR(20) NOT NULL,
	SERVER_NM             VARCHAR(60) NULL,
	SERVER_IP             VARCHAR(23) NULL,
	SERVER_PORT           VARCHAR(10) NULL,
	FTP_ID                VARCHAR(20) NULL,
	FTP_PASSWORD          VARCHAR(20) NULL,
	SYNCHRN_LC            VARCHAR(255) NULL,
	REFLCT_AT             CHAR(1) NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	 PRIMARY KEY (SERVER_ID)
);
CREATE UNIQUE INDEX COMTNSYNCHRNSERVERINFO_PK ON COMTNSYNCHRNSERVERINFO (SERVER_ID);


CREATE TABLE COMTNSERVERINFO
(
	SERVER_ID             CHAR(20) NOT NULL,
	SERVER_NM             VARCHAR(60) NULL,
	SERVER_KND            CHAR(2) NULL,
	RGSDE                 DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	 PRIMARY KEY (SERVER_ID)
);
CREATE UNIQUE INDEX COMTNSERVERINFO_PK ON COMTNSERVERINFO (SERVER_ID);


CREATE TABLE COMTNSERVEREQPMNRELATE
(
	SERVER_EQPMN_ID       VARCHAR(20) NOT NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	SERVER_ID             CHAR(20) NOT NULL,
	 PRIMARY KEY (SERVER_EQPMN_ID,SERVER_ID),
	FOREIGN KEY COMTNSERVEREQPMNRELATE_FK2 (SERVER_EQPMN_ID) REFERENCES COMTNSERVEREQPMNINFO(SERVER_EQPMN_ID),
	FOREIGN KEY COMTNSERVEREQPMNRELATE_FK1 (SERVER_ID) REFERENCES COMTNSERVERINFO(SERVER_ID)
);
CREATE UNIQUE INDEX COMTNSERVEREQPMNRELATE_PK ON COMTNSERVEREQPMNRELATE (SERVER_EQPMN_ID, SERVER_ID);


CREATE TABLE COMTNSERVERRESRCELOGINFO
(
	SERVER_EQPMN_ID       VARCHAR(20) NOT NULL,
	CPU_USE_RT            NUMERIC(3) NULL,
	MORY_USE_RT           NUMERIC(3) NULL,
	SVC_STTUS             CHAR(2) NULL,
	LOG_INFO              VARCHAR(2000) NULL,
	CREAT_DT              DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	SERVER_ID             CHAR(20) NOT NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LOG_ID                CHAR(20) NOT NULL,
	 PRIMARY KEY (SERVER_EQPMN_ID,SERVER_ID,LOG_ID),
	FOREIGN KEY COMTNSERVERRESRCELOGINFO_FK1 (SERVER_EQPMN_ID,SERVER_ID) REFERENCES COMTNSERVEREQPMNRELATE(SERVER_EQPMN_ID,SERVER_ID)
);
CREATE UNIQUE INDEX COMTNSERVERRESRCELOGINFO_PK ON COMTNSERVERRESRCELOGINFO
(
	SERVER_EQPMN_ID,
	SERVER_ID,
	LOG_ID
);



CREATE TABLE IMGTEMP
(
	ORGNZT_CODE           VARCHAR(10) NOT NULL,
	ERNCSL_SE             VARCHAR(2) NOT NULL,
	IMAGE_INFO            BLOB NOT NULL,
	IMAGE_TY              VARCHAR(20) NULL,
	 PRIMARY KEY (ORGNZT_CODE,ERNCSL_SE)
);
CREATE UNIQUE INDEX IMGTEMP_PK ON IMGTEMP (ORGNZT_CODE, ERNCSL_SE);


CREATE TABLE IDS
(
	IDGEN_TABLE_NM        VARCHAR(20) NOT NULL,
	IDGEN_NEXT_ID         NUMERIC(30) NOT NULL,
	 PRIMARY KEY (IDGEN_TABLE_NM)
);
CREATE UNIQUE INDEX IDS_PK ON IDS (IDGEN_TABLE_NM);


CREATE TABLE COMTNTWITTER
(
	USER_ID               VARCHAR(20) NOT NULL,
	CNSMR_KEY             VARCHAR(50) NOT NULL,
	CNSMR_SECRET          VARCHAR(50) NOT NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	 PRIMARY KEY (USER_ID)
);
CREATE UNIQUE INDEX COMTNTWITTER_PK ON COMTNTWITTER (USER_ID);


CREATE TABLE COMTNWIKIBKMK
(
	WIKI_BKMK_ID          CHAR(20) NOT NULL,
	USER_ID               VARCHAR(20) NOT NULL,
	WIKI_BKMK_NM          VARCHAR(1000) NOT NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	 PRIMARY KEY (WIKI_BKMK_ID,USER_ID)
);
CREATE UNIQUE INDEX COMTNWIKIBKMK_PK ON COMTNWIKIBKMK (WIKI_BKMK_ID, USER_ID);





CREATE TABLE COMTNPROCESSMON
(
	PROCS_ID              CHAR(20) NOT NULL,
	PROCS_NM              VARCHAR(60) NULL,
	PROCS_STTUS           VARCHAR(3) NULL,
	CREAT_DT              DATETIME NULL,
	MNGR_NM               VARCHAR(60) NULL,
	MNGR_EMAIL_ADRES      VARCHAR(50) NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	 PRIMARY KEY (PROCS_ID)
);
CREATE UNIQUE INDEX COMTNPROCESSMON_PK ON COMTNPROCESSMON (PROCS_ID);


CREATE TABLE COMTNPROCESSMONLOGINFO
(
	PROCS_ID              CHAR(20) NOT NULL,
	PROCS_NM              VARCHAR(60) NULL,
	PROCS_STTUS           VARCHAR(3) NULL,
	CREAT_DT              DATETIME NULL,
	LOG_INFO              VARCHAR(2000) NULL,
	MNGR_NM               VARCHAR(60) NULL,
	MNGR_EMAIL_ADRES      VARCHAR(50) NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LOG_ID                CHAR(20) NOT NULL,
	 PRIMARY KEY (PROCS_ID,LOG_ID),
	FOREIGN KEY COMTNPROCESSMONLOGINFO_FK2 (PROCS_ID) REFERENCES COMTNPROCESSMON(PROCS_ID)
);
CREATE UNIQUE INDEX COMTNPROCESSMONLOGINFO_PK ON COMTNPROCESSMONLOGINFO (PROCS_ID, LOG_ID);



CREATE TABLE J_ATTACHFILE 
(
	FILE_ID VARCHAR(13) NOT NULL,
	FILE_SEQ INT NOT NULL,
	FILE_NAME VARCHAR(100) NOT NULL,
	FILE_SIZE INT,
	FILE_MASK VARCHAR(100),
	DOWNLOAD_COUNT INT,
	DOWNLOAD_EXPIRE_DATE VARCHAR(8),
	DOWNLOAD_LIMIT_COUNT INT,
	REG_DATE DATETIME,
	DELETE_YN VARCHAR(1),
	PRIMARY KEY (FILE_ID, FILE_SEQ)
);
CREATE UNIQUE INDEX J_ATTACHFILE_PK ON J_ATTACHFILE (FILE_ID, FILE_SEQ);


CREATE TABLE COMTNROUGHMAP (
    ROUGHMAP_ID       VARCHAR(75)   NOT NULL,
    ROUGHMAPSJ        VARCHAR(75)   NOT NULL,
    ROUGHMAPADDRESS   VARCHAR(200)  NULL,
    LA                VARCHAR(48)   NULL,
    LO                VARCHAR(48)   NULL,
    MARKERLA          VARCHAR(48)   NULL,
    MARKERLO          VARCHAR(48)   NULL,
    INFOWINDOW        VARCHAR(20)   NULL,
    ZOOMLEVEL         VARCHAR(10)   NULL,
    FRST_REGIST_PNTTM DATETIME          NULL,
    FRST_REGISTER_ID  VARCHAR(20)   NULL,
    LAST_UPDT_PNTTM   DATETIME          NULL,
    LAST_UPDUSR_ID    VARCHAR(20)   NULL
);


CREATE TABLE COMTNPRIVACYLOG
(
	REQUST_ID            VARCHAR(20) NOT NULL,
	INQIRE_DT            DATETIME NOT NULL,
	SRVC_NM              VARCHAR(500) NULL,
	INQIRE_INFO          VARCHAR(100) NULL,
	RQESTER_ID           VARCHAR(20) NULL,
	RQESTER_IP           VARCHAR(23) NULL,
	PRIMARY KEY (REQUST_ID)
);
CREATE UNIQUE INDEX COMTNPRIVACYLOG_PK ON COMTNPRIVACYLOG (REQUST_ID);


CREATE TABLE COMTNCOMMUTE (
    WRKTM_ID           CHAR(20) NOT NULL,
    EMPLYR_ID          VARCHAR(20) NOT NULL,
    ORGNZT_ID          VARCHAR(20) NULL,
    WRKT_DT            VARCHAR(10) NOT NULL, 
    WRK_START_TIME     VARCHAR(14) NULL, 
    WRK_END_TIME       VARCHAR(14) NULL, 
    WRK_HOURS          CHAR(2) NULL, 
    OVTMWRK_HOURS      CHAR(2) NULL,
    WRK_START_STATUS   VARCHAR(10) NULL, 
    WRK_END_STATUS     VARCHAR(10) NULL, 
    RM                 VARCHAR(100) NULL,
    FRST_REGISTER_ID   VARCHAR(20) NULL,
    FRST_REGIST_PNTTM  DATETIME NULL,
    LAST_UPDUSR_ID     VARCHAR(20) NULL,
    LAST_UPDT_PNTTM    DATETIME NULL,
 	PRIMARY KEY (EMPLYR_ID, WRKT_DT)
);


CREATE TABLE COMTNBLOG
(
	BLOG_ID             CHAR(20)  NOT NULL ,
	BLOG_NM             VARCHAR(255)  NOT NULL ,
	BLOG_INTRCN         VARCHAR(2400)  NULL ,
	USE_AT              CHAR(1)  NOT NULL ,
	REGIST_SE_CODE      CHAR(6)  NULL ,
	TMPLAT_ID           CHAR(20)  NULL ,
	FRST_REGIST_PNTTM   DATETIME  NOT NULL ,
	FRST_REGISTER_ID    VARCHAR(20)  NOT NULL ,
	LAST_UPDT_PNTTM     DATETIME  NULL ,
	LAST_UPDUSR_ID      VARCHAR(20)  NULL ,
	BBS_ID 			CHAR(20) DEFAULT NULL,
  	BLOG_AT 			CHAR(2) DEFAULT NULL,
	PRIMARY KEY (BLOG_ID)
);


CREATE TABLE COMTNBLOGUSER
(
	BLOG_ID             CHAR(20) NOT NULL,
	EMPLYR_ID             VARCHAR(20) NOT NULL,
	MNGR_AT               CHAR(1) NOT NULL,
	MBER_STTUS			VARCHAR(15) NULL,
	SBSCRB_DE             DATETIME NULL,
	SECSN_DE              CHAR(20) NULL,
	USE_AT                CHAR(1) NULL,
	FRST_REGIST_PNTTM     DATETIME NOT NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	PRIMARY KEY (BLOG_ID,EMPLYR_ID),
	FOREIGN KEY COMTNBLOGUSER_FK1 (BLOG_ID) REFERENCES COMTNBLOG(BLOG_ID)
);
