COMMENT ON TABLE COMTECOPSEQ IS 'COMTECOPSEQ'; 
COMMENT ON COLUMN COMTECOPSEQ.TABLE_NAME IS '테이블명'; 
COMMENT ON COLUMN COMTECOPSEQ.NEXT_ID IS '다음아이디'; 


COMMENT ON TABLE COMTNFILE IS '파일속성'; 
COMMENT ON COLUMN COMTNFILE.ATCH_FILE_ID IS '첨부파일ID'; 
COMMENT ON COLUMN COMTNFILE.CREAT_DT IS '생성일시'; 
COMMENT ON COLUMN COMTNFILE.USE_AT IS '사용여부'; 
 

COMMENT ON TABLE COMTNFILEDETAIL IS '파일상세정보'; 
COMMENT ON COLUMN COMTNFILEDETAIL.ATCH_FILE_ID IS '첨부파일ID'; 
COMMENT ON COLUMN COMTNFILEDETAIL.FILE_SN IS '파일순번'; 
COMMENT ON COLUMN COMTNFILEDETAIL.FILE_STRE_COURS IS '파일저장경로'; 
COMMENT ON COLUMN COMTNFILEDETAIL.STRE_FILE_NM IS '저장파일명'; 
COMMENT ON COLUMN COMTNFILEDETAIL.ORIGNL_FILE_NM IS '원파일명'; 
COMMENT ON COLUMN COMTNFILEDETAIL.FILE_EXTSN IS '파일확장자'; 
COMMENT ON COLUMN COMTNFILEDETAIL.FILE_CN IS '파일내용'; 
COMMENT ON COLUMN COMTNFILEDETAIL.FILE_SIZE IS '파일크기'; 
 

COMMENT ON TABLE COMTNLOGINPOLICY IS '로그인정책'; 
COMMENT ON COLUMN COMTNLOGINPOLICY.EMPLYR_ID IS '업무사용자ID'; 
COMMENT ON COLUMN COMTNLOGINPOLICY.IP_INFO IS 'IP정보'; 
COMMENT ON COLUMN COMTNLOGINPOLICY.DPLCT_PERM_AT IS '중복허용여부'; 
COMMENT ON COLUMN COMTNLOGINPOLICY.LMTT_AT IS '제한여부'; 
COMMENT ON COLUMN COMTNLOGINPOLICY.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNLOGINPOLICY.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNLOGINPOLICY.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNLOGINPOLICY.LAST_UPDT_PNTTM IS '최종수정시점'; 
 

COMMENT ON TABLE COMTNORGNZTINFO IS '조직정보'; 
COMMENT ON COLUMN COMTNORGNZTINFO.ORGNZT_ID IS '조직ID'; 
COMMENT ON COLUMN COMTNORGNZTINFO.ORGNZT_NM IS '조직명'; 
COMMENT ON COLUMN COMTNORGNZTINFO.ORGNZT_DC IS '조직설명'; 


COMMENT ON TABLE COMTNAUTHORGROUPINFO IS '권한그룹정보'; 
COMMENT ON COLUMN COMTNAUTHORGROUPINFO.GROUP_ID IS '그룹ID'; 
COMMENT ON COLUMN COMTNAUTHORGROUPINFO.GROUP_NM IS '그룹명'; 
COMMENT ON COLUMN COMTNAUTHORGROUPINFO.GROUP_CREAT_DE IS '그룹생성일'; 
COMMENT ON COLUMN COMTNAUTHORGROUPINFO.GROUP_DC IS '그룹설명'; 
 

COMMENT ON TABLE COMTNEMPLYRINFO IS '업무사용자정보'; 
COMMENT ON COLUMN COMTNEMPLYRINFO.EMPLYR_ID IS '업무사용자ID'; 
COMMENT ON COLUMN COMTNEMPLYRINFO.ORGNZT_ID IS '조직ID'; 
COMMENT ON COLUMN COMTNEMPLYRINFO.USER_NM IS '사용자명'; 
COMMENT ON COLUMN COMTNEMPLYRINFO.PASSWORD IS '비밀번호'; 
COMMENT ON COLUMN COMTNEMPLYRINFO.EMPL_NO IS '사원번호'; 
COMMENT ON COLUMN COMTNEMPLYRINFO.IHIDNUM IS '주민등록번호'; 
COMMENT ON COLUMN COMTNEMPLYRINFO.SEXDSTN_CODE IS '성별코드'; 
COMMENT ON COLUMN COMTNEMPLYRINFO.BRTHDY IS '생일'; 
COMMENT ON COLUMN COMTNEMPLYRINFO.FXNUM IS '팩스번호'; 
COMMENT ON COLUMN COMTNEMPLYRINFO.HOUSE_ADRES IS '주택주소'; 
COMMENT ON COLUMN COMTNEMPLYRINFO.PASSWORD_HINT IS '비밀번호힌트'; 
COMMENT ON COLUMN COMTNEMPLYRINFO.PASSWORD_CNSR IS '비밀번호정답'; 
COMMENT ON COLUMN COMTNEMPLYRINFO.HOUSE_END_TELNO IS '주택끝전화번호'; 
COMMENT ON COLUMN COMTNEMPLYRINFO.AREA_NO IS '지역번호'; 
COMMENT ON COLUMN COMTNEMPLYRINFO.DETAIL_ADRES IS '상세주소'; 
COMMENT ON COLUMN COMTNEMPLYRINFO.ZIP IS '우편번호'; 
COMMENT ON COLUMN COMTNEMPLYRINFO.OFFM_TELNO IS '사무실전화번호'; 
COMMENT ON COLUMN COMTNEMPLYRINFO.MBTLNUM IS '이동전화번호'; 
COMMENT ON COLUMN COMTNEMPLYRINFO.EMAIL_ADRES IS '이메일주소'; 
COMMENT ON COLUMN COMTNEMPLYRINFO.OFCPS_NM IS '직위명'; 
COMMENT ON COLUMN COMTNEMPLYRINFO.HOUSE_MIDDLE_TELNO IS '주택중간전화번호'; 
COMMENT ON COLUMN COMTNEMPLYRINFO.GROUP_ID IS '그룹ID'; 
COMMENT ON COLUMN COMTNEMPLYRINFO.PSTINST_CODE IS '소속기관코드'; 
COMMENT ON COLUMN COMTNEMPLYRINFO.EMPLYR_STTUS_CODE IS '사용자상태코드'; 
COMMENT ON COLUMN COMTNEMPLYRINFO.ESNTL_ID IS '고유ID'; 
COMMENT ON COLUMN COMTNEMPLYRINFO.CRTFC_DN_VALUE IS '인증DN값'; 
COMMENT ON COLUMN COMTNEMPLYRINFO.SBSCRB_DE IS '가입일자'; 
COMMENT ON COLUMN COMTNEMPLYRINFO.LOCK_AT IS '잠금여부';
COMMENT ON COLUMN COMTNEMPLYRINFO.LOCK_CNT IS '잠금회수';
COMMENT ON COLUMN COMTNEMPLYRINFO.LOCK_LAST_PNTTM IS '잠금최종시점';


COMMENT ON TABLE COMTHEMPLYRINFOCHANGEDTLS IS '업무사용자정보변경내역'; 
COMMENT ON COLUMN COMTHEMPLYRINFOCHANGEDTLS.EMPLYR_ID IS '업무사용자ID'; 
COMMENT ON COLUMN COMTHEMPLYRINFOCHANGEDTLS.CHANGE_DE IS '변경일'; 
COMMENT ON COLUMN COMTHEMPLYRINFOCHANGEDTLS.ORGNZT_ID IS '조직ID'; 
COMMENT ON COLUMN COMTHEMPLYRINFOCHANGEDTLS.GROUP_ID IS '그룹ID'; 
COMMENT ON COLUMN COMTHEMPLYRINFOCHANGEDTLS.EMPL_NO IS '사원번호'; 
COMMENT ON COLUMN COMTHEMPLYRINFOCHANGEDTLS.SEXDSTN_CODE IS '성별코드'; 
COMMENT ON COLUMN COMTHEMPLYRINFOCHANGEDTLS.BRTHDY IS '생일'; 
COMMENT ON COLUMN COMTHEMPLYRINFOCHANGEDTLS.FXNUM IS '팩스번호'; 
COMMENT ON COLUMN COMTHEMPLYRINFOCHANGEDTLS.HOUSE_ADRES IS '주택주소'; 
COMMENT ON COLUMN COMTHEMPLYRINFOCHANGEDTLS.HOUSE_END_TELNO IS '주택끝전화번호'; 
COMMENT ON COLUMN COMTHEMPLYRINFOCHANGEDTLS.AREA_NO IS '지역번호'; 
COMMENT ON COLUMN COMTHEMPLYRINFOCHANGEDTLS.DETAIL_ADRES IS '상세주소'; 
COMMENT ON COLUMN COMTHEMPLYRINFOCHANGEDTLS.ZIP IS '우편번호'; 
COMMENT ON COLUMN COMTHEMPLYRINFOCHANGEDTLS.OFFM_TELNO IS '사무실전화번호'; 
COMMENT ON COLUMN COMTHEMPLYRINFOCHANGEDTLS.MBTLNUM IS '이동전화번호'; 
COMMENT ON COLUMN COMTHEMPLYRINFOCHANGEDTLS.EMAIL_ADRES IS '이메일주소'; 
COMMENT ON COLUMN COMTHEMPLYRINFOCHANGEDTLS.HOUSE_MIDDLE_TELNO IS '주택중간전화번호'; 
COMMENT ON COLUMN COMTHEMPLYRINFOCHANGEDTLS.PSTINST_CODE IS '소속기관코드'; 
COMMENT ON COLUMN COMTHEMPLYRINFOCHANGEDTLS.EMPLYR_STTUS_CODE IS '사용자상태코드'; 
COMMENT ON COLUMN COMTHEMPLYRINFOCHANGEDTLS.ESNTL_ID IS '고유ID'; 


COMMENT ON TABLE COMTNENTRPRSMBER IS '기업회원'; 
COMMENT ON COLUMN COMTNENTRPRSMBER.ENTRPRS_MBER_ID IS '기업회원ID'; 
COMMENT ON COLUMN COMTNENTRPRSMBER.ENTRPRS_SE_CODE IS '기업구분코드'; 
COMMENT ON COLUMN COMTNENTRPRSMBER.BIZRNO IS '사업자등록번호'; 
COMMENT ON COLUMN COMTNENTRPRSMBER.JURIRNO IS '법인등록번호'; 
COMMENT ON COLUMN COMTNENTRPRSMBER.CMPNY_NM IS '회사명'; 
COMMENT ON COLUMN COMTNENTRPRSMBER.CXFC IS '대표이사'; 
COMMENT ON COLUMN COMTNENTRPRSMBER.ZIP IS '우편번호'; 
COMMENT ON COLUMN COMTNENTRPRSMBER.ADRES IS '주소'; 
COMMENT ON COLUMN COMTNENTRPRSMBER.ENTRPRS_MIDDLE_TELNO IS '기업중간전화번호'; 
COMMENT ON COLUMN COMTNENTRPRSMBER.FXNUM IS '팩스번호'; 
COMMENT ON COLUMN COMTNENTRPRSMBER.INDUTY_CODE IS '업종코드'; 
COMMENT ON COLUMN COMTNENTRPRSMBER.APPLCNT_NM IS '신청인명'; 
COMMENT ON COLUMN COMTNENTRPRSMBER.APPLCNT_IHIDNUM IS '신청인주민등록번호'; 
COMMENT ON COLUMN COMTNENTRPRSMBER.SBSCRB_DE IS '가입일자'; 
COMMENT ON COLUMN COMTNENTRPRSMBER.ENTRPRS_MBER_STTUS IS '기업회원상태'; 
COMMENT ON COLUMN COMTNENTRPRSMBER.ENTRPRS_MBER_PASSWORD IS '기업회원비밀번호'; 
COMMENT ON COLUMN COMTNENTRPRSMBER.ENTRPRS_MBER_PASSWORD_HINT IS '기업회원비밀번호힌트'; 
COMMENT ON COLUMN COMTNENTRPRSMBER.ENTRPRS_MBER_PASSWORD_CNSR IS '기업회원비밀번호정답'; 
COMMENT ON COLUMN COMTNENTRPRSMBER.GROUP_ID IS '그룹ID'; 
COMMENT ON COLUMN COMTNENTRPRSMBER.DETAIL_ADRES IS '상세주소'; 
COMMENT ON COLUMN COMTNENTRPRSMBER.ENTRPRS_END_TELNO IS '기업끝전화번호'; 
COMMENT ON COLUMN COMTNENTRPRSMBER.AREA_NO IS '지역번호'; 
COMMENT ON COLUMN COMTNENTRPRSMBER.APPLCNT_EMAIL_ADRES IS '신청자이메일주소'; 
COMMENT ON COLUMN COMTNENTRPRSMBER.ESNTL_ID IS '고유ID'; 
COMMENT ON COLUMN COMTNENTRPRSMBER.LOCK_AT IS '잠금여부';
COMMENT ON COLUMN COMTNENTRPRSMBER.LOCK_CNT IS '잠금회수';
COMMENT ON COLUMN COMTNENTRPRSMBER.LOCK_LAST_PNTTM IS '잠금최종시점';


COMMENT ON TABLE COMTNGNRLMBER IS '일반회원'; 
COMMENT ON COLUMN COMTNGNRLMBER.MBER_ID IS '회원ID'; 
COMMENT ON COLUMN COMTNGNRLMBER.PASSWORD IS '비밀번호'; 
COMMENT ON COLUMN COMTNGNRLMBER.PASSWORD_HINT IS '비밀번호힌트'; 
COMMENT ON COLUMN COMTNGNRLMBER.PASSWORD_CNSR IS '비밀번호정답'; 
COMMENT ON COLUMN COMTNGNRLMBER.IHIDNUM IS '주민등록번호'; 
COMMENT ON COLUMN COMTNGNRLMBER.MBER_NM IS '회원명'; 
COMMENT ON COLUMN COMTNGNRLMBER.ZIP IS '우편번호'; 
COMMENT ON COLUMN COMTNGNRLMBER.ADRES IS '주소'; 
COMMENT ON COLUMN COMTNGNRLMBER.AREA_NO IS '지역번호'; 
COMMENT ON COLUMN COMTNGNRLMBER.MBER_STTUS IS '회원상태'; 
COMMENT ON COLUMN COMTNGNRLMBER.DETAIL_ADRES IS '상세주소'; 
COMMENT ON COLUMN COMTNGNRLMBER.END_TELNO IS '끝전화번호'; 
COMMENT ON COLUMN COMTNGNRLMBER.MBTLNUM IS '이동전화번호'; 
COMMENT ON COLUMN COMTNGNRLMBER.GROUP_ID IS '그룹ID'; 
COMMENT ON COLUMN COMTNGNRLMBER.MBER_FXNUM IS '회원팩스번호'; 
COMMENT ON COLUMN COMTNGNRLMBER.MBER_EMAIL_ADRES IS '회원이메일주소'; 
COMMENT ON COLUMN COMTNGNRLMBER.MIDDLE_TELNO IS '중간전화번호'; 
COMMENT ON COLUMN COMTNGNRLMBER.SBSCRB_DE IS '가입일자'; 
COMMENT ON COLUMN COMTNGNRLMBER.SEXDSTN_CODE IS '성별코드'; 
COMMENT ON COLUMN COMTNGNRLMBER.ESNTL_ID IS '고유ID'; 
COMMENT ON COLUMN COMTNGNRLMBER.LOCK_AT IS '잠금여부';
COMMENT ON COLUMN COMTNGNRLMBER.LOCK_CNT IS '잠금회수';
COMMENT ON COLUMN COMTNGNRLMBER.LOCK_LAST_PNTTM IS '잠금최종시점';
 

COMMENT ON TABLE COMTNAUTHORINFO IS '권한정보'; 
COMMENT ON COLUMN COMTNAUTHORINFO.AUTHOR_CODE IS '권한코드'; 
COMMENT ON COLUMN COMTNAUTHORINFO.AUTHOR_NM IS '권한명'; 
COMMENT ON COLUMN COMTNAUTHORINFO.AUTHOR_DC IS '권한설명'; 
COMMENT ON COLUMN COMTNAUTHORINFO.AUTHOR_CREAT_DE IS '권한생성일'; 


COMMENT ON TABLE COMTNEMPLYRSCRTYESTBS IS '사용자보안설정'; 
COMMENT ON COLUMN COMTNEMPLYRSCRTYESTBS.SCRTY_DTRMN_TRGET_ID IS '보안설정대상ID'; 
COMMENT ON COLUMN COMTNEMPLYRSCRTYESTBS.MBER_TY_CODE IS '회원유형코드'; 
COMMENT ON COLUMN COMTNEMPLYRSCRTYESTBS.AUTHOR_CODE IS '권한코드'; 


COMMENT ON TABLE COMTNROLES_HIERARCHY IS '롤 계층구조'; 
COMMENT ON COLUMN COMTNROLES_HIERARCHY.PARNTS_ROLE IS '부모롤'; 
COMMENT ON COLUMN COMTNROLES_HIERARCHY.CHLDRN_ROLE IS '자식롤'; 


COMMENT ON TABLE COMTNROLEINFO IS '롤정보'; 
COMMENT ON COLUMN COMTNROLEINFO.ROLE_CODE IS '롤코드'; 
COMMENT ON COLUMN COMTNROLEINFO.ROLE_NM IS '롤명'; 
COMMENT ON COLUMN COMTNROLEINFO.ROLE_PTTRN IS '롤패턴'; 
COMMENT ON COLUMN COMTNROLEINFO.ROLE_DC IS '롤설명'; 
COMMENT ON COLUMN COMTNROLEINFO.ROLE_TY IS '롤유형'; 
COMMENT ON COLUMN COMTNROLEINFO.ROLE_SORT IS '롤정렬'; 
COMMENT ON COLUMN COMTNROLEINFO.ROLE_CREAT_DE IS '롤생성일'; 


COMMENT ON TABLE COMTNAUTHORROLERELATE IS '권한롤관계'; 
COMMENT ON COLUMN COMTNAUTHORROLERELATE.AUTHOR_CODE IS '권한코드'; 
COMMENT ON COLUMN COMTNAUTHORROLERELATE.ROLE_CODE IS '롤코드'; 
COMMENT ON COLUMN COMTNAUTHORROLERELATE.CREAT_DT IS '생성일시'; 


COMMENT ON TABLE COMTNBBSMASTER IS '게시판마스터'; 
COMMENT ON COLUMN COMTNBBSMASTER.BBS_ID IS '게시판ID'; 
COMMENT ON COLUMN COMTNBBSMASTER.BBS_NM IS '게시판명'; 
COMMENT ON COLUMN COMTNBBSMASTER.BBS_INTRCN IS '게시판소개'; 
COMMENT ON COLUMN COMTNBBSMASTER.BBS_TY_CODE IS '게시판유형코드'; 
COMMENT ON COLUMN COMTNBBSMASTER.REPLY_POSBL_AT IS '답장가능여부'; 
COMMENT ON COLUMN COMTNBBSMASTER.FILE_ATCH_POSBL_AT IS '파일첨부가능여부'; 
COMMENT ON COLUMN COMTNBBSMASTER.ATCH_POSBL_FILE_NUMBER IS '첨부가능파일숫자'; 
COMMENT ON COLUMN COMTNBBSMASTER.ATCH_POSBL_FILE_SIZE IS '첨부가능파일사이즈'; 
COMMENT ON COLUMN COMTNBBSMASTER.USE_AT IS '사용여부'; 
COMMENT ON COLUMN COMTNBBSMASTER.TMPLAT_ID IS '템플릿ID'; 
COMMENT ON COLUMN COMTNBBSMASTER.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNBBSMASTER.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNBBSMASTER.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNBBSMASTER.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN COMTNBBSMASTER.BLOG_AT IS '블로그 여부';
COMMENT ON COLUMN COMTNBBSMASTER.BLOG_ID IS '블로그 ID';
COMMENT ON COLUMN COMTNBBSMASTER.CMMNTY_ID IS '커뮤니티ID';


COMMENT ON TABLE COMTNBBSMASTEROPTN IS '게시판마스터옵션'; 
COMMENT ON COLUMN COMTNBBSMASTEROPTN.BBS_ID IS '게시판ID'; 
COMMENT ON COLUMN COMTNBBSMASTEROPTN.ANSWER_AT IS '댓글여부'; 
COMMENT ON COLUMN COMTNBBSMASTEROPTN.STSFDG_AT IS '만족도여부'; 
COMMENT ON COLUMN COMTNBBSMASTEROPTN.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNBBSMASTEROPTN.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN COMTNBBSMASTEROPTN.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNBBSMASTEROPTN.LAST_UPDUSR_ID IS '최종수정자ID'; 
 

COMMENT ON TABLE COMTNBBSUSE IS '게시판활용'; 
COMMENT ON COLUMN COMTNBBSUSE.BBS_ID IS '게시판ID'; 
COMMENT ON COLUMN COMTNBBSUSE.TRGET_ID IS '대상ID'; 
COMMENT ON COLUMN COMTNBBSUSE.USE_AT IS '사용여부'; 
COMMENT ON COLUMN COMTNBBSUSE.REGIST_SE_CODE IS '등록구분코드'; 
COMMENT ON COLUMN COMTNBBSUSE.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNBBSUSE.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNBBSUSE.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN COMTNBBSUSE.LAST_UPDUSR_ID IS '최종수정자ID'; 
 

COMMENT ON TABLE COMTNBBS IS '게시판'; 
COMMENT ON COLUMN COMTNBBS.NTT_ID IS '게시물ID'; 
COMMENT ON COLUMN COMTNBBS.BBS_ID IS '게시판ID'; 
COMMENT ON COLUMN COMTNBBS.NTT_NO IS '게시물번호'; 
COMMENT ON COLUMN COMTNBBS.NTT_SJ IS '게시물제목'; 
COMMENT ON COLUMN COMTNBBS.NTT_CN IS '게시물내용'; 
COMMENT ON COLUMN COMTNBBS.ANSWER_AT IS '댓글여부'; 
COMMENT ON COLUMN COMTNBBS.PARNTSCTT_NO IS '부모글번호'; 
COMMENT ON COLUMN COMTNBBS.ANSWER_LC IS '댓글위치'; 
COMMENT ON COLUMN COMTNBBS.SORT_ORDR IS '정렬순서'; 
COMMENT ON COLUMN COMTNBBS.USE_AT IS '사용여부'; 
COMMENT ON COLUMN COMTNBBS.RDCNT IS '조회수'; 
COMMENT ON COLUMN COMTNBBS.NTCE_BGNDE IS '게시시작일'; 
COMMENT ON COLUMN COMTNBBS.NTCE_ENDDE IS '게시종료일'; 
COMMENT ON COLUMN COMTNBBS.NTCR_ID IS '게시자ID'; 
COMMENT ON COLUMN COMTNBBS.NTCR_NM IS '게시자명'; 
COMMENT ON COLUMN COMTNBBS.PASSWORD IS '비밀번호'; 
COMMENT ON COLUMN COMTNBBS.ATCH_FILE_ID IS '첨부파일ID'; 
COMMENT ON COLUMN COMTNBBS.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNBBS.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNBBS.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN COMTNBBS.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNBBS.BLOG_ID IS '블로그 ID';
COMMENT ON COLUMN COMTNBBS.NOTICE_AT IS '공지사항여부';
COMMENT ON COLUMN COMTNBBS.SECRET_AT IS '비밀글여부';
COMMENT ON COLUMN COMTNBBS.SJ_BOLD_AT IS '제목볼드여부';


COMMENT ON TABLE COMTNCOMMENT IS '댓글'; 
COMMENT ON COLUMN COMTNCOMMENT.NTT_ID IS '게시물ID'; 
COMMENT ON COLUMN COMTNCOMMENT.BBS_ID IS '게시판ID'; 
COMMENT ON COLUMN COMTNCOMMENT.ANSWER_NO IS '댓글번호'; 
COMMENT ON COLUMN COMTNCOMMENT.WRTER_ID IS '작성자ID'; 
COMMENT ON COLUMN COMTNCOMMENT.WRTER_NM IS '작성자명'; 
COMMENT ON COLUMN COMTNCOMMENT.ANSWER IS '댓글'; 
COMMENT ON COLUMN COMTNCOMMENT.USE_AT IS '사용여부'; 
COMMENT ON COLUMN COMTNCOMMENT.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNCOMMENT.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNCOMMENT.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN COMTNCOMMENT.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNCOMMENT.PASSWORD IS '비밀번호'; 


COMMENT ON TABLE COMTNSTSFDG IS '만족도'; 
COMMENT ON COLUMN COMTNSTSFDG.STSFDG_NO IS '만족도번호'; 
COMMENT ON COLUMN COMTNSTSFDG.NTT_ID IS '게시물ID'; 
COMMENT ON COLUMN COMTNSTSFDG.BBS_ID IS '게시판ID'; 
COMMENT ON COLUMN COMTNSTSFDG.WRTER_ID IS '작성자ID'; 
COMMENT ON COLUMN COMTNSTSFDG.WRTER_NM IS '작성자명'; 
COMMENT ON COLUMN COMTNSTSFDG.PASSWORD IS '비밀번호'; 
COMMENT ON COLUMN COMTNSTSFDG.STSFDG IS '만족도'; 
COMMENT ON COLUMN COMTNSTSFDG.STSFDG_CN IS '만족도내용'; 
COMMENT ON COLUMN COMTNSTSFDG.USE_AT IS '사용여부'; 
COMMENT ON COLUMN COMTNSTSFDG.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNSTSFDG.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN COMTNSTSFDG.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNSTSFDG.LAST_UPDUSR_ID IS '최종수정자ID'; 


COMMENT ON TABLE COMTNSCRAP IS '스크랩'; 
COMMENT ON COLUMN COMTNSCRAP.SCRAP_ID IS '스크랩ID'; 
COMMENT ON COLUMN COMTNSCRAP.NTT_ID IS '게시물ID'; 
COMMENT ON COLUMN COMTNSCRAP.BBS_ID IS '게시판ID'; 
COMMENT ON COLUMN COMTNSCRAP.SCRAP_NM IS '스크랩명'; 
COMMENT ON COLUMN COMTNSCRAP.USE_AT IS '사용여부'; 
COMMENT ON COLUMN COMTNSCRAP.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNSCRAP.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN COMTNSCRAP.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNSCRAP.LAST_UPDUSR_ID IS '최종수정자ID'; 

 
COMMENT ON TABLE COMTNCMMNTY IS '커뮤니티 속성'; 
COMMENT ON COLUMN COMTNCMMNTY.CMMNTY_ID IS '커뮤니티ID'; 
COMMENT ON COLUMN COMTNCMMNTY.CMMNTY_NM IS '커뮤니티명'; 
COMMENT ON COLUMN COMTNCMMNTY.CMMNTY_INTRCN IS '커뮤니티소개'; 
COMMENT ON COLUMN COMTNCMMNTY.USE_AT IS '사용여부'; 
COMMENT ON COLUMN COMTNCMMNTY.REGIST_SE_CODE IS '등록구분코드'; 
COMMENT ON COLUMN COMTNCMMNTY.TMPLAT_ID IS '템플릿ID'; 
COMMENT ON COLUMN COMTNCMMNTY.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNCMMNTY.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNCMMNTY.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN COMTNCMMNTY.LAST_UPDUSR_ID IS '최종수정자ID'; 


COMMENT ON TABLE COMTNCMMNTYUSER IS '커뮤니티사용자'; 
COMMENT ON COLUMN COMTNCMMNTYUSER.CMMNTY_ID IS '커뮤니티ID'; 
COMMENT ON COLUMN COMTNCMMNTYUSER.EMPLYR_ID IS '업무사용자ID'; 
COMMENT ON COLUMN COMTNCMMNTYUSER.MNGR_AT IS '관리자여부'; 
COMMENT ON COLUMN COMTNCMMNTYUSER.SBSCRB_DE IS '가입일자'; 
COMMENT ON COLUMN COMTNCMMNTYUSER.SECSN_DE IS '탈퇴일'; 
COMMENT ON COLUMN COMTNCMMNTYUSER.USE_AT IS '사용여부'; 
COMMENT ON COLUMN COMTNCMMNTYUSER.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNCMMNTYUSER.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNCMMNTYUSER.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN COMTNCMMNTYUSER.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNCMMNTYUSER.MBER_STTUS IS '회원 상태';
 

COMMENT ON TABLE COMTNCLUB IS '동호회속성'; 
COMMENT ON COLUMN COMTNCLUB.CLB_ID IS '동호회ID'; 
COMMENT ON COLUMN COMTNCLUB.CMMNTY_ID IS '커뮤니티ID'; 
COMMENT ON COLUMN COMTNCLUB.CLB_NM IS '동호회명'; 
COMMENT ON COLUMN COMTNCLUB.CLB_INTRCN IS '동호회소개'; 
COMMENT ON COLUMN COMTNCLUB.USE_AT IS '사용여부'; 
COMMENT ON COLUMN COMTNCLUB.REGIST_SE_CODE IS '등록구분코드'; 
COMMENT ON COLUMN COMTNCLUB.TMPLAT_ID IS '템플릿ID'; 
COMMENT ON COLUMN COMTNCLUB.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNCLUB.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNCLUB.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN COMTNCLUB.LAST_UPDUSR_ID IS '최종수정자ID'; 


COMMENT ON TABLE COMTNCLUBUSER IS '동호회사용자'; 
COMMENT ON COLUMN COMTNCLUBUSER.CLB_ID IS '동호회ID'; 
COMMENT ON COLUMN COMTNCLUBUSER.CMMNTY_ID IS '커뮤니티ID'; 
COMMENT ON COLUMN COMTNCLUBUSER.EMPLYR_ID IS '업무사용자ID'; 
COMMENT ON COLUMN COMTNCLUBUSER.OPRTR_AT IS '운영인여부'; 
COMMENT ON COLUMN COMTNCLUBUSER.SBSCRB_DE IS '가입일자'; 
COMMENT ON COLUMN COMTNCLUBUSER.SECSN_DE IS '탈퇴일'; 
COMMENT ON COLUMN COMTNCLUBUSER.USE_AT IS '사용여부'; 
COMMENT ON COLUMN COMTNCLUBUSER.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNCLUBUSER.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNCLUBUSER.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN COMTNCLUBUSER.LAST_UPDUSR_ID IS '최종수정자ID'; 
 

COMMENT ON TABLE COMTHCONFMHISTORY IS '승인이력'; 
COMMENT ON COLUMN COMTHCONFMHISTORY.CONFM_NO IS '승인번호'; 
COMMENT ON COLUMN COMTHCONFMHISTORY.CONFM_RQESTER_ID IS '승인요청자ID'; 
COMMENT ON COLUMN COMTHCONFMHISTORY.CONFMER_ID IS '승인자ID'; 
COMMENT ON COLUMN COMTHCONFMHISTORY.CONFM_DE IS '승인일'; 
COMMENT ON COLUMN COMTHCONFMHISTORY.CONFM_TY_CODE IS '승인유형코드'; 
COMMENT ON COLUMN COMTHCONFMHISTORY.CONFM_STTUS_CODE IS '승인상태코드'; 
COMMENT ON COLUMN COMTHCONFMHISTORY.OPERT_TY_CODE IS '작업유형코드'; 
COMMENT ON COLUMN COMTHCONFMHISTORY.OPERT_ID IS '작업ID'; 
COMMENT ON COLUMN COMTHCONFMHISTORY.TRGET_JOB_TY_CODE IS '대상업무유형코드'; 
COMMENT ON COLUMN COMTHCONFMHISTORY.TRGET_JOB_ID IS '대상업무ID'; 


COMMENT ON TABLE COMTNPROGRMLIST IS '프로그램목록'; 
COMMENT ON COLUMN COMTNPROGRMLIST.PROGRM_FILE_NM IS '프로그램파일명'; 
COMMENT ON COLUMN COMTNPROGRMLIST.PROGRM_STRE_PATH IS '프로그램저장경로'; 
COMMENT ON COLUMN COMTNPROGRMLIST.PROGRM_KOREAN_NM IS '프로그램한글명'; 
COMMENT ON COLUMN COMTNPROGRMLIST.PROGRM_DC IS '프로그램설명'; 
COMMENT ON COLUMN COMTNPROGRMLIST.URL IS 'URL'; 
 

COMMENT ON TABLE COMTHPROGRMCHANGEDTLS IS '프로그램변경내역'; 
COMMENT ON COLUMN COMTHPROGRMCHANGEDTLS.PROGRM_FILE_NM IS '프로그램파일명'; 
COMMENT ON COLUMN COMTHPROGRMCHANGEDTLS.REQUST_NO IS '요청번호'; 
COMMENT ON COLUMN COMTHPROGRMCHANGEDTLS.RQESTER_ID IS '요청자ID'; 
COMMENT ON COLUMN COMTHPROGRMCHANGEDTLS.CHANGE_REQUST_CN IS '변경요청내용'; 
COMMENT ON COLUMN COMTHPROGRMCHANGEDTLS.REQUST_PROCESS_CN IS '요청처리내용'; 
COMMENT ON COLUMN COMTHPROGRMCHANGEDTLS.OPETR_ID IS '처리자ID'; 
COMMENT ON COLUMN COMTHPROGRMCHANGEDTLS.PROCESS_STTUS_CODE IS '처리상태코드'; 
COMMENT ON COLUMN COMTHPROGRMCHANGEDTLS.PROCESS_DE IS '처리일'; 
COMMENT ON COLUMN COMTHPROGRMCHANGEDTLS.RQESTDE IS '요청일'; 
COMMENT ON COLUMN COMTHPROGRMCHANGEDTLS.REQUST_SJ IS '요청제목'; 
 
