
COMMENT ON TABLE COMTRDNMADRZIP IS '도로명주소';

COMMENT ON COLUMN COMTRDNMADRZIP.SN IS '일련번호';
COMMENT ON COLUMN COMTRDNMADRZIP.RDMN_CODE IS '도로명코드';
COMMENT ON COLUMN COMTRDNMADRZIP.CTPRVN_NM IS '시도명';
COMMENT ON COLUMN COMTRDNMADRZIP.SIGNGU_NM IS '시군구명';
COMMENT ON COLUMN COMTRDNMADRZIP.RDMN IS '도로명';
COMMENT ON COLUMN COMTRDNMADRZIP.BDNBR_MNNM IS '건물번호본번';
COMMENT ON COLUMN COMTRDNMADRZIP.BDNBR_SLNO IS '건물번호부번';
COMMENT ON COLUMN COMTRDNMADRZIP.BULD_NM IS '건물명';
COMMENT ON COLUMN COMTRDNMADRZIP.DETAIL_BULD_NM IS '상세건물명';
COMMENT ON COLUMN COMTRDNMADRZIP.ZIP IS '우편번호';
COMMENT ON COLUMN COMTRDNMADRZIP.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTRDNMADRZIP.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTRDNMADRZIP.LAST_UPDT_PNTTM IS '최종수정시점';
COMMENT ON COLUMN COMTRDNMADRZIP.LAST_UPDUSR_ID IS '최종수정자ID';

-----------------------

COMMENT ON TABLE IDS IS 'IDS';

COMMENT ON COLUMN IDS.IDGEN_TABLE_NM IS 'IDGEN테이블명';
COMMENT ON COLUMN IDS.IDGEN_NEXT_ID IS 'IDGEN다음ID';

------------------------

COMMENT ON TABLE COMTNANSWER IS '댓글';

COMMENT ON COLUMN COMTNANSWER.NTT_ID IS '게시물ID';
COMMENT ON COLUMN COMTNANSWER.BBS_ID IS '게시판ID';
COMMENT ON COLUMN COMTNANSWER.ANSWER_NO IS '답글번호';
COMMENT ON COLUMN COMTNANSWER.WRTER_ID IS '작성자ID';
COMMENT ON COLUMN COMTNANSWER.ANSWER IS '댓글';
COMMENT ON COLUMN COMTNANSWER.USE_AT IS '사용여부';
COMMENT ON COLUMN COMTNANSWER.WRTER_NM IS '작성자명';
COMMENT ON COLUMN COMTNANSWER.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNANSWER.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNANSWER.LAST_UPDT_PNTTM IS '최종수정시점';
COMMENT ON COLUMN COMTNANSWER.LAST_UPDUSR_ID IS '최종수정자ID';

-------------------------

COMMENT ON TABLE COMTNCOMMUTE IS '출퇴근관리';

COMMENT ON COLUMN COMTNCOMMUTE.EMPLYR_ID IS '직원 ID';
COMMENT ON COLUMN COMTNCOMMUTE.WRKT_DT IS '출근날짜';
COMMENT ON COLUMN COMTNCOMMUTE.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNCOMMUTE.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNCOMMUTE.LAST_UPDT_PNTTM IS '최종수정시점';
COMMENT ON COLUMN COMTNCOMMUTE.LAST_UPDUSR_ID IS '최종수정자ID';
COMMENT ON COLUMN COMTNCOMMUTE.ORGNZT_ID IS '부서 ID';
COMMENT ON COLUMN COMTNCOMMUTE.OVTMWRK_HOURS IS '초과근무시간';
COMMENT ON COLUMN COMTNCOMMUTE.RM IS '비고';
COMMENT ON COLUMN COMTNCOMMUTE.WRKTM_ID IS '출퇴근 구분 ID';
COMMENT ON COLUMN COMTNCOMMUTE.WRK_END_STATUS IS '퇴근상태';
COMMENT ON COLUMN COMTNCOMMUTE.WRK_END_TIME IS '퇴근시간';
COMMENT ON COLUMN COMTNCOMMUTE.WRK_HOURS IS '근무시간';
COMMENT ON COLUMN COMTNCOMMUTE.WRK_START_STATUS IS '출근상태';
COMMENT ON COLUMN COMTNCOMMUTE.WRK_START_TIME IS '출근시간';

-------------------------------

COMMENT ON TABLE COMTNLEADERSCHDULDE IS 'COMTNLEADERSCHDULDE';

COMMENT ON COLUMN COMTNLEADERSCHDULDE.SCHDUL_ID IS '일정ID';
COMMENT ON COLUMN COMTNLEADERSCHDULDE.SCHDUL_DE IS '일정일';

----------------------------------

COMMENT ON TABLE COMTNLEADERSTTUS IS '간부상태정보';

COMMENT ON COLUMN COMTNLEADERSTTUS.LEADER_ID IS '간부ID';
COMMENT ON COLUMN COMTNLEADERSTTUS.LEADER_STTUS IS '간부상태';
COMMENT ON COLUMN COMTNLEADERSTTUS.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNLEADERSTTUS.FRST_REGIST_PNTTM IS '최초등록자시점';
COMMENT ON COLUMN COMTNLEADERSTTUS.LAST_UPDUSR_ID IS '최종수정자ID';
COMMENT ON COLUMN COMTNLEADERSTTUS.LAST_UPDT_PNTTM IS '최종등록자시점';

-----------------------------------

COMMENT ON TABLE COMTNTWITTER IS '트위터계정관리';

COMMENT ON COLUMN COMTNTWITTER.USER_ID IS '사용자ID';
COMMENT ON COLUMN COMTNTWITTER.CNSMR_KEY IS '사용자열쇠';
COMMENT ON COLUMN COMTNTWITTER.CNSMR_SECRET IS '사용자비밀';
COMMENT ON COLUMN COMTNTWITTER.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNTWITTER.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNTWITTER.LAST_UPDUSR_ID IS '최종수정자ID';
COMMENT ON COLUMN COMTNTWITTER.LAST_UPDT_PNTTM IS '최종수정시점';



