 


COMMENT ON TABLE COMTHDBMNTRNGLOGINFO IS 'DB서비스모니터링로그정보'; 
COMMENT ON COLUMN COMTHDBMNTRNGLOGINFO.LOG_ID IS '로그ID'; 
COMMENT ON COLUMN COMTHDBMNTRNGLOGINFO.DATA_SOURC_NM IS '데이터소스명'; 
COMMENT ON COLUMN COMTHDBMNTRNGLOGINFO.SERVER_NM IS '서버명'; 
COMMENT ON COLUMN COMTHDBMNTRNGLOGINFO.DBMS_KND IS 'DBMS종류'; 
COMMENT ON COLUMN COMTHDBMNTRNGLOGINFO.CECK_SQL IS '체크SQL'; 
COMMENT ON COLUMN COMTHDBMNTRNGLOGINFO.MNGR_NM IS '관리자명'; 
COMMENT ON COLUMN COMTHDBMNTRNGLOGINFO.MNGR_EMAIL_ADRES IS '관리자이메일주소'; 
COMMENT ON COLUMN COMTHDBMNTRNGLOGINFO.MNTRNG_STTUS IS '모니터링상태'; 
COMMENT ON COLUMN COMTHDBMNTRNGLOGINFO.LOG_INFO IS '로그정보'; 
COMMENT ON COLUMN COMTHDBMNTRNGLOGINFO.CREAT_DT IS '생성일시'; 
COMMENT ON COLUMN COMTHDBMNTRNGLOGINFO.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTHDBMNTRNGLOGINFO.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTHDBMNTRNGLOGINFO.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN COMTHDBMNTRNGLOGINFO.LAST_UPDUSR_ID IS '최종수정자ID'; 
 



COMMENT ON TABLE COMTHHTTPMONLOGINFO IS 'HTTP서비스모니터링로그정보'; 
COMMENT ON COLUMN COMTHHTTPMONLOGINFO.SYS_ID IS '시스템ID'; 
COMMENT ON COLUMN COMTHHTTPMONLOGINFO.LOG_ID IS '로그ID'; 
COMMENT ON COLUMN COMTHHTTPMONLOGINFO.SITE_URL IS '사이트URL'; 
COMMENT ON COLUMN COMTHHTTPMONLOGINFO.WEBSVC_KND IS '웹서비스종류'; 
COMMENT ON COLUMN COMTHHTTPMONLOGINFO.HTTP_STTUS_CODE IS 'HTTP상태코드'; 
COMMENT ON COLUMN COMTHHTTPMONLOGINFO.CREAT_DT IS '생성일시'; 
COMMENT ON COLUMN COMTHHTTPMONLOGINFO.LOG_INFO IS '로그정보'; 
COMMENT ON COLUMN COMTHHTTPMONLOGINFO.MNGR_NM IS '관리자명'; 
COMMENT ON COLUMN COMTHHTTPMONLOGINFO.MNGR_EMAIL_ADRES IS '관리자이메일주소'; 
COMMENT ON COLUMN COMTHHTTPMONLOGINFO.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTHHTTPMONLOGINFO.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTHHTTPMONLOGINFO.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTHHTTPMONLOGINFO.LAST_UPDT_PNTTM IS '최종수정시점'; 
 


COMMENT ON TABLE COMTHTRSMRCVMNTRNGLOGINFO IS '송수신모니터링로그정보'; 
COMMENT ON COLUMN COMTHTRSMRCVMNTRNGLOGINFO.LOG_ID IS '로그ID'; 
COMMENT ON COLUMN COMTHTRSMRCVMNTRNGLOGINFO.CNTC_ID IS '연계ID'; 
COMMENT ON COLUMN COMTHTRSMRCVMNTRNGLOGINFO.TEST_CLASS_NM IS '테스트클래스명'; 
COMMENT ON COLUMN COMTHTRSMRCVMNTRNGLOGINFO.MNGR_NM IS '관리자명'; 
COMMENT ON COLUMN COMTHTRSMRCVMNTRNGLOGINFO.MNGR_EMAIL_ADRES IS '관리자이메일주소'; 
COMMENT ON COLUMN COMTHTRSMRCVMNTRNGLOGINFO.MNTRNG_STTUS IS '모니터링상태'; 
COMMENT ON COLUMN COMTHTRSMRCVMNTRNGLOGINFO.LOG_INFO IS '로그정보'; 
COMMENT ON COLUMN COMTHTRSMRCVMNTRNGLOGINFO.CREAT_DT IS '생성일시'; 
COMMENT ON COLUMN COMTHTRSMRCVMNTRNGLOGINFO.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTHTRSMRCVMNTRNGLOGINFO.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTHTRSMRCVMNTRNGLOGINFO.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTHTRSMRCVMNTRNGLOGINFO.LAST_UPDT_PNTTM IS '최종수정시점'; 


COMMENT ON TABLE COMTNADMINISTRATIONWORD IS '행정용어사전관리'; 
COMMENT ON COLUMN COMTNADMINISTRATIONWORD.ADMINIST_WORD_ID IS '행정용어ID'; 
COMMENT ON COLUMN COMTNADMINISTRATIONWORD.ADMINIST_WORD_NM IS '행정용어명'; 
COMMENT ON COLUMN COMTNADMINISTRATIONWORD.ADMINIST_WORD_ENG_NM IS '행정용어영문명'; 
COMMENT ON COLUMN COMTNADMINISTRATIONWORD.ADMINIST_WORD_ABRV_NM IS '행정용어약어명'; 
COMMENT ON COLUMN COMTNADMINISTRATIONWORD.THEMA_RELM IS '주제영역'; 
COMMENT ON COLUMN COMTNADMINISTRATIONWORD.WORD_SE IS '용어구분'; 
COMMENT ON COLUMN COMTNADMINISTRATIONWORD.RELATE_STD_WORD IS '관계표준용어'; 
COMMENT ON COLUMN COMTNADMINISTRATIONWORD.ADMINIST_WORD_DFN IS '행정용어정의'; 
COMMENT ON COLUMN COMTNADMINISTRATIONWORD.ADMINIST_WORD_DC IS '행정용어설명'; 
COMMENT ON COLUMN COMTNADMINISTRATIONWORD.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNADMINISTRATIONWORD.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNADMINISTRATIONWORD.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNADMINISTRATIONWORD.LAST_UPDT_PNTTM IS '최종수정시점'; 


COMMENT ON TABLE COMTNANSWER IS '댓글'; 
COMMENT ON COLUMN COMTNANSWER.NTT_ID IS '게시물ID'; 
COMMENT ON COLUMN COMTNANSWER.BBS_ID IS '게시판ID'; 
COMMENT ON COLUMN COMTNANSWER.ANSWER_NO IS '답글번호'; 
COMMENT ON COLUMN COMTNANSWER.WRTER_ID IS '작성자ID'; 
COMMENT ON COLUMN COMTNANSWER.ANSWER IS '댓글'; 
COMMENT ON COLUMN COMTNANSWER.USE_AT IS '사용여부'; 
COMMENT ON COLUMN COMTNANSWER.WRTER_NM IS '작성자명'; 
COMMENT ON COLUMN COMTNANSWER.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNANSWER.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNANSWER.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN COMTNANSWER.LAST_UPDUSR_ID IS '최종수정자ID'; 
 


COMMENT ON TABLE COMTNCNSLTLIST IS '상담내역'; 
COMMENT ON COLUMN COMTNCNSLTLIST.CNSLT_ID IS '상담ID'; 
COMMENT ON COLUMN COMTNCNSLTLIST.CNSLT_SJ IS '상담제목'; 
COMMENT ON COLUMN COMTNCNSLTLIST.OTHBC_AT IS '공개여부'; 
COMMENT ON COLUMN COMTNCNSLTLIST.EMAIL_ADRES IS '이메일주소'; 
COMMENT ON COLUMN COMTNCNSLTLIST.CNSLT_CN IS '상담내용'; 
COMMENT ON COLUMN COMTNCNSLTLIST.MANAGT_CN IS '조치내용'; 
COMMENT ON COLUMN COMTNCNSLTLIST.MANAGT_DE IS '조치일'; 
COMMENT ON COLUMN COMTNCNSLTLIST.RDCNT IS '조회수'; 
COMMENT ON COLUMN COMTNCNSLTLIST.ATCH_FILE_ID IS '첨부파일ID'; 
COMMENT ON COLUMN COMTNCNSLTLIST.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNCNSLTLIST.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNCNSLTLIST.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN COMTNCNSLTLIST.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNCNSLTLIST.AREA_NO IS '지역번호'; 
COMMENT ON COLUMN COMTNCNSLTLIST.MIDDLE_TELNO IS '중간전화번호'; 
COMMENT ON COLUMN COMTNCNSLTLIST.END_TELNO IS '끝전화번호'; 
COMMENT ON COLUMN COMTNCNSLTLIST.FRST_MBTLNUM IS '처음휴대폰번호'; 
COMMENT ON COLUMN COMTNCNSLTLIST.MIDDLE_MBTLNUM IS '중간이동전화번호'; 
COMMENT ON COLUMN COMTNCNSLTLIST.END_MBTLNUM IS '끝이동전화번호'; 
COMMENT ON COLUMN COMTNCNSLTLIST.WRITNG_DE IS '작성일'; 
COMMENT ON COLUMN COMTNCNSLTLIST.WRTER_NM IS '작성자명'; 
COMMENT ON COLUMN COMTNCNSLTLIST.EMAIL_ANSWER_AT IS '메일답변여부'; 
COMMENT ON COLUMN COMTNCNSLTLIST.QNA_PROCESS_STTUS_CODE IS '질의응답처리상태코드'; 
COMMENT ON COLUMN COMTNCNSLTLIST.WRITNG_PASSWORD IS '작성비밀번호'; 


COMMENT ON TABLE COMTNCNTNTSLIST IS '컨텐츠목록'; 
COMMENT ON COLUMN COMTNCNTNTSLIST.CNTNTS_ID IS '컨텐츠ID'; 
COMMENT ON COLUMN COMTNCNTNTSLIST.EMPLYR_ID IS '업무사용자ID'; 

 

COMMENT ON TABLE COMTNCOMMUTE IS '출퇴근관리'; 
COMMENT ON COLUMN COMTNCOMMUTE.EMPLYR_ID IS '업무사용자ID'; 
COMMENT ON COLUMN COMTNCOMMUTE.WRKT_DT IS '출근날짜'; 
COMMENT ON COLUMN COMTNCOMMUTE.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNCOMMUTE.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNCOMMUTE.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN COMTNCOMMUTE.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNCOMMUTE.ORGNZT_ID IS '조직ID'; 
COMMENT ON COLUMN COMTNCOMMUTE.OVTMWRK_HOURS IS '초과근무시간'; 
COMMENT ON COLUMN COMTNCOMMUTE.RM IS '비고'; 
COMMENT ON COLUMN COMTNCOMMUTE.WRKTM_ID IS '출퇴근 구분 ID'; 
COMMENT ON COLUMN COMTNCOMMUTE.WRK_END_STATUS IS '퇴근상태'; 
COMMENT ON COLUMN COMTNCOMMUTE.WRK_END_TIME IS '퇴근시간'; 
COMMENT ON COLUMN COMTNCOMMUTE.WRK_HOURS IS '근무시간'; 
COMMENT ON COLUMN COMTNCOMMUTE.WRK_START_STATUS IS '출근상태'; 
COMMENT ON COLUMN COMTNCOMMUTE.WRK_START_TIME IS '출근시간'; 

 
COMMENT ON TABLE COMTNCPYRHTINFO IS '저작권정보'; 
COMMENT ON COLUMN COMTNCPYRHTINFO.CPYRHT_ID IS '저작권ID'; 
COMMENT ON COLUMN COMTNCPYRHTINFO.CPYRHT_PRTC_POLICY_CN IS '저작권보호정책내용'; 
COMMENT ON COLUMN COMTNCPYRHTINFO.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNCPYRHTINFO.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNCPYRHTINFO.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN COMTNCPYRHTINFO.LAST_UPDUSR_ID IS '최종수정자ID'; 


 
COMMENT ON TABLE COMTNDAMCALRES IS '지식정보요청제공'; 
COMMENT ON COLUMN COMTNDAMCALRES.KNWLDG_ID IS '지식ID'; 
COMMENT ON COLUMN COMTNDAMCALRES.ORGNZT_ID IS '조직ID'; 
COMMENT ON COLUMN COMTNDAMCALRES.EXPERT_ID IS '전문가ID'; 
COMMENT ON COLUMN COMTNDAMCALRES.KNWLDG_TY_CODE IS '지식유형코드'; 
COMMENT ON COLUMN COMTNDAMCALRES.EMPLYR_ID IS '업무사용자ID'; 
COMMENT ON COLUMN COMTNDAMCALRES.KNWLDG_NM IS '지식명'; 
COMMENT ON COLUMN COMTNDAMCALRES.KNWLDG_CN IS '지식내용'; 
COMMENT ON COLUMN COMTNDAMCALRES.ATCH_FILE_ID IS '첨부파일ID'; 
COMMENT ON COLUMN COMTNDAMCALRES.PARNTS_KNWLDG_ID IS '부모지식ID'; 
COMMENT ON COLUMN COMTNDAMCALRES.ANSWER_DP IS '답변깊이'; 
COMMENT ON COLUMN COMTNDAMCALRES.ANSWER_ORDR IS '답변순서'; 
COMMENT ON COLUMN COMTNDAMCALRES.ANSWER_GROUP_NO IS '답변그룹번호'; 
COMMENT ON COLUMN COMTNDAMCALRES.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNDAMCALRES.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNDAMCALRES.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNDAMCALRES.LAST_UPDT_PNTTM IS '최종수정시점'; 

 
COMMENT ON TABLE COMTNDAMKNOIFM IS '지식정보'; 
COMMENT ON COLUMN COMTNDAMKNOIFM.KNWLDG_ID IS '지식ID'; 
COMMENT ON COLUMN COMTNDAMKNOIFM.KNWLDG_TY_CODE IS '지식유형코드'; 
COMMENT ON COLUMN COMTNDAMKNOIFM.ORGNZT_ID IS '조직ID'; 
COMMENT ON COLUMN COMTNDAMKNOIFM.EXPERT_ID IS '전문가ID'; 
COMMENT ON COLUMN COMTNDAMKNOIFM.EMPLYR_ID IS '업무사용자ID'; 
COMMENT ON COLUMN COMTNDAMKNOIFM.KNWLDG_NM IS '지식명'; 
COMMENT ON COLUMN COMTNDAMKNOIFM.KNWLDG_CN IS '지식내용'; 
COMMENT ON COLUMN COMTNDAMKNOIFM.KWRD IS '키워드'; 
COMMENT ON COLUMN COMTNDAMKNOIFM.OTHBC_AT IS '공개여부'; 
COMMENT ON COLUMN COMTNDAMKNOIFM.KNWLDG_EVL IS '지식평가'; 
COMMENT ON COLUMN COMTNDAMKNOIFM.COLCT_DE IS '수집일자'; 
COMMENT ON COLUMN COMTNDAMKNOIFM.EVL_DE IS '평가일자'; 
COMMENT ON COLUMN COMTNDAMKNOIFM.ATCH_FILE_ID IS '첨부파일ID'; 
COMMENT ON COLUMN COMTNDAMKNOIFM.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNDAMKNOIFM.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNDAMKNOIFM.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNDAMKNOIFM.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN COMTNDAMKNOIFM.DSUSE_DE IS '폐기일'; 

 
COMMENT ON TABLE COMTNDAMMAPKNO IS '지식맵(유형별)'; 
COMMENT ON COLUMN COMTNDAMMAPKNO.KNWLDG_TY_CODE IS '지식유형코드'; 
COMMENT ON COLUMN COMTNDAMMAPKNO.ORGNZT_ID IS '조직ID'; 
COMMENT ON COLUMN COMTNDAMMAPKNO.EXPERT_ID IS '전문가ID'; 
COMMENT ON COLUMN COMTNDAMMAPKNO.KNWLDG_TY_NM IS '지식유형명'; 
COMMENT ON COLUMN COMTNDAMMAPKNO.CL_DE IS '분류일'; 
COMMENT ON COLUMN COMTNDAMMAPKNO.KNWLDG_URL IS '지식URL'; 
COMMENT ON COLUMN COMTNDAMMAPKNO.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNDAMMAPKNO.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNDAMMAPKNO.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNDAMMAPKNO.LAST_UPDT_PNTTM IS '최종수정시점'; 

 
COMMENT ON TABLE COMTNDAMMAPTEAM IS '지식맵(조직별)'; 
COMMENT ON COLUMN COMTNDAMMAPTEAM.ORGNZT_ID IS '조직ID'; 
COMMENT ON COLUMN COMTNDAMMAPTEAM.ORGNZT_NM IS '조직명'; 
COMMENT ON COLUMN COMTNDAMMAPTEAM.CL_DE IS '분류일'; 
COMMENT ON COLUMN COMTNDAMMAPTEAM.KNWLDG_URL IS '지식URL'; 
COMMENT ON COLUMN COMTNDAMMAPTEAM.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNDAMMAPTEAM.LAST_UPDT_PNTTM IS '최종수정시점'; 


COMMENT ON TABLE COMTNDAMPRO IS '지식전문가'; 
COMMENT ON COLUMN COMTNDAMPRO.EXPERT_ID IS '전문가ID'; 
COMMENT ON COLUMN COMTNDAMPRO.KNWLDG_TY_CODE IS '지식유형코드'; 
COMMENT ON COLUMN COMTNDAMPRO.EXPERT_GRAD IS '전문가등급'; 
COMMENT ON COLUMN COMTNDAMPRO.EXPERT_CONFM_DE IS '전문가승인일'; 
COMMENT ON COLUMN COMTNDAMPRO.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNDAMPRO.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNDAMPRO.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNDAMPRO.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN COMTNDAMPRO.EXPERT_DC IS '전문가설명'; 

 
COMMENT ON TABLE COMTNDBMNTRNG IS 'DB서비스모니터링'; 
COMMENT ON COLUMN COMTNDBMNTRNG.DATA_SOURC_NM IS '데이터소스명'; 
COMMENT ON COLUMN COMTNDBMNTRNG.SERVER_NM IS '서버명'; 
COMMENT ON COLUMN COMTNDBMNTRNG.DBMS_KND IS 'DBMS종류'; 
COMMENT ON COLUMN COMTNDBMNTRNG.CECK_SQL IS '체크SQL'; 
COMMENT ON COLUMN COMTNDBMNTRNG.MNGR_NM IS '관리자명'; 
COMMENT ON COLUMN COMTNDBMNTRNG.MNGR_EMAIL_ADRES IS '관리자이메일주소'; 
COMMENT ON COLUMN COMTNDBMNTRNG.MNTRNG_STTUS IS '모니터링상태'; 
COMMENT ON COLUMN COMTNDBMNTRNG.CREAT_DT IS '생성일시'; 
COMMENT ON COLUMN COMTNDBMNTRNG.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNDBMNTRNG.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNDBMNTRNG.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNDBMNTRNG.LAST_UPDT_PNTTM IS '최종수정시점'; 
 


 


 
COMMENT ON TABLE COMTNFAQINFO IS 'FAQ정보'; 
COMMENT ON COLUMN COMTNFAQINFO.FAQ_ID IS 'FAQID'; 
COMMENT ON COLUMN COMTNFAQINFO.QESTN_SJ IS '질문제목'; 
COMMENT ON COLUMN COMTNFAQINFO.QESTN_CN IS '질문내용'; 
COMMENT ON COLUMN COMTNFAQINFO.ANSWER_CN IS '답변내용'; 
COMMENT ON COLUMN COMTNFAQINFO.RDCNT IS '조회수'; 
COMMENT ON COLUMN COMTNFAQINFO.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNFAQINFO.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNFAQINFO.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN COMTNFAQINFO.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNFAQINFO.ATCH_FILE_ID IS '첨부파일ID'; 
COMMENT ON COLUMN COMTNFAQINFO.QNA_PROCESS_STTUS_CODE IS '질의응답처리상태코드'; 



COMMENT ON TABLE COMTNFILESYSMNTRNG IS '파일시스템모니터링'; 
COMMENT ON COLUMN COMTNFILESYSMNTRNG.FILE_SYS_ID IS '파일시스템ID'; 
COMMENT ON COLUMN COMTNFILESYSMNTRNG.FILE_SYS_NM IS '파일시스템명'; 
COMMENT ON COLUMN COMTNFILESYSMNTRNG.FILE_SYS_MANAGE_NM IS '파일시스템관리명'; 
COMMENT ON COLUMN COMTNFILESYSMNTRNG.FILE_SYS_SIZE IS '파일시스템크기'; 
COMMENT ON COLUMN COMTNFILESYSMNTRNG.FILE_SYS_THRHLD IS '파일시스템임계치'; 
COMMENT ON COLUMN COMTNFILESYSMNTRNG.FILE_SYS_USGQTY IS '파일시스템사용량'; 
COMMENT ON COLUMN COMTNFILESYSMNTRNG.MNGR_NM IS '관리자명'; 
COMMENT ON COLUMN COMTNFILESYSMNTRNG.MNGR_EMAIL_ADRES IS '관리자이메일주소'; 
COMMENT ON COLUMN COMTNFILESYSMNTRNG.MNTRNG_STTUS IS '모니터링상태'; 
COMMENT ON COLUMN COMTNFILESYSMNTRNG.CREAT_DT IS '생성일시'; 
COMMENT ON COLUMN COMTNFILESYSMNTRNG.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNFILESYSMNTRNG.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNFILESYSMNTRNG.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNFILESYSMNTRNG.LAST_UPDT_PNTTM IS '최종수정시점'; 


COMMENT ON TABLE COMTNFILESYSMNTRNGLOGINFO IS '파일시스템모니터링로그정보'; 
COMMENT ON COLUMN COMTNFILESYSMNTRNGLOGINFO.FILE_SYS_ID IS '파일시스템ID'; 
COMMENT ON COLUMN COMTNFILESYSMNTRNGLOGINFO.LOG_ID IS '로그ID'; 
COMMENT ON COLUMN COMTNFILESYSMNTRNGLOGINFO.FILE_SYS_NM IS '파일시스템명'; 
COMMENT ON COLUMN COMTNFILESYSMNTRNGLOGINFO.FILE_SYS_MANAGE_NM IS '파일시스템관리명'; 
COMMENT ON COLUMN COMTNFILESYSMNTRNGLOGINFO.FILE_SYS_SIZE IS '파일시스템크기'; 
COMMENT ON COLUMN COMTNFILESYSMNTRNGLOGINFO.FILE_SYS_THRHLD IS '파일시스템임계치'; 
COMMENT ON COLUMN COMTNFILESYSMNTRNGLOGINFO.FILE_SYS_USGQTY IS '파일시스템사용량'; 
COMMENT ON COLUMN COMTNFILESYSMNTRNGLOGINFO.MNTRNG_STTUS IS '모니터링상태'; 
COMMENT ON COLUMN COMTNFILESYSMNTRNGLOGINFO.LOG_INFO IS '로그정보'; 
COMMENT ON COLUMN COMTNFILESYSMNTRNGLOGINFO.CREAT_DT IS '생성일시'; 
COMMENT ON COLUMN COMTNFILESYSMNTRNGLOGINFO.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNFILESYSMNTRNGLOGINFO.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNFILESYSMNTRNGLOGINFO.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNFILESYSMNTRNGLOGINFO.LAST_UPDT_PNTTM IS '최종수정시점'; 



COMMENT ON TABLE COMTNHPCMINFO IS '도움말정보'; 
COMMENT ON COLUMN COMTNHPCMINFO.HPCM_ID IS '도움말ID'; 
COMMENT ON COLUMN COMTNHPCMINFO.HPCM_SE_CODE IS '도움말구분코드'; 
COMMENT ON COLUMN COMTNHPCMINFO.HPCM_DFN IS '도움말정의'; 
COMMENT ON COLUMN COMTNHPCMINFO.HPCM_DC IS '도움말설명'; 
COMMENT ON COLUMN COMTNHPCMINFO.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNHPCMINFO.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNHPCMINFO.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN COMTNHPCMINFO.LAST_UPDUSR_ID IS '최종수정자ID'; 

 
COMMENT ON TABLE COMTNHTTPMON IS 'HTTP서비스모니터링'; 
COMMENT ON COLUMN COMTNHTTPMON.SYS_ID IS '시스템ID'; 
COMMENT ON COLUMN COMTNHTTPMON.SITE_URL IS '사이트URL'; 
COMMENT ON COLUMN COMTNHTTPMON.WEBSVC_KND IS '웹서비스종류'; 
COMMENT ON COLUMN COMTNHTTPMON.HTTP_STTUS_CODE IS 'HTTP상태코드'; 
COMMENT ON COLUMN COMTNHTTPMON.CREAT_DT IS '생성일시'; 
COMMENT ON COLUMN COMTNHTTPMON.MNGR_NM IS '관리자명'; 
COMMENT ON COLUMN COMTNHTTPMON.MNGR_EMAIL_ADRES IS '관리자이메일주소'; 
COMMENT ON COLUMN COMTNHTTPMON.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNHTTPMON.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNHTTPMON.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNHTTPMON.LAST_UPDT_PNTTM IS '최종수정시점'; 

 
COMMENT ON TABLE COMTNINDVDLINFOPOLICY IS '개인정보정책확인'; 
COMMENT ON COLUMN COMTNINDVDLINFOPOLICY.INDVDL_INFO_POLICY_ID IS '개인정보정책ID'; 
COMMENT ON COLUMN COMTNINDVDLINFOPOLICY.INDVDL_INFO_POLICY_CN IS '개인정보정책내용'; 
COMMENT ON COLUMN COMTNINDVDLINFOPOLICY.INDVDL_INFO_POLICY_AGRE_AT IS '개인정보정책동의여부'; 
COMMENT ON COLUMN COMTNINDVDLINFOPOLICY.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNINDVDLINFOPOLICY.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNINDVDLINFOPOLICY.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNINDVDLINFOPOLICY.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN COMTNINDVDLINFOPOLICY.INDVDL_INFO_POLICY_NM IS '개인정보정책명'; 


COMMENT ON TABLE COMTNINDVDLPGECNTNTS IS '마이페이지 컨텐츠'; 
COMMENT ON COLUMN COMTNINDVDLPGECNTNTS.CNTNTS_ID IS '컨텐츠ID'; 
COMMENT ON COLUMN COMTNINDVDLPGECNTNTS.CNTNTS_NM IS '컨텐츠명'; 
COMMENT ON COLUMN COMTNINDVDLPGECNTNTS.CNTC_URL IS '연계URL'; 
COMMENT ON COLUMN COMTNINDVDLPGECNTNTS.CNTNTS_USE_AT IS '컨텐츠사용여부'; 
COMMENT ON COLUMN COMTNINDVDLPGECNTNTS.CNTNTS_LINK_URL IS '컨텐츠링크URL'; 
COMMENT ON COLUMN COMTNINDVDLPGECNTNTS.CNTNTS_DC IS '컨텐츠설명'; 


COMMENT ON TABLE COMTNINDVDLPGEESTBS IS '마이페이지 설정'; 
COMMENT ON COLUMN COMTNINDVDLPGEESTBS.EMPLYR_ID IS '업무사용자ID'; 
COMMENT ON COLUMN COMTNINDVDLPGEESTBS.UPEND_IMAGE IS '상단이미지'; 
COMMENT ON COLUMN COMTNINDVDLPGEESTBS.TITLEBAR_COLOR IS '타이틀바색상'; 
COMMENT ON COLUMN COMTNINDVDLPGEESTBS.ALGN_MTHD IS '배열방식'; 
COMMENT ON COLUMN COMTNINDVDLPGEESTBS.ALGN_CO IS '배열개수'; 

 
 
 


COMMENT ON TABLE COMTNMTGINFO IS '회의정보'; 
COMMENT ON COLUMN COMTNMTGINFO.MTG_ID IS '회의ID'; 
COMMENT ON COLUMN COMTNMTGINFO.MTG_NM IS '회의명'; 
COMMENT ON COLUMN COMTNMTGINFO.MTG_MTR_CN IS '회의안건내용'; 
COMMENT ON COLUMN COMTNMTGINFO.MTG_SN IS '회의순번'; 
COMMENT ON COLUMN COMTNMTGINFO.MTG_CO IS '회의수'; 
COMMENT ON COLUMN COMTNMTGINFO.MTG_DE IS '회의일'; 
COMMENT ON COLUMN COMTNMTGINFO.MTG_PLACE IS '회의장소'; 
COMMENT ON COLUMN COMTNMTGINFO.MTG_BEGIN_TM IS '회의시작시간'; 
COMMENT ON COLUMN COMTNMTGINFO.MTG_END_TM IS '회의종료시간'; 
COMMENT ON COLUMN COMTNMTGINFO.CLSDR_MTG_AT IS '비공개회의여부'; 
COMMENT ON COLUMN COMTNMTGINFO.READNG_BGNDE IS '열람개시일'; 
COMMENT ON COLUMN COMTNMTGINFO.READNG_AT IS '열람여부'; 
COMMENT ON COLUMN COMTNMTGINFO.MTG_RESULT_CN IS '회의결과내용'; 
COMMENT ON COLUMN COMTNMTGINFO.MTG_RESULT_ENNC IS '회의결과유무'; 
COMMENT ON COLUMN COMTNMTGINFO.ETC_MATTER IS '기타사항'; 
COMMENT ON COLUMN COMTNMTGINFO.MNGT_DEPT_ID IS '주관부서ID'; 
COMMENT ON COLUMN COMTNMTGINFO.MNAER_ID IS '주관자ID'; 
COMMENT ON COLUMN COMTNMTGINFO.MNAER_DEPT_ID IS '주관자부서ID'; 
COMMENT ON COLUMN COMTNMTGINFO.MTG_AT IS '회의여부'; 
COMMENT ON COLUMN COMTNMTGINFO.NONATDRN_CO IS '불참자수'; 
COMMENT ON COLUMN COMTNMTGINFO.ATDRN_CO IS '참석자수'; 
COMMENT ON COLUMN COMTNMTGINFO.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNMTGINFO.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNMTGINFO.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN COMTNMTGINFO.LAST_UPDUSR_ID IS '최종수정자ID'; 




COMMENT ON TABLE COMTNNTWRKSVCMNTRNG IS '네트워크서비스모니터링'; 
COMMENT ON COLUMN COMTNNTWRKSVCMNTRNG.SYS_IP IS '시스템IP'; 
COMMENT ON COLUMN COMTNNTWRKSVCMNTRNG.SYS_PORT IS '시스템포트'; 
COMMENT ON COLUMN COMTNNTWRKSVCMNTRNG.SYS_NM IS '시스템명'; 
COMMENT ON COLUMN COMTNNTWRKSVCMNTRNG.MNGR_NM IS '관리자명'; 
COMMENT ON COLUMN COMTNNTWRKSVCMNTRNG.MNGR_EMAIL_ADRES IS '관리자이메일주소'; 
COMMENT ON COLUMN COMTNNTWRKSVCMNTRNG.MNTRNG_STTUS IS '모니터링상태'; 
COMMENT ON COLUMN COMTNNTWRKSVCMNTRNG.CREAT_DT IS '생성일시'; 
COMMENT ON COLUMN COMTNNTWRKSVCMNTRNG.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNNTWRKSVCMNTRNG.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNNTWRKSVCMNTRNG.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNNTWRKSVCMNTRNG.LAST_UPDT_PNTTM IS '최종수정시점'; 
 

COMMENT ON TABLE COMTNNTWRKSVCMNTRNGLOGINFO IS '네트워크서비스모니터링로그정보'; 
COMMENT ON COLUMN COMTNNTWRKSVCMNTRNGLOGINFO.SYS_IP IS '시스템IP'; 
COMMENT ON COLUMN COMTNNTWRKSVCMNTRNGLOGINFO.SYS_PORT IS '시스템포트'; 
COMMENT ON COLUMN COMTNNTWRKSVCMNTRNGLOGINFO.LOG_ID IS '로그ID'; 
COMMENT ON COLUMN COMTNNTWRKSVCMNTRNGLOGINFO.SYS_NM IS '시스템명'; 
COMMENT ON COLUMN COMTNNTWRKSVCMNTRNGLOGINFO.MNTRNG_STTUS IS '모니터링상태'; 
COMMENT ON COLUMN COMTNNTWRKSVCMNTRNGLOGINFO.LOG_INFO IS '로그정보'; 
COMMENT ON COLUMN COMTNNTWRKSVCMNTRNGLOGINFO.CREAT_DT IS '생성일시'; 
COMMENT ON COLUMN COMTNNTWRKSVCMNTRNGLOGINFO.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNNTWRKSVCMNTRNGLOGINFO.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNNTWRKSVCMNTRNGLOGINFO.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNNTWRKSVCMNTRNGLOGINFO.LAST_UPDT_PNTTM IS '최종수정시점'; 


COMMENT ON TABLE COMTNONLINEMANUAL IS '온라인메뉴얼'; 
COMMENT ON COLUMN COMTNONLINEMANUAL.ONLINE_MNL_ID IS '온라인메뉴얼ID'; 
COMMENT ON COLUMN COMTNONLINEMANUAL.ONLINE_MNL_SE_CODE IS '온라인메뉴얼구분코드'; 
COMMENT ON COLUMN COMTNONLINEMANUAL.ONLINE_MNL_DFN IS '온라인메뉴얼정의'; 
COMMENT ON COLUMN COMTNONLINEMANUAL.ONLINE_MNL_DC IS '온라인메뉴얼설명'; 
COMMENT ON COLUMN COMTNONLINEMANUAL.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNONLINEMANUAL.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNONLINEMANUAL.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNONLINEMANUAL.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN COMTNONLINEMANUAL.ONLINE_MNL_NM IS '온라인메뉴얼명'; 


COMMENT ON TABLE COMTNONLINEPOLLIEM IS '온라인POLL항목'; 
COMMENT ON COLUMN COMTNONLINEPOLLIEM.POLL_ID IS 'POLLID'; 
COMMENT ON COLUMN COMTNONLINEPOLLIEM.POLL_IEM_ID IS 'POLL항목ID'; 
COMMENT ON COLUMN COMTNONLINEPOLLIEM.POLL_IEM_NM IS 'POLL항목명'; 
COMMENT ON COLUMN COMTNONLINEPOLLIEM.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNONLINEPOLLIEM.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNONLINEPOLLIEM.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNONLINEPOLLIEM.LAST_UPDT_PNTTM IS '최종수정시점'; 
 

COMMENT ON TABLE COMTNONLINEPOLLMANAGE IS '온라인POLL관리'; 
COMMENT ON COLUMN COMTNONLINEPOLLMANAGE.POLL_ID IS 'POLLID'; 
COMMENT ON COLUMN COMTNONLINEPOLLMANAGE.POLL_NM IS 'POLL명'; 
COMMENT ON COLUMN COMTNONLINEPOLLMANAGE.POLL_BGNDE IS 'POLL시작일'; 
COMMENT ON COLUMN COMTNONLINEPOLLMANAGE.POLL_ENDDE IS 'POLL종료일'; 
COMMENT ON COLUMN COMTNONLINEPOLLMANAGE.POLL_KND IS 'POLL종류'; 
COMMENT ON COLUMN COMTNONLINEPOLLMANAGE.POLL_DSUSE_ENNC IS 'POLL폐기유무'; 
COMMENT ON COLUMN COMTNONLINEPOLLMANAGE.POLL_ATMC_DSUSE_ENNC IS 'POLL자동폐기유무'; 
COMMENT ON COLUMN COMTNONLINEPOLLMANAGE.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNONLINEPOLLMANAGE.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNONLINEPOLLMANAGE.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNONLINEPOLLMANAGE.LAST_UPDT_PNTTM IS '최종수정시점'; 

 
COMMENT ON TABLE COMTNONLINEPOLLRESULT IS '온라인POLL결과'; 
COMMENT ON COLUMN COMTNONLINEPOLLRESULT.POLL_RESULT_ID IS 'POLL결과ID'; 
COMMENT ON COLUMN COMTNONLINEPOLLRESULT.POLL_IEM_ID IS 'POLL항목ID'; 
COMMENT ON COLUMN COMTNONLINEPOLLRESULT.POLL_ID IS 'POLLID'; 
COMMENT ON COLUMN COMTNONLINEPOLLRESULT.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNONLINEPOLLRESULT.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNONLINEPOLLRESULT.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNONLINEPOLLRESULT.LAST_UPDT_PNTTM IS '최종수정시점'; 


COMMENT ON TABLE COMTNPRIVACYLOG IS '개인정보조회 로그'; 
COMMENT ON COLUMN COMTNPRIVACYLOG.REQUST_ID IS '요청 ID'; 
COMMENT ON COLUMN COMTNPRIVACYLOG.INQIRE_DT IS '조회일시'; 
COMMENT ON COLUMN COMTNPRIVACYLOG.INQIRE_INFO IS '조회 정보 명'; 
COMMENT ON COLUMN COMTNPRIVACYLOG.RQESTER_ID IS '요청자아이디'; 
COMMENT ON COLUMN COMTNPRIVACYLOG.RQESTER_IP IS '요청아이피'; 
COMMENT ON COLUMN COMTNPRIVACYLOG.SRVC_NM IS '서비스 명'; 


COMMENT ON TABLE COMTNPROCESSMON IS '프로세스모니터링'; 
COMMENT ON COLUMN COMTNPROCESSMON.PROCS_ID IS '프로세스ID'; 
COMMENT ON COLUMN COMTNPROCESSMON.PROCS_NM IS '프로세스명'; 
COMMENT ON COLUMN COMTNPROCESSMON.PROCS_STTUS IS '프로세스상태'; 
COMMENT ON COLUMN COMTNPROCESSMON.CREAT_DT IS '생성일시'; 
COMMENT ON COLUMN COMTNPROCESSMON.MNGR_NM IS '관리자명'; 
COMMENT ON COLUMN COMTNPROCESSMON.MNGR_EMAIL_ADRES IS '관리자이메일주소'; 
COMMENT ON COLUMN COMTNPROCESSMON.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNPROCESSMON.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNPROCESSMON.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNPROCESSMON.LAST_UPDT_PNTTM IS '최종수정시점'; 

 
COMMENT ON TABLE COMTNPROCESSMONLOGINFO IS '프로세스모니터링로그정보'; 
COMMENT ON COLUMN COMTNPROCESSMONLOGINFO.PROCS_ID IS '프로세스ID'; 
COMMENT ON COLUMN COMTNPROCESSMONLOGINFO.LOG_ID IS '로그ID'; 
COMMENT ON COLUMN COMTNPROCESSMONLOGINFO.PROCS_NM IS '프로세스명'; 
COMMENT ON COLUMN COMTNPROCESSMONLOGINFO.PROCS_STTUS IS '프로세스상태'; 
COMMENT ON COLUMN COMTNPROCESSMONLOGINFO.CREAT_DT IS '생성일시'; 
COMMENT ON COLUMN COMTNPROCESSMONLOGINFO.LOG_INFO IS '로그정보'; 
COMMENT ON COLUMN COMTNPROCESSMONLOGINFO.MNGR_NM IS '관리자명'; 
COMMENT ON COLUMN COMTNPROCESSMONLOGINFO.MNGR_EMAIL_ADRES IS '관리자이메일주소'; 
COMMENT ON COLUMN COMTNPROCESSMONLOGINFO.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNPROCESSMONLOGINFO.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNPROCESSMONLOGINFO.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNPROCESSMONLOGINFO.LAST_UPDT_PNTTM IS '최종수정시점'; 

 
COMMENT ON TABLE COMTNPROXYINFO IS '프록시정보'; 
COMMENT ON COLUMN COMTNPROXYINFO.PROXY_ID IS '프록시ID'; 
COMMENT ON COLUMN COMTNPROXYINFO.PROXY_NM IS '프록시명'; 
COMMENT ON COLUMN COMTNPROXYINFO.PROXY_IP IS '프록시IP'; 
COMMENT ON COLUMN COMTNPROXYINFO.PROXY_PORT IS '프록시포트'; 
COMMENT ON COLUMN COMTNPROXYINFO.TRGET_SVC_NM IS '대상서비스명'; 
COMMENT ON COLUMN COMTNPROXYINFO.SVC_DC IS '서비스설명'; 
COMMENT ON COLUMN COMTNPROXYINFO.SVC_IP IS '서비스IP'; 
COMMENT ON COLUMN COMTNPROXYINFO.SVC_PORT IS '서비스포트'; 
COMMENT ON COLUMN COMTNPROXYINFO.SVC_STTUS IS '서비스상태'; 
COMMENT ON COLUMN COMTNPROXYINFO.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNPROXYINFO.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNPROXYINFO.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNPROXYINFO.LAST_UPDT_PNTTM IS '최종수정시점'; 
 

COMMENT ON TABLE COMTNPROXYLOGINFO IS '프록시로그정보'; 
COMMENT ON COLUMN COMTNPROXYLOGINFO.PROXY_ID IS '프록시ID'; 
COMMENT ON COLUMN COMTNPROXYLOGINFO.LOG_ID IS '로그ID'; 
COMMENT ON COLUMN COMTNPROXYLOGINFO.CLNT_IP IS '클라이언트IP'; 
COMMENT ON COLUMN COMTNPROXYLOGINFO.CLNT_PORT IS '클라이언트포트'; 
COMMENT ON COLUMN COMTNPROXYLOGINFO.CONECT_TIME IS '접속시간'; 
COMMENT ON COLUMN COMTNPROXYLOGINFO.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNPROXYLOGINFO.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNPROXYLOGINFO.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNPROXYLOGINFO.LAST_UPDT_PNTTM IS '최종수정시점'; 
 

COMMENT ON TABLE COMTNQAINFO IS 'QA정보'; 
COMMENT ON COLUMN COMTNQAINFO.QA_ID IS 'QAID'; 
COMMENT ON COLUMN COMTNQAINFO.QESTN_SJ IS '질문제목'; 
COMMENT ON COLUMN COMTNQAINFO.QESTN_CN IS '질문내용'; 
COMMENT ON COLUMN COMTNQAINFO.WRITNG_DE IS '작성일'; 
COMMENT ON COLUMN COMTNQAINFO.RDCNT IS '조회수'; 
COMMENT ON COLUMN COMTNQAINFO.EMAIL_ADRES IS '이메일주소'; 
COMMENT ON COLUMN COMTNQAINFO.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNQAINFO.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNQAINFO.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN COMTNQAINFO.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNQAINFO.QNA_PROCESS_STTUS_CODE IS '질의응답처리상태코드'; 
COMMENT ON COLUMN COMTNQAINFO.WRTER_NM IS '작성자명'; 
COMMENT ON COLUMN COMTNQAINFO.ANSWER_CN IS '답변내용'; 
COMMENT ON COLUMN COMTNQAINFO.WRITNG_PASSWORD IS '작성비밀번호'; 
COMMENT ON COLUMN COMTNQAINFO.ANSWER_DE IS '답변일자'; 
COMMENT ON COLUMN COMTNQAINFO.EMAIL_ANSWER_AT IS '메일답변여부'; 
COMMENT ON COLUMN COMTNQAINFO.AREA_NO IS '지역번호'; 
COMMENT ON COLUMN COMTNQAINFO.MIDDLE_TELNO IS '중간전화번호'; 
COMMENT ON COLUMN COMTNQAINFO.END_TELNO IS '끝전화번호'; 

 
COMMENT ON TABLE COMTNQESTNRINFO IS '설문지정보'; 
COMMENT ON COLUMN COMTNQESTNRINFO.QUSTNR_TMPLAT_ID IS '설문템플릿ID'; 
COMMENT ON COLUMN COMTNQESTNRINFO.QESTNR_ID IS '설문지ID'; 
COMMENT ON COLUMN COMTNQESTNRINFO.QUSTNR_SJ IS '설문제목'; 
COMMENT ON COLUMN COMTNQESTNRINFO.QUSTNR_PURPS IS '설문목적'; 
COMMENT ON COLUMN COMTNQESTNRINFO.QUSTNR_WRITNG_GUIDANCE_CN IS '설문작성안내내용'; 
COMMENT ON COLUMN COMTNQESTNRINFO.QUSTNR_TRGET IS '설문대상'; 
COMMENT ON COLUMN COMTNQESTNRINFO.QUSTNR_BGNDE IS '설문시작일'; 
COMMENT ON COLUMN COMTNQESTNRINFO.QUSTNR_ENDDE IS '설문종료일'; 
COMMENT ON COLUMN COMTNQESTNRINFO.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNQESTNRINFO.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNQESTNRINFO.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN COMTNQESTNRINFO.LAST_UPDUSR_ID IS '최종수정자ID'; 


COMMENT ON TABLE COMTNQUSTNRIEM IS '설문항목'; 
COMMENT ON COLUMN COMTNQUSTNRIEM.QUSTNR_TMPLAT_ID IS '설문템플릿ID'; 
COMMENT ON COLUMN COMTNQUSTNRIEM.QESTNR_ID IS '설문지ID'; 
COMMENT ON COLUMN COMTNQUSTNRIEM.QUSTNR_QESITM_ID IS '설문문항ID'; 
COMMENT ON COLUMN COMTNQUSTNRIEM.QUSTNR_IEM_ID IS '설문항목ID'; 
COMMENT ON COLUMN COMTNQUSTNRIEM.IEM_SN IS '항목순번'; 
COMMENT ON COLUMN COMTNQUSTNRIEM.IEM_CN IS '항목내용'; 
COMMENT ON COLUMN COMTNQUSTNRIEM.ETC_ANSWER_AT IS '기타답변여부'; 
COMMENT ON COLUMN COMTNQUSTNRIEM.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNQUSTNRIEM.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNQUSTNRIEM.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN COMTNQUSTNRIEM.LAST_UPDUSR_ID IS '최종수정자ID'; 


COMMENT ON TABLE COMTNQUSTNRQESITM IS '설문문항'; 
COMMENT ON COLUMN COMTNQUSTNRQESITM.QESTNR_ID IS '설문지ID'; 
COMMENT ON COLUMN COMTNQUSTNRQESITM.QUSTNR_QESITM_ID IS '설문문항ID'; 
COMMENT ON COLUMN COMTNQUSTNRQESITM.QUSTNR_TMPLAT_ID IS '설문템플릿ID'; 
COMMENT ON COLUMN COMTNQUSTNRQESITM.QESTN_SN IS '질문순번'; 
COMMENT ON COLUMN COMTNQUSTNRQESITM.QESTN_TY_CODE IS '질문유형코드'; 
COMMENT ON COLUMN COMTNQUSTNRQESITM.QESTN_CN IS '질문내용'; 
COMMENT ON COLUMN COMTNQUSTNRQESITM.MXMM_CHOISE_CO IS '최대선택개수'; 
COMMENT ON COLUMN COMTNQUSTNRQESITM.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNQUSTNRQESITM.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNQUSTNRQESITM.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN COMTNQUSTNRQESITM.LAST_UPDUSR_ID IS '최종수정자ID'; 

 
COMMENT ON TABLE COMTNQUSTNRRESPONDINFO IS '설문응답자정보'; 
COMMENT ON COLUMN COMTNQUSTNRRESPONDINFO.QUSTNR_TMPLAT_ID IS '설문템플릿ID'; 
COMMENT ON COLUMN COMTNQUSTNRRESPONDINFO.QESTNR_ID IS '설문지ID'; 
COMMENT ON COLUMN COMTNQUSTNRRESPONDINFO.QUSTNR_RESPOND_ID IS '설문응답자ID'; 
COMMENT ON COLUMN COMTNQUSTNRRESPONDINFO.SEXDSTN_CODE IS '성별코드'; 
COMMENT ON COLUMN COMTNQUSTNRRESPONDINFO.OCCP_TY_CODE IS '직업유형코드'; 
COMMENT ON COLUMN COMTNQUSTNRRESPONDINFO.RESPOND_NM IS '응답자명'; 
COMMENT ON COLUMN COMTNQUSTNRRESPONDINFO.BRTHDY IS '생일'; 
COMMENT ON COLUMN COMTNQUSTNRRESPONDINFO.AREA_NO IS '지역번호'; 
COMMENT ON COLUMN COMTNQUSTNRRESPONDINFO.MIDDLE_TELNO IS '중간전화번호'; 
COMMENT ON COLUMN COMTNQUSTNRRESPONDINFO.END_TELNO IS '끝전화번호'; 
COMMENT ON COLUMN COMTNQUSTNRRESPONDINFO.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNQUSTNRRESPONDINFO.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNQUSTNRRESPONDINFO.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN COMTNQUSTNRRESPONDINFO.LAST_UPDUSR_ID IS '최종수정자ID'; 

 
COMMENT ON TABLE COMTNQUSTNRRSPNSRESULT IS '설문응답결과'; 
COMMENT ON COLUMN COMTNQUSTNRRSPNSRESULT.QUSTNR_RSPNS_RESULT_ID IS '설문응답결과ID'; 
COMMENT ON COLUMN COMTNQUSTNRRSPNSRESULT.QESTNR_ID IS '설문지ID'; 
COMMENT ON COLUMN COMTNQUSTNRRSPNSRESULT.QUSTNR_QESITM_ID IS '설문문항ID'; 
COMMENT ON COLUMN COMTNQUSTNRRSPNSRESULT.QUSTNR_TMPLAT_ID IS '설문템플릿ID'; 
COMMENT ON COLUMN COMTNQUSTNRRSPNSRESULT.RESPOND_ANSWER_CN IS '응답자답변내용'; 
COMMENT ON COLUMN COMTNQUSTNRRSPNSRESULT.ETC_ANSWER_CN IS '기타답변내용'; 
COMMENT ON COLUMN COMTNQUSTNRRSPNSRESULT.RESPOND_NM IS '응답자명'; 
COMMENT ON COLUMN COMTNQUSTNRRSPNSRESULT.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNQUSTNRRSPNSRESULT.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNQUSTNRRSPNSRESULT.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN COMTNQUSTNRRSPNSRESULT.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNQUSTNRRSPNSRESULT.QUSTNR_IEM_ID IS '설문항목ID'; 


COMMENT ON TABLE COMTNQUSTNRTMPLAT IS '설문템플릿'; 
COMMENT ON COLUMN COMTNQUSTNRTMPLAT.QUSTNR_TMPLAT_ID IS '설문템플릿ID'; 
COMMENT ON COLUMN COMTNQUSTNRTMPLAT.QUSTNR_TMPLAT_TY IS '설문템플릿유형'; 
COMMENT ON COLUMN COMTNQUSTNRTMPLAT.QUSTNR_TMPLAT_DC IS '설문템플릿설명'; 
COMMENT ON COLUMN COMTNQUSTNRTMPLAT.QUSTNR_TMPLAT_PATH_NM IS '설문템플릿경로명'; 
COMMENT ON COLUMN COMTNQUSTNRTMPLAT.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNQUSTNRTMPLAT.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNQUSTNRTMPLAT.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN COMTNQUSTNRTMPLAT.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNQUSTNRTMPLAT.QUSTNR_TMPLAT_IMAGE_INFO IS '설문템플릿이미지정보'; 

 
 



COMMENT ON TABLE COMTNROUGHMAP IS '약도관리'; 
COMMENT ON COLUMN COMTNROUGHMAP.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNROUGHMAP.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNROUGHMAP.INFOWINDOW IS '안내창 도움말'; 
COMMENT ON COLUMN COMTNROUGHMAP.LA IS '지도 위도'; 
COMMENT ON COLUMN COMTNROUGHMAP.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN COMTNROUGHMAP.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNROUGHMAP.LO IS '지도 경도'; 
COMMENT ON COLUMN COMTNROUGHMAP.MARKERLA IS '마커 위도'; 
COMMENT ON COLUMN COMTNROUGHMAP.MARKERLO IS '마커 경도'; 
COMMENT ON COLUMN COMTNROUGHMAP.ROUGHMAPADDRESS IS '약도상세주소'; 
COMMENT ON COLUMN COMTNROUGHMAP.ROUGHMAPSJ IS '약도 제목'; 
COMMENT ON COLUMN COMTNROUGHMAP.ROUGHMAP_ID IS '약도 ID'; 
COMMENT ON COLUMN COMTNROUGHMAP.ZOOMLEVEL IS '지도 확대수준'; 


COMMENT ON TABLE COMTNSERVEREQPMNINFO IS '서버장비정보'; 
COMMENT ON COLUMN COMTNSERVEREQPMNINFO.SERVER_EQPMN_ID IS '서버장비ID'; 
COMMENT ON COLUMN COMTNSERVEREQPMNINFO.SERVER_EQPMN_NM IS '서버장비명'; 
COMMENT ON COLUMN COMTNSERVEREQPMNINFO.SERVER_EQPMN_IP IS '서버장비IP'; 
COMMENT ON COLUMN COMTNSERVEREQPMNINFO.SERVER_EQPMN_MNGR IS '서버장비관리자'; 
COMMENT ON COLUMN COMTNSERVEREQPMNINFO.MNGR_EMAIL_ADRES IS '관리자이메일주소'; 
COMMENT ON COLUMN COMTNSERVEREQPMNINFO.OPERSYSM_INFO IS '운영체제정보'; 
COMMENT ON COLUMN COMTNSERVEREQPMNINFO.CPU_INFO IS 'CPU정보'; 
COMMENT ON COLUMN COMTNSERVEREQPMNINFO.MORY_INFO IS '메모리정보'; 
COMMENT ON COLUMN COMTNSERVEREQPMNINFO.HDDISK IS 'HDDISK'; 
COMMENT ON COLUMN COMTNSERVEREQPMNINFO.ETC_INFO IS '기타정보'; 
COMMENT ON COLUMN COMTNSERVEREQPMNINFO.RGSDE IS '등록일'; 
COMMENT ON COLUMN COMTNSERVEREQPMNINFO.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNSERVEREQPMNINFO.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNSERVEREQPMNINFO.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNSERVEREQPMNINFO.LAST_UPDT_PNTTM IS '최종수정시점'; 


COMMENT ON TABLE COMTNSERVEREQPMNRELATE IS '서버장비관계'; 
COMMENT ON COLUMN COMTNSERVEREQPMNRELATE.SERVER_EQPMN_ID IS '서버장비ID'; 
COMMENT ON COLUMN COMTNSERVEREQPMNRELATE.SERVER_ID IS '서버ID'; 
COMMENT ON COLUMN COMTNSERVEREQPMNRELATE.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNSERVEREQPMNRELATE.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNSERVEREQPMNRELATE.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNSERVEREQPMNRELATE.LAST_UPDT_PNTTM IS '최종수정시점'; 


COMMENT ON TABLE COMTNSERVERINFO IS '서버정보'; 
COMMENT ON COLUMN COMTNSERVERINFO.SERVER_ID IS '서버ID'; 
COMMENT ON COLUMN COMTNSERVERINFO.SERVER_NM IS '서버명'; 
COMMENT ON COLUMN COMTNSERVERINFO.SERVER_KND IS '서버종류'; 
COMMENT ON COLUMN COMTNSERVERINFO.RGSDE IS '등록일'; 
COMMENT ON COLUMN COMTNSERVERINFO.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNSERVERINFO.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNSERVERINFO.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNSERVERINFO.LAST_UPDT_PNTTM IS '최종수정시점'; 


COMMENT ON TABLE COMTNSERVERRESRCELOGINFO IS '서버자원로그정보'; 
COMMENT ON COLUMN COMTNSERVERRESRCELOGINFO.SERVER_EQPMN_ID IS '서버장비ID'; 
COMMENT ON COLUMN COMTNSERVERRESRCELOGINFO.LOG_ID IS '로그ID'; 
COMMENT ON COLUMN COMTNSERVERRESRCELOGINFO.SERVER_ID IS '서버ID'; 
COMMENT ON COLUMN COMTNSERVERRESRCELOGINFO.CPU_USE_RT IS 'CPU사용율'; 
COMMENT ON COLUMN COMTNSERVERRESRCELOGINFO.MORY_USE_RT IS '메모리사용율'; 
COMMENT ON COLUMN COMTNSERVERRESRCELOGINFO.SVC_STTUS IS '서비스상태'; 
COMMENT ON COLUMN COMTNSERVERRESRCELOGINFO.LOG_INFO IS '로그정보'; 
COMMENT ON COLUMN COMTNSERVERRESRCELOGINFO.CREAT_DT IS '생성일시'; 
COMMENT ON COLUMN COMTNSERVERRESRCELOGINFO.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNSERVERRESRCELOGINFO.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNSERVERRESRCELOGINFO.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNSERVERRESRCELOGINFO.LAST_UPDT_PNTTM IS '최종수정시점'; 

 
COMMENT ON TABLE COMTNSTPLATINFO IS '약관정보'; 
COMMENT ON COLUMN COMTNSTPLATINFO.USE_STPLAT_ID IS '이용약관ID'; 
COMMENT ON COLUMN COMTNSTPLATINFO.USE_STPLAT_NM IS '이용약관명'; 
COMMENT ON COLUMN COMTNSTPLATINFO.USE_STPLAT_CN IS '이용약관내용'; 
COMMENT ON COLUMN COMTNSTPLATINFO.INFO_PROVD_AGRE_CN IS '정보제공동의내용'; 
COMMENT ON COLUMN COMTNSTPLATINFO.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNSTPLATINFO.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNSTPLATINFO.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN COMTNSTPLATINFO.LAST_UPDUSR_ID IS '최종수정자ID'; 

 
COMMENT ON TABLE COMTNSYNCHRNSERVERINFO IS '동기화서버정보'; 
COMMENT ON COLUMN COMTNSYNCHRNSERVERINFO.SERVER_ID IS '서버ID'; 
COMMENT ON COLUMN COMTNSYNCHRNSERVERINFO.SERVER_NM IS '서버명'; 
COMMENT ON COLUMN COMTNSYNCHRNSERVERINFO.SERVER_IP IS '서버IP'; 
COMMENT ON COLUMN COMTNSYNCHRNSERVERINFO.SERVER_PORT IS '서버포트'; 
COMMENT ON COLUMN COMTNSYNCHRNSERVERINFO.FTP_ID IS 'FTPID'; 
COMMENT ON COLUMN COMTNSYNCHRNSERVERINFO.FTP_PASSWORD IS 'FTP비밀번호'; 
COMMENT ON COLUMN COMTNSYNCHRNSERVERINFO.SYNCHRN_LC IS '동기화위치'; 
COMMENT ON COLUMN COMTNSYNCHRNSERVERINFO.REFLCT_AT IS '반영여부'; 
COMMENT ON COLUMN COMTNSYNCHRNSERVERINFO.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNSYNCHRNSERVERINFO.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNSYNCHRNSERVERINFO.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNSYNCHRNSERVERINFO.LAST_UPDT_PNTTM IS '최종수정시점'; 
 

 

 
 
COMMENT ON TABLE COMTNTRSMRCVMNTRNG IS '송수신모니터링'; 
COMMENT ON COLUMN COMTNTRSMRCVMNTRNG.CNTC_ID IS '연계ID'; 
COMMENT ON COLUMN COMTNTRSMRCVMNTRNG.TEST_CLASS_NM IS '테스트클래스명'; 
COMMENT ON COLUMN COMTNTRSMRCVMNTRNG.MNGR_NM IS '관리자명'; 
COMMENT ON COLUMN COMTNTRSMRCVMNTRNG.MNGR_EMAIL_ADRES IS '관리자이메일주소'; 
COMMENT ON COLUMN COMTNTRSMRCVMNTRNG.MNTRNG_STTUS IS '모니터링상태'; 
COMMENT ON COLUMN COMTNTRSMRCVMNTRNG.CREAT_DT IS '생성일시'; 
COMMENT ON COLUMN COMTNTRSMRCVMNTRNG.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNTRSMRCVMNTRNG.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNTRSMRCVMNTRNG.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNTRSMRCVMNTRNG.LAST_UPDT_PNTTM IS '최종수정시점'; 
 

COMMENT ON TABLE COMTNTWITTER IS '트위터계정관리'; 
COMMENT ON COLUMN COMTNTWITTER.USER_ID IS '사용자ID'; 
COMMENT ON COLUMN COMTNTWITTER.CNSMR_KEY IS '사용자열쇠'; 
COMMENT ON COLUMN COMTNTWITTER.CNSMR_SECRET IS '사용자비밀'; 
COMMENT ON COLUMN COMTNTWITTER.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNTWITTER.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNTWITTER.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNTWITTER.LAST_UPDT_PNTTM IS '최종수정시점'; 
 

COMMENT ON TABLE COMTNWIKIBKMK IS 'Wiki북마크'; 
COMMENT ON COLUMN COMTNWIKIBKMK.WIKI_BKMK_ID IS 'Wiki즐겨찾기ID'; 
COMMENT ON COLUMN COMTNWIKIBKMK.USER_ID IS '사용자ID'; 
COMMENT ON COLUMN COMTNWIKIBKMK.WIKI_BKMK_NM IS 'Wiki북마크명'; 
COMMENT ON COLUMN COMTNWIKIBKMK.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNWIKIBKMK.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNWIKIBKMK.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN COMTNWIKIBKMK.LAST_UPDT_PNTTM IS '최종수정시점'; 
 



COMMENT ON TABLE COMTNWORDDICARYINFO IS '용어사전정보'; 
COMMENT ON COLUMN COMTNWORDDICARYINFO.WORD_ID IS '용어ID'; 
COMMENT ON COLUMN COMTNWORDDICARYINFO.WORD_NM IS '용어명'; 
COMMENT ON COLUMN COMTNWORDDICARYINFO.ENG_NM IS '영문명'; 
COMMENT ON COLUMN COMTNWORDDICARYINFO.WORD_DC IS '용어설명'; 
COMMENT ON COLUMN COMTNWORDDICARYINFO.SYNONM IS '동의어'; 
COMMENT ON COLUMN COMTNWORDDICARYINFO.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTNWORDDICARYINFO.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTNWORDDICARYINFO.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN COMTNWORDDICARYINFO.LAST_UPDUSR_ID IS '최종수정자ID'; 
 

COMMENT ON TABLE COMTRDNMADRZIP IS '도로명주소'; 
COMMENT ON COLUMN COMTRDNMADRZIP.SN IS '일련번호'; 
COMMENT ON COLUMN COMTRDNMADRZIP.RDMN_CODE IS '도로명코드'; 
COMMENT ON COLUMN COMTRDNMADRZIP.CTPRVN_NM IS '시도명'; 
COMMENT ON COLUMN COMTRDNMADRZIP.SIGNGU_NM IS '시군구명'; 
COMMENT ON COLUMN COMTRDNMADRZIP.RDMN IS '도로명'; 
COMMENT ON COLUMN COMTRDNMADRZIP.BDNBR_MNNM IS '건물번호본번'; 
COMMENT ON COLUMN COMTRDNMADRZIP.BDNBR_SLNO IS '건물번호부번'; 
COMMENT ON COLUMN COMTRDNMADRZIP.BULD_NM IS '건물명'; 
COMMENT ON COLUMN COMTRDNMADRZIP.DETAIL_BULD_NM IS '상세건물명'; 
COMMENT ON COLUMN COMTRDNMADRZIP.ZIP IS '우편번호'; 
COMMENT ON COLUMN COMTRDNMADRZIP.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN COMTRDNMADRZIP.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN COMTRDNMADRZIP.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN COMTRDNMADRZIP.LAST_UPDUSR_ID IS '최종수정자ID'; 


COMMENT ON TABLE IDS IS 'IDS'; 
COMMENT ON COLUMN IDS.IDGEN_TABLE_NM IS 'IDGEN테이블명'; 
COMMENT ON COLUMN IDS.IDGEN_NEXT_ID IS 'IDGEN다음ID'; 
 

COMMENT ON TABLE IMGTEMP IS 'IMGTEMP'; 
COMMENT ON COLUMN IMGTEMP.ORGNZT_CODE IS '조직코드'; 
COMMENT ON COLUMN IMGTEMP.ERNCSL_SE IS '전자관인구분'; 
COMMENT ON COLUMN IMGTEMP.IMAGE_INFO IS '이미지정보'; 
COMMENT ON COLUMN IMGTEMP.IMAGE_TY IS '이미지유형'; 


COMMENT ON TABLE J_ATTACHFILE IS 'Jfile업로드'; 
COMMENT ON COLUMN J_ATTACHFILE.FILE_ID IS '파일 아이디'; 
COMMENT ON COLUMN J_ATTACHFILE.FILE_SEQ IS '파일 순번'; 
COMMENT ON COLUMN J_ATTACHFILE.FILE_NAME IS '파일명'; 
COMMENT ON COLUMN J_ATTACHFILE.FILE_SIZE IS '파일 사이즈'; 
COMMENT ON COLUMN J_ATTACHFILE.FILE_MASK IS '파일 마스크'; 
COMMENT ON COLUMN J_ATTACHFILE.DOWNLOAD_COUNT IS '다운로드 횟수'; 
COMMENT ON COLUMN J_ATTACHFILE.DOWNLOAD_EXPIRE_DATE IS '다운로드 만료일'; 
COMMENT ON COLUMN J_ATTACHFILE.DOWNLOAD_LIMIT_COUNT IS '다운로드 제한 횟수'; 
COMMENT ON COLUMN J_ATTACHFILE.REG_DATE IS '등록일'; 
COMMENT ON COLUMN J_ATTACHFILE.DELETE_YN IS '삭제 구분'; 


COMMENT ON TABLE COMTNBLOG IS '블로그게시판';
COMMENT ON COLUMN COMTNBLOG.BBS_ID IS '게시판 ID';
COMMENT ON COLUMN COMTNBLOG.BLOG_AT  IS '블로그 여부';
COMMENT ON COLUMN COMTNBLOG.BLOG_ID IS '블로그 ID';
COMMENT ON COLUMN COMTNBLOG.BLOG_INTRCN IS '블로그 소개';
COMMENT ON COLUMN COMTNBLOG.BLOG_NM IS '블로그 명';
COMMENT ON COLUMN COMTNBLOG.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNBLOG.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNBLOG.LAST_UPDT_PNTTM IS '최종수정시점';
COMMENT ON COLUMN COMTNBLOG.LAST_UPDUSR_ID IS '최종수정자ID';
COMMENT ON COLUMN COMTNBLOG.REGIST_SE_CODE IS '등록구분코드';
COMMENT ON COLUMN COMTNBLOG.TMPLAT_ID IS '템플릿 ID';
COMMENT ON COLUMN COMTNBLOG.USE_AT IS '사용여부';


COMMENT ON TABLE COMTNBLOGUSER IS '블로그사용자';
COMMENT ON COLUMN COMTNBLOGUSER.BLOG_ID IS '블로그 ID';
COMMENT ON COLUMN COMTNBLOGUSER.EMPLYR_ID IS '업무사용자ID';
COMMENT ON COLUMN COMTNBLOGUSER.FRST_REGISTER_ID IS '최초등록자 ID';
COMMENT ON COLUMN COMTNBLOGUSER.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNBLOGUSER.LAST_UPDT_PNTTM IS '최종수정시점';
COMMENT ON COLUMN COMTNBLOGUSER.LAST_UPDUSR_ID IS '최종수정자 ID';
COMMENT ON COLUMN COMTNBLOGUSER.MBER_STTUS IS '회원상태';
COMMENT ON COLUMN COMTNBLOGUSER.MNGR_AT IS '관리자여부';
COMMENT ON COLUMN COMTNBLOGUSER.SBSCRB_DE IS '가입일자';
COMMENT ON COLUMN COMTNBLOGUSER.SECSN_DE IS '탈퇴일';
COMMENT ON COLUMN COMTNBLOGUSER.USE_AT IS '사용여부';

