// Simple CSS (className) plugin for the editor
// Sponsored by http://www.miro.com.au
// Original implementation by Mihai Bazon, http://dynarch.com/mishoo.
// Current implementation by Inferior Products Corporation, http://Inferior-Products.com
//
// (c) 2003-2013 Inferior-Products.com
// (c) dynarch.com 2003
// Distributed under the same terms as HTMLArea itself.
// This notice MUST stay intact for use (see license.txt).
//
// $Id: css.js,v 1.3 2010-11-10 00:21:50 sfchris Exp $
function CSS(editor,params){this.editor=editor;var cfg=editor.config;var toolbar=cfg.toolbar;var self=this;var i18n=CSS.I18N;var plugin_config=params[0];var combos=plugin_config.combos;var first=true;for(var i=combos.length;--i>=0;){var combo=combos[i];var id="CSS-class-"+(combo.id||i);var css_class={id:id,options:combo.options,action:function(editor){self.onSelect(editor,this,combo.context,combo.updatecontextclass);},refresh:function(editor){self.updateValue(editor,this);},context:combo.context};cfg.registerDropdown(css_class);toolbar[1].splice(0,0,first?"separator":"space");toolbar[1].splice(0,0,id);if(combo.label)toolbar[1].splice(0,0,"T["+combo.label+"]");first=false;}};CSS._pluginInfo={name:"CSS",version:"1.3",developer:"Inferior-Products",developer_url:"http://Inferior-Products.com/",c_owner:"SF_chris",sponsor:"Miro International",sponsor_url:"http://www.miro.com.au",license:"htmlArea"};CSS.prototype.onSelect=function(editor,obj,context,updatecontextclass){var tbobj=editor._toolbarObjects[obj.id];var index=tbobj.element.selectedIndex;var className=tbobj.element.value;var parent=editor.getParentElement();var surround=true;var is_span=(parent&&parent.tagName.toLowerCase()=="span");var update_parent=(context&&updatecontextclass&&parent&&parent.tagName.toLowerCase()==context);if(update_parent){parent.className=className;editor.updateToolbar();return;}if(is_span&&index==0&&!/\S/.test(parent.style.cssText)){while(parent.firstChild){parent.parentNode.insertBefore(parent.firstChild,parent);}parent.parentNode.removeChild(parent);editor.updateToolbar();return;}if(is_span){if(parent.childNodes.length==1){parent.className=className;surround=false;editor.updateToolbar();}}if(surround){editor.surroundHTML("<span class='"+className+"'>","</span>");}};CSS.prototype.updateValue=function(editor,obj){var select=editor._toolbarObjects[obj.id].element;var parent=editor.getParentElement();if(typeof parent.className!="undefined"&&/\S/.test(parent.className)){var options=select.options;var value=parent.className;for(var i=options.length;--i>=0;){var option=options[i];if(value==option.value){select.selectedIndex=i;return;}}}select.selectedIndex=0;};
